// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getBotEventStats = `-- name: GetBotEventStats :one

SELECT
    COUNT(*) FILTER (WHERE verdict = 'blocked'   AND created_at >= NOW() - INTERVAL '24 hours') AS blocked_24h,
    COUNT(*) FILTER (WHERE verdict = 'challenged' AND created_at >= NOW() - INTERVAL '24 hours') AS challenged_24h
FROM auth.bot_events WHERE tenant_id = $1
`

type GetBotEventStatsRow struct {
	Blocked24h    int64
	Challenged24h int64
}

// ListBotEvents is intentionally hand-written in bot.go because COALESCE(host(ip),”)
// causes sqlc to generate interface{} for the column type, making type-safe scanning
// impossible without runtime assertions.
func (q *Queries) GetBotEventStats(ctx context.Context, tenantID uuid.UUID) (GetBotEventStatsRow, error) {
	row := q.db.QueryRow(ctx, getBotEventStats, tenantID)
	var i GetBotEventStatsRow
	err := row.Scan(&i.Blocked24h, &i.Challenged24h)
	return i, err
}

const getBotSettings = `-- name: GetBotSettings :one
SELECT ua_check, honeypot, captcha, signature, score_threshold
FROM auth.bot_settings WHERE tenant_id = $1
`

type GetBotSettingsRow struct {
	UaCheck        bool
	Honeypot       bool
	Captcha        bool
	Signature      bool
	ScoreThreshold float32
}

func (q *Queries) GetBotSettings(ctx context.Context, tenantID uuid.UUID) (GetBotSettingsRow, error) {
	row := q.db.QueryRow(ctx, getBotSettings, tenantID)
	var i GetBotSettingsRow
	err := row.Scan(
		&i.UaCheck,
		&i.Honeypot,
		&i.Captcha,
		&i.Signature,
		&i.ScoreThreshold,
	)
	return i, err
}

const getUserTenantByEmail = `-- name: GetUserTenantByEmail :one

SELECT tenant_id FROM "user".users
WHERE LOWER(email) = LOWER($1) AND deleted_at IS NULL AND tenant_id IS NOT NULL
LIMIT 1
`

// Queries for the threat-detection/bot domain.
// Static queries are compiled by sqlc into ./dbgen.
// InsertBotEvent is intentionally hand-written in bot.go because it uses
// NULLIF($2,”)::inet — the inet cast makes sqlc parameter-type inference
// ambiguous; correctness takes priority over coverage.
func (q *Queries) GetUserTenantByEmail(ctx context.Context, lower string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUserTenantByEmail, lower)
	var tenant_id pgtype.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}

const upsertBotSettings = `-- name: UpsertBotSettings :exec
INSERT INTO auth.bot_settings (tenant_id, ua_check, honeypot, captcha, signature, score_threshold, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (tenant_id) DO UPDATE SET
    ua_check        = EXCLUDED.ua_check,
    honeypot        = EXCLUDED.honeypot,
    captcha         = EXCLUDED.captcha,
    signature       = EXCLUDED.signature,
    score_threshold = EXCLUDED.score_threshold,
    updated_at      = NOW()
`

type UpsertBotSettingsParams struct {
	TenantID       uuid.UUID
	UaCheck        bool
	Honeypot       bool
	Captcha        bool
	Signature      bool
	ScoreThreshold float32
}

func (q *Queries) UpsertBotSettings(ctx context.Context, arg UpsertBotSettingsParams) error {
	_, err := q.db.Exec(ctx, upsertBotSettings,
		arg.TenantID,
		arg.UaCheck,
		arg.Honeypot,
		arg.Captcha,
		arg.Signature,
		arg.ScoreThreshold,
	)
	return err
}
