// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getBranding = `-- name: GetBranding :one

SELECT tenant_id, logo_url, primary_color, secondary_color,
       custom_domain, email_from_name, email_from_address, settings
FROM tenant.branding WHERE tenant_id = $1
`

type GetBrandingRow struct {
	TenantID         uuid.UUID
	LogoUrl          *string
	PrimaryColor     *string
	SecondaryColor   *string
	CustomDomain     *string
	EmailFromName    *string
	EmailFromAddress *string
	Settings         []byte
}

// Queries for the branding domain.
// Static queries against tenant.branding live here and are compiled by sqlc into ./dbgen.
// The Upsert query uses a COALESCE/NULLIF expression that sqlc cannot parse reliably;
// it intentionally remains hand-written in branding.go.
func (q *Queries) GetBranding(ctx context.Context, tenantID uuid.UUID) (GetBrandingRow, error) {
	row := q.db.QueryRow(ctx, getBranding, tenantID)
	var i GetBrandingRow
	err := row.Scan(
		&i.TenantID,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.CustomDomain,
		&i.EmailFromName,
		&i.EmailFromAddress,
		&i.Settings,
	)
	return i, err
}
