// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteRelationTuple = `-- name: DeleteRelationTuple :execrows
DELETE FROM auth.relation_tuples WHERE id = $1 AND tenant_id = $2
`

type DeleteRelationTupleParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteRelationTuple(ctx context.Context, arg DeleteRelationTupleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRelationTuple, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fetchSubjects = `-- name: FetchSubjects :many
SELECT subject_type, subject_id, subject_relation
FROM auth.relation_tuples
WHERE tenant_id = $1 AND object_type = $2 AND object_id = $3 AND relation = $4
`

type FetchSubjectsParams struct {
	TenantID   uuid.UUID
	ObjectType string
	ObjectID   string
	Relation   string
}

type FetchSubjectsRow struct {
	SubjectType     string
	SubjectID       string
	SubjectRelation string
}

// Hot path for Check/Explain/Expand: fetch every subject granted relation on one object.
func (q *Queries) FetchSubjects(ctx context.Context, arg FetchSubjectsParams) ([]FetchSubjectsRow, error) {
	rows, err := q.db.Query(ctx, fetchSubjects,
		arg.TenantID,
		arg.ObjectType,
		arg.ObjectID,
		arg.Relation,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FetchSubjectsRow{}
	for rows.Next() {
		var i FetchSubjectsRow
		if err := rows.Scan(&i.SubjectType, &i.SubjectID, &i.SubjectRelation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRelationTuple = `-- name: InsertRelationTuple :one

INSERT INTO auth.relation_tuples
    (tenant_id, object_type, object_id, relation, subject_type, subject_id, subject_relation)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tenant_id, object_type, object_id, relation, subject_type, subject_id, subject_relation)
DO UPDATE SET tenant_id = EXCLUDED.tenant_id
RETURNING id
`

type InsertRelationTupleParams struct {
	TenantID        uuid.UUID
	ObjectType      string
	ObjectID        string
	Relation        string
	SubjectType     string
	SubjectID       string
	SubjectRelation string
}

// Queries for the rebac domain.
// All five SQL statements are fully static (the Zanzibar-style recursion
// lives in Go, not SQL), so all are converted.
func (q *Queries) InsertRelationTuple(ctx context.Context, arg InsertRelationTupleParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertRelationTuple,
		arg.TenantID,
		arg.ObjectType,
		arg.ObjectID,
		arg.Relation,
		arg.SubjectType,
		arg.SubjectID,
		arg.SubjectRelation,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listRelationTuplesByObject = `-- name: ListRelationTuplesByObject :many
SELECT id, relation, subject_type, subject_id, subject_relation
FROM auth.relation_tuples
WHERE tenant_id = $1 AND object_type = $2 AND object_id = $3
ORDER BY relation, subject_type, subject_id
`

type ListRelationTuplesByObjectParams struct {
	TenantID   uuid.UUID
	ObjectType string
	ObjectID   string
}

type ListRelationTuplesByObjectRow struct {
	ID              uuid.UUID
	Relation        string
	SubjectType     string
	SubjectID       string
	SubjectRelation string
}

func (q *Queries) ListRelationTuplesByObject(ctx context.Context, arg ListRelationTuplesByObjectParams) ([]ListRelationTuplesByObjectRow, error) {
	rows, err := q.db.Query(ctx, listRelationTuplesByObject, arg.TenantID, arg.ObjectType, arg.ObjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRelationTuplesByObjectRow{}
	for rows.Next() {
		var i ListRelationTuplesByObjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Relation,
			&i.SubjectType,
			&i.SubjectID,
			&i.SubjectRelation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationTuplesBySubject = `-- name: ListRelationTuplesBySubject :many
SELECT id, object_type, object_id, relation, subject_relation
FROM auth.relation_tuples
WHERE tenant_id = $1 AND subject_type = $2 AND subject_id = $3
ORDER BY object_type, object_id, relation
`

type ListRelationTuplesBySubjectParams struct {
	TenantID    uuid.UUID
	SubjectType string
	SubjectID   string
}

type ListRelationTuplesBySubjectRow struct {
	ID              uuid.UUID
	ObjectType      string
	ObjectID        string
	Relation        string
	SubjectRelation string
}

func (q *Queries) ListRelationTuplesBySubject(ctx context.Context, arg ListRelationTuplesBySubjectParams) ([]ListRelationTuplesBySubjectRow, error) {
	rows, err := q.db.Query(ctx, listRelationTuplesBySubject, arg.TenantID, arg.SubjectType, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRelationTuplesBySubjectRow{}
	for rows.Next() {
		var i ListRelationTuplesBySubjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Relation,
			&i.SubjectRelation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
