apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qeet-id

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - migration-job.yaml

commonLabels:
  app.kubernetes.io/name: qeet-id
  app.kubernetes.io/managed-by: kustomize
