// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*)
FROM auth.notifications
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertNotification = `-- name: InsertNotification :exec

INSERT INTO auth.notifications (user_id, tenant_id, kind, title, description, href)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertNotificationParams struct {
	UserID      uuid.UUID
	TenantID    pgtype.UUID
	Kind        string
	Title       string
	Description string
	Href        string
}

// Queries for the notifications domain.
// Static queries against auth.notifications live here and are compiled by
// sqlc into ./dbgen. There are no dynamic queries in this domain.
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.UserID,
		arg.TenantID,
		arg.Kind,
		arg.Title,
		arg.Description,
		arg.Href,
	)
	return err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, kind, title, description, href, created_at, read_at
FROM auth.notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListNotificationsParams struct {
	UserID   uuid.UUID
	RowLimit int32
}

type ListNotificationsRow struct {
	ID          uuid.UUID
	Kind        string
	Title       string
	Description string
	Href        string
	CreatedAt   time.Time
	ReadAt      pgtype.Timestamptz
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsRow{}
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Title,
			&i.Description,
			&i.Href,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE auth.notifications
SET read_at = NOW()
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}
