// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDomain = `-- name: DeleteDomain :execrows
DELETE FROM tenant.domains WHERE id = $1 AND tenant_id = $2
`

type DeleteDomainParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteDomain(ctx context.Context, arg DeleteDomainParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDomain, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDomainForVerify = `-- name: GetDomainForVerify :one
SELECT id, domain, verification_token, verified_at, created_at
FROM tenant.domains WHERE id = $1 AND tenant_id = $2
`

type GetDomainForVerifyParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type GetDomainForVerifyRow struct {
	ID                uuid.UUID
	Domain            string
	VerificationToken string
	VerifiedAt        pgtype.Timestamptz
	CreatedAt         time.Time
}

func (q *Queries) GetDomainForVerify(ctx context.Context, arg GetDomainForVerifyParams) (GetDomainForVerifyRow, error) {
	row := q.db.QueryRow(ctx, getDomainForVerify, arg.ID, arg.TenantID)
	var i GetDomainForVerifyRow
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.VerificationToken,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertDomain = `-- name: InsertDomain :one

INSERT INTO tenant.domains (tenant_id, domain, verification_token)
VALUES ($1, $2, $3)
RETURNING id, domain, verification_token, verified_at, created_at
`

type InsertDomainParams struct {
	TenantID          uuid.UUID
	Domain            string
	VerificationToken string
}

type InsertDomainRow struct {
	ID                uuid.UUID
	Domain            string
	VerificationToken string
	VerifiedAt        pgtype.Timestamptz
	CreatedAt         time.Time
}

// Queries for the domain-verification domain.
// All queries are static. Error handling for the unique-index violations
// (uq_tenant_domain, uq_verified_domain) stays in the service layer via
// strings.Contains checks preserved in domainverify.go.
func (q *Queries) InsertDomain(ctx context.Context, arg InsertDomainParams) (InsertDomainRow, error) {
	row := q.db.QueryRow(ctx, insertDomain, arg.TenantID, arg.Domain, arg.VerificationToken)
	var i InsertDomainRow
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.VerificationToken,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDomains = `-- name: ListDomains :many
SELECT id, domain, verification_token, verified_at, created_at
FROM tenant.domains WHERE tenant_id = $1 ORDER BY created_at DESC
`

type ListDomainsRow struct {
	ID                uuid.UUID
	Domain            string
	VerificationToken string
	VerifiedAt        pgtype.Timestamptz
	CreatedAt         time.Time
}

func (q *Queries) ListDomains(ctx context.Context, tenantID uuid.UUID) ([]ListDomainsRow, error) {
	rows, err := q.db.Query(ctx, listDomains, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDomainsRow{}
	for rows.Next() {
		var i ListDomainsRow
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.VerificationToken,
			&i.VerifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDomainVerified = `-- name: MarkDomainVerified :one
UPDATE tenant.domains SET verified_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, domain, verification_token, verified_at, created_at
`

type MarkDomainVerifiedParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type MarkDomainVerifiedRow struct {
	ID                uuid.UUID
	Domain            string
	VerificationToken string
	VerifiedAt        pgtype.Timestamptz
	CreatedAt         time.Time
}

func (q *Queries) MarkDomainVerified(ctx context.Context, arg MarkDomainVerifiedParams) (MarkDomainVerifiedRow, error) {
	row := q.db.QueryRow(ctx, markDomainVerified, arg.ID, arg.TenantID)
	var i MarkDomainVerifiedRow
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.VerificationToken,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}
