apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qeet-id
  namespace: qeet-id
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.id.qeet.in
      secretName: qeet-id-tls
  rules:
    - host: api.id.qeet.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qeet-id
                port:
                  name: http
