// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO tenant.group_members (group_id, user_id, tenant_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID  uuid.UUID
	UserID   uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addGroupMember, arg.GroupID, arg.UserID, arg.TenantID)
	return err
}

const checkUserInTenant = `-- name: CheckUserInTenant :one
SELECT EXISTS(
    SELECT 1 FROM "user".users WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
)
`

type CheckUserInTenantParams struct {
	ID       uuid.UUID
	TenantID pgtype.UUID
}

func (q *Queries) CheckUserInTenant(ctx context.Context, arg CheckUserInTenantParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserInTenant, arg.ID, arg.TenantID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countProvisionedUsers = `-- name: CountProvisionedUsers :one
SELECT count(*) FROM "user".users
WHERE tenant_id = $1 AND provisioned_via = 'scim' AND deleted_at IS NULL
`

func (q *Queries) CountProvisionedUsers(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProvisionedUsers, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteGroupMembers = `-- name: DeleteGroupMembers :exec
DELETE FROM tenant.group_members WHERE group_id = $1 AND tenant_id = $2
`

type DeleteGroupMembersParams struct {
	GroupID  uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteGroupMembers(ctx context.Context, arg DeleteGroupMembersParams) error {
	_, err := q.db.Exec(ctx, deleteGroupMembers, arg.GroupID, arg.TenantID)
	return err
}

const deleteScimGroup = `-- name: DeleteScimGroup :execrows
DELETE FROM tenant.groups WHERE id = $1 AND tenant_id = $2
`

type DeleteScimGroupParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteScimGroup(ctx context.Context, arg DeleteScimGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScimGroup, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteScimToken = `-- name: DeleteScimToken :execrows
DELETE FROM tenant.scim_tokens WHERE tenant_id = $1
`

func (q *Queries) DeleteScimToken(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScimToken, tenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProvisionedUser = `-- name: GetProvisionedUser :one

SELECT id, email, display_name, status, external_id, created_at, updated_at
FROM "user".users WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type GetProvisionedUserParams struct {
	ID       uuid.UUID
	TenantID pgtype.UUID
}

type GetProvisionedUserRow struct {
	ID          uuid.UUID
	Email       string
	DisplayName *string
	Status      string
	ExternalID  *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// ==========================================================================
// Users (provisioned read + tag)
// ==========================================================================
func (q *Queries) GetProvisionedUser(ctx context.Context, arg GetProvisionedUserParams) (GetProvisionedUserRow, error) {
	row := q.db.QueryRow(ctx, getProvisionedUser, arg.ID, arg.TenantID)
	var i GetProvisionedUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScimGroup = `-- name: GetScimGroup :one

SELECT id, name, external_id, created_at, updated_at
FROM tenant.groups WHERE id = $1 AND tenant_id = $2
`

type GetScimGroupParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type GetScimGroupRow struct {
	ID         uuid.UUID
	Name       string
	ExternalID *string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

// ==========================================================================
// Groups
// ==========================================================================
func (q *Queries) GetScimGroup(ctx context.Context, arg GetScimGroupParams) (GetScimGroupRow, error) {
	row := q.db.QueryRow(ctx, getScimGroup, arg.ID, arg.TenantID)
	var i GetScimGroupRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScimTokenConfig = `-- name: GetScimTokenConfig :one


SELECT token_prefix, created_at, last_used_at
FROM tenant.scim_tokens WHERE tenant_id = $1
`

type GetScimTokenConfigRow struct {
	TokenPrefix string
	CreatedAt   time.Time
	LastUsedAt  pgtype.Timestamptz
}

// Queries for the SCIM domain.
// DYNAMIC queries kept hand-written:
//
//	listProvisioned  — conditional WHERE + dynamic parameter positions for LIMIT/OFFSET
//	listGroups       — same conditional pattern with optional name filter
//	touchGroupTx     — CASE WHEN bool flag controls external_id update
//
// ==========================================================================
// Token management
// ==========================================================================
func (q *Queries) GetScimTokenConfig(ctx context.Context, tenantID uuid.UUID) (GetScimTokenConfigRow, error) {
	row := q.db.QueryRow(ctx, getScimTokenConfig, tenantID)
	var i GetScimTokenConfigRow
	err := row.Scan(&i.TokenPrefix, &i.CreatedAt, &i.LastUsedAt)
	return i, err
}

const getScimTokenTenant = `-- name: GetScimTokenTenant :one
SELECT tenant_id FROM tenant.scim_tokens WHERE token_hash = $1
`

func (q *Queries) GetScimTokenTenant(ctx context.Context, tokenHash string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getScimTokenTenant, tokenHash)
	var tenant_id uuid.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}

const insertScimGroup = `-- name: InsertScimGroup :one
INSERT INTO tenant.groups (tenant_id, name, external_id)
VALUES ($1, $2, $3)
RETURNING id, name, external_id, created_at, updated_at
`

type InsertScimGroupParams struct {
	TenantID   uuid.UUID
	Name       string
	ExternalID *string
}

type InsertScimGroupRow struct {
	ID         uuid.UUID
	Name       string
	ExternalID *string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) InsertScimGroup(ctx context.Context, arg InsertScimGroupParams) (InsertScimGroupRow, error) {
	row := q.db.QueryRow(ctx, insertScimGroup, arg.TenantID, arg.Name, arg.ExternalID)
	var i InsertScimGroupRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT gm.user_id, u.email, u.display_name
FROM tenant.group_members gm
JOIN "user".users u ON u.id = gm.user_id
WHERE gm.group_id = $1 AND gm.tenant_id = $2 AND u.deleted_at IS NULL
ORDER BY u.email
`

type ListGroupMembersParams struct {
	GroupID  uuid.UUID
	TenantID uuid.UUID
}

type ListGroupMembersRow struct {
	UserID      uuid.UUID
	Email       string
	DisplayName *string
}

func (q *Queries) ListGroupMembers(ctx context.Context, arg ListGroupMembersParams) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, arg.GroupID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupMembersRow{}
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(&i.UserID, &i.Email, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM tenant.group_members
WHERE group_id = $1 AND user_id = $2 AND tenant_id = $3
`

type RemoveGroupMemberParams struct {
	GroupID  uuid.UUID
	UserID   uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.UserID, arg.TenantID)
	return err
}

const tagProvisionedUser = `-- name: TagProvisionedUser :exec
UPDATE "user".users
    SET external_id    = $1,
        provisioned_via = 'scim',
        updated_at     = NOW()
WHERE id = $2
`

type TagProvisionedUserParams struct {
	ExternalID *string
	ID         uuid.UUID
}

func (q *Queries) TagProvisionedUser(ctx context.Context, arg TagProvisionedUserParams) error {
	_, err := q.db.Exec(ctx, tagProvisionedUser, arg.ExternalID, arg.ID)
	return err
}

const touchScimTokenUsed = `-- name: TouchScimTokenUsed :exec
UPDATE tenant.scim_tokens SET last_used_at = NOW() WHERE tenant_id = $1
`

func (q *Queries) TouchScimTokenUsed(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchScimTokenUsed, tenantID)
	return err
}

const upsertScimToken = `-- name: UpsertScimToken :exec
INSERT INTO tenant.scim_tokens (tenant_id, token_hash, token_prefix, created_at, last_used_at)
VALUES ($1, $2, $3, NOW(), NULL)
ON CONFLICT (tenant_id) DO UPDATE
    SET token_hash   = EXCLUDED.token_hash,
        token_prefix = EXCLUDED.token_prefix,
        created_at   = NOW(),
        last_used_at = NULL
`

type UpsertScimTokenParams struct {
	TenantID    uuid.UUID
	TokenHash   string
	TokenPrefix string
}

func (q *Queries) UpsertScimToken(ctx context.Context, arg UpsertScimTokenParams) error {
	_, err := q.db.Exec(ctx, upsertScimToken, arg.TenantID, arg.TokenHash, arg.TokenPrefix)
	return err
}
