// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const searchAuditEvents = `-- name: SearchAuditEvents :many
SELECT id, action, resource_type, resource_id, created_at
FROM audit.events
WHERE tenant_id = $1
  AND (action ILIKE $2 OR resource_type ILIKE $2)
ORDER BY created_at DESC, id
LIMIT $3
`

type SearchAuditEventsParams struct {
	TenantID pgtype.UUID
	Q        string
	RowLimit int32
}

type SearchAuditEventsRow struct {
	ID           uuid.UUID
	Action       string
	ResourceType string
	ResourceID   pgtype.UUID
	CreatedAt    time.Time
}

func (q *Queries) SearchAuditEvents(ctx context.Context, arg SearchAuditEventsParams) ([]SearchAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, searchAuditEvents, arg.TenantID, arg.Q, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchAuditEventsRow{}
	for rows.Next() {
		var i SearchAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchGroups = `-- name: SearchGroups :many
SELECT id, name, description, created_at
FROM tenant.groups
WHERE tenant_id = $1
  AND name ILIKE $2
ORDER BY created_at DESC, id
LIMIT $3
`

type SearchGroupsParams struct {
	TenantID uuid.UUID
	Q        string
	RowLimit int32
}

type SearchGroupsRow struct {
	ID          uuid.UUID
	Name        string
	Description string
	CreatedAt   time.Time
}

func (q *Queries) SearchGroups(ctx context.Context, arg SearchGroupsParams) ([]SearchGroupsRow, error) {
	rows, err := q.db.Query(ctx, searchGroups, arg.TenantID, arg.Q, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchGroupsRow{}
	for rows.Next() {
		var i SearchGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchOIDCClients = `-- name: SearchOIDCClients :many
SELECT id, name, client_id, type AS client_type, created_at
FROM auth.oidc_clients
WHERE tenant_id = $1
  AND (name ILIKE $2 OR client_id ILIKE $2)
ORDER BY created_at DESC, id
LIMIT $3
`

type SearchOIDCClientsParams struct {
	TenantID uuid.UUID
	Q        string
	RowLimit int32
}

type SearchOIDCClientsRow struct {
	ID         uuid.UUID
	Name       string
	ClientID   string
	ClientType string
	CreatedAt  time.Time
}

func (q *Queries) SearchOIDCClients(ctx context.Context, arg SearchOIDCClientsParams) ([]SearchOIDCClientsRow, error) {
	rows, err := q.db.Query(ctx, searchOIDCClients, arg.TenantID, arg.Q, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchOIDCClientsRow{}
	for rows.Next() {
		var i SearchOIDCClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClientID,
			&i.ClientType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchOrganization = `-- name: SearchOrganization :many
SELECT id, name, slug, status, updated_at
FROM tenant.tenants
WHERE id = $1
  AND (name ILIKE $2 OR slug ILIKE $2)
LIMIT 1
`

type SearchOrganizationParams struct {
	TenantID uuid.UUID
	Q        string
}

type SearchOrganizationRow struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	Status    string
	UpdatedAt time.Time
}

// Returns the caller's own tenant when its name or slug matches the query.
// At most one row (id = tenant_id is a PK equality).
func (q *Queries) SearchOrganization(ctx context.Context, arg SearchOrganizationParams) ([]SearchOrganizationRow, error) {
	rows, err := q.db.Query(ctx, searchOrganization, arg.TenantID, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchOrganizationRow{}
	for rows.Next() {
		var i SearchOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRoles = `-- name: SearchRoles :many
SELECT id, name, description, is_system, created_at
FROM rbac.roles
WHERE tenant_id = $1
  AND name ILIKE $2
ORDER BY created_at DESC, id
LIMIT $3
`

type SearchRolesParams struct {
	TenantID uuid.UUID
	Q        string
	RowLimit int32
}

type SearchRolesRow struct {
	ID          uuid.UUID
	Name        string
	Description string
	IsSystem    bool
	CreatedAt   time.Time
}

func (q *Queries) SearchRoles(ctx context.Context, arg SearchRolesParams) ([]SearchRolesRow, error) {
	rows, err := q.db.Query(ctx, searchRoles, arg.TenantID, arg.Q, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchRolesRow{}
	for rows.Next() {
		var i SearchRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many

SELECT id, email, display_name, status, updated_at
FROM "user".users
WHERE tenant_id = $1
  AND deleted_at IS NULL
  AND (email ILIKE $2 OR display_name ILIKE $2)
ORDER BY updated_at DESC, id
LIMIT $3
`

type SearchUsersParams struct {
	TenantID pgtype.UUID
	Q        string
	RowLimit int32
}

type SearchUsersRow struct {
	ID          uuid.UUID
	Email       string
	DisplayName *string
	Status      string
	UpdatedAt   time.Time
}

// Queries for the universal-search domain.
// Each query fetches one resource type scoped to the caller's tenant.
// The @q parameter must be passed as '%<query>%' (wildcards included) from
// the service layer so that the SQL remains a static parameterised query
// (no dynamic concatenation). Results are merged and scored in-memory by
// the service before being returned to the caller.
// pg_trgm is not enabled in this database, so fuzzy matching is ILIKE;
// prefix/exact scoring is computed in Go after the rows are fetched.
func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.TenantID, arg.Q, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Status,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
