// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeSamlLoginCode = `-- name: ConsumeSamlLoginCode :one
SELECT user_id, tenant_id, expires_at, used_at
FROM auth.saml_login_codes WHERE code_hash = $1 FOR UPDATE
`

type ConsumeSamlLoginCodeRow struct {
	UserID    uuid.UUID
	TenantID  uuid.UUID
	ExpiresAt time.Time
	UsedAt    pgtype.Timestamptz
}

func (q *Queries) ConsumeSamlLoginCode(ctx context.Context, codeHash string) (ConsumeSamlLoginCodeRow, error) {
	row := q.db.QueryRow(ctx, consumeSamlLoginCode, codeHash)
	var i ConsumeSamlLoginCodeRow
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const deleteSamlConnection = `-- name: DeleteSamlConnection :execrows
DELETE FROM tenant.saml_connections WHERE id = $1 AND tenant_id = $2
`

type DeleteSamlConnectionParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteSamlConnection(ctx context.Context, arg DeleteSamlConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSamlConnection, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSamlSP = `-- name: DeleteSamlSP :execrows
DELETE FROM tenant.saml_service_providers WHERE id = $1 AND tenant_id = $2
`

type DeleteSamlSPParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteSamlSP(ctx context.Context, arg DeleteSamlSPParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSamlSP, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getExternalIdentityUser = `-- name: GetExternalIdentityUser :one

SELECT user_id FROM "user".external_identities
WHERE tenant_id = $1 AND provider = $2 AND subject = $3
`

type GetExternalIdentityUserParams struct {
	TenantID uuid.UUID
	Provider string
	Subject  string
}

// ==========================================================================
// findOrCreateUser — same pattern as ldap (cross-schema "user" tables)
// ==========================================================================
func (q *Queries) GetExternalIdentityUser(ctx context.Context, arg GetExternalIdentityUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getExternalIdentityUser, arg.TenantID, arg.Provider, arg.Subject)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getSamlConnection = `-- name: GetSamlConnection :one
SELECT id, tenant_id, name, idp_entity_id, idp_sso_url, idp_certificate,
       email_attribute, name_attribute, status, created_at, updated_at, last_login_at
FROM tenant.saml_connections WHERE id = $1 AND tenant_id = $2
`

type GetSamlConnectionParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetSamlConnection(ctx context.Context, arg GetSamlConnectionParams) (TenantSamlConnection, error) {
	row := q.db.QueryRow(ctx, getSamlConnection, arg.ID, arg.TenantID)
	var i TenantSamlConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.IdpEntityID,
		&i.IdpSsoUrl,
		&i.IdpCertificate,
		&i.EmailAttribute,
		&i.NameAttribute,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getSamlConnectionByID = `-- name: GetSamlConnectionByID :one
SELECT id, tenant_id, name, idp_entity_id, idp_sso_url, idp_certificate,
       email_attribute, name_attribute, status, created_at, updated_at, last_login_at
FROM tenant.saml_connections WHERE id = $1
`

func (q *Queries) GetSamlConnectionByID(ctx context.Context, id uuid.UUID) (TenantSamlConnection, error) {
	row := q.db.QueryRow(ctx, getSamlConnectionByID, id)
	var i TenantSamlConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.IdpEntityID,
		&i.IdpSsoUrl,
		&i.IdpCertificate,
		&i.EmailAttribute,
		&i.NameAttribute,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getSamlSP = `-- name: GetSamlSP :one
SELECT id, tenant_id, name, entity_id, acs_url, name_id_format,
       name_id_attribute, certificate, status, created_at, updated_at, last_login_at
FROM tenant.saml_service_providers WHERE id = $1 AND tenant_id = $2
`

type GetSamlSPParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetSamlSP(ctx context.Context, arg GetSamlSPParams) (TenantSamlServiceProvider, error) {
	row := q.db.QueryRow(ctx, getSamlSP, arg.ID, arg.TenantID)
	var i TenantSamlServiceProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.EntityID,
		&i.AcsUrl,
		&i.NameIDFormat,
		&i.NameIDAttribute,
		&i.Certificate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getSamlSPByEntityID = `-- name: GetSamlSPByEntityID :one
SELECT id, tenant_id, name, entity_id, acs_url, name_id_format,
       name_id_attribute, certificate, status, created_at, updated_at, last_login_at
FROM tenant.saml_service_providers
WHERE entity_id = $1 AND status <> 'disabled' ORDER BY created_at LIMIT 1
`

func (q *Queries) GetSamlSPByEntityID(ctx context.Context, entityID string) (TenantSamlServiceProvider, error) {
	row := q.db.QueryRow(ctx, getSamlSPByEntityID, entityID)
	var i TenantSamlServiceProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.EntityID,
		&i.AcsUrl,
		&i.NameIDFormat,
		&i.NameIDAttribute,
		&i.Certificate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getSamlSPByUUID = `-- name: GetSamlSPByUUID :one
SELECT id, tenant_id, name, entity_id, acs_url, name_id_format,
       name_id_attribute, certificate, status, created_at, updated_at, last_login_at
FROM tenant.saml_service_providers WHERE id = $1
`

func (q *Queries) GetSamlSPByUUID(ctx context.Context, id uuid.UUID) (TenantSamlServiceProvider, error) {
	row := q.db.QueryRow(ctx, getSamlSPByUUID, id)
	var i TenantSamlServiceProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.EntityID,
		&i.AcsUrl,
		&i.NameIDFormat,
		&i.NameIDAttribute,
		&i.Certificate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id FROM "user".users WHERE LOWER(email) = LOWER($1) AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserForIdP = `-- name: GetUserForIdP :one
SELECT email, display_name, tenant_id FROM "user".users WHERE id = $1 AND deleted_at IS NULL
`

type GetUserForIdPRow struct {
	Email       string
	DisplayName *string
	TenantID    pgtype.UUID
}

func (q *Queries) GetUserForIdP(ctx context.Context, id uuid.UUID) (GetUserForIdPRow, error) {
	row := q.db.QueryRow(ctx, getUserForIdP, id)
	var i GetUserForIdPRow
	err := row.Scan(&i.Email, &i.DisplayName, &i.TenantID)
	return i, err
}

const insertSamlConnection = `-- name: InsertSamlConnection :one


INSERT INTO tenant.saml_connections
    (tenant_id, name, idp_entity_id, idp_sso_url, idp_certificate, email_attribute, name_attribute, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, name, idp_entity_id, idp_sso_url, idp_certificate,
          email_attribute, name_attribute, status, created_at, updated_at, last_login_at
`

type InsertSamlConnectionParams struct {
	TenantID       uuid.UUID
	Name           string
	IdpEntityID    string
	IdpSsoUrl      string
	IdpCertificate string
	EmailAttribute string
	NameAttribute  string
	Status         string
}

// Queries for the saml domain.
// Covers both saml.go (SP-side Service) and idp.go (IdP-side IdP struct).
// All queries are STATIC.
// ==========================================================================
// SP-side: external IdP connections (saml.go)
// ==========================================================================
func (q *Queries) InsertSamlConnection(ctx context.Context, arg InsertSamlConnectionParams) (TenantSamlConnection, error) {
	row := q.db.QueryRow(ctx, insertSamlConnection,
		arg.TenantID,
		arg.Name,
		arg.IdpEntityID,
		arg.IdpSsoUrl,
		arg.IdpCertificate,
		arg.EmailAttribute,
		arg.NameAttribute,
		arg.Status,
	)
	var i TenantSamlConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.IdpEntityID,
		&i.IdpSsoUrl,
		&i.IdpCertificate,
		&i.EmailAttribute,
		&i.NameAttribute,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const insertSamlLoginCode = `-- name: InsertSamlLoginCode :exec

INSERT INTO auth.saml_login_codes (code_hash, user_id, tenant_id, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertSamlLoginCodeParams struct {
	CodeHash  string
	UserID    uuid.UUID
	TenantID  uuid.UUID
	ExpiresAt time.Time
}

// ==========================================================================
// SAML login codes (ExchangeLogin + ACS handler)
// ==========================================================================
func (q *Queries) InsertSamlLoginCode(ctx context.Context, arg InsertSamlLoginCodeParams) error {
	_, err := q.db.Exec(ctx, insertSamlLoginCode,
		arg.CodeHash,
		arg.UserID,
		arg.TenantID,
		arg.ExpiresAt,
	)
	return err
}

const insertSamlSP = `-- name: InsertSamlSP :one

INSERT INTO tenant.saml_service_providers
    (tenant_id, name, entity_id, acs_url, name_id_format, name_id_attribute, certificate, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, name, entity_id, acs_url, name_id_format,
          name_id_attribute, certificate, status, created_at, updated_at, last_login_at
`

type InsertSamlSPParams struct {
	TenantID        uuid.UUID
	Name            string
	EntityID        string
	AcsUrl          string
	NameIDFormat    string
	NameIDAttribute string
	Certificate     string
	Status          string
}

// ==========================================================================
// IdP-side: Qeet as SAML provider (idp.go)
// ==========================================================================
func (q *Queries) InsertSamlSP(ctx context.Context, arg InsertSamlSPParams) (TenantSamlServiceProvider, error) {
	row := q.db.QueryRow(ctx, insertSamlSP,
		arg.TenantID,
		arg.Name,
		arg.EntityID,
		arg.AcsUrl,
		arg.NameIDFormat,
		arg.NameIDAttribute,
		arg.Certificate,
		arg.Status,
	)
	var i TenantSamlServiceProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.EntityID,
		&i.AcsUrl,
		&i.NameIDFormat,
		&i.NameIDAttribute,
		&i.Certificate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const insertUserWithEmail = `-- name: InsertUserWithEmail :one
INSERT INTO "user".users (tenant_id, email, email_verified_at, display_name, status)
VALUES ($1, $2, NOW(), $3, 'active')
RETURNING id
`

type InsertUserWithEmailParams struct {
	TenantID    pgtype.UUID
	Email       string
	DisplayName *string
}

func (q *Queries) InsertUserWithEmail(ctx context.Context, arg InsertUserWithEmailParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertUserWithEmail, arg.TenantID, arg.Email, arg.DisplayName)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const linkExternalIdentity = `-- name: LinkExternalIdentity :exec
INSERT INTO "user".external_identities (user_id, tenant_id, provider, subject, email)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, provider, subject) DO NOTHING
`

type LinkExternalIdentityParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
	Provider string
	Subject  string
	Email    *string
}

func (q *Queries) LinkExternalIdentity(ctx context.Context, arg LinkExternalIdentityParams) error {
	_, err := q.db.Exec(ctx, linkExternalIdentity,
		arg.UserID,
		arg.TenantID,
		arg.Provider,
		arg.Subject,
		arg.Email,
	)
	return err
}

const listSamlConnections = `-- name: ListSamlConnections :many
SELECT id, tenant_id, name, idp_entity_id, idp_sso_url, idp_certificate,
       email_attribute, name_attribute, status, created_at, updated_at, last_login_at
FROM tenant.saml_connections WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSamlConnections(ctx context.Context, tenantID uuid.UUID) ([]TenantSamlConnection, error) {
	rows, err := q.db.Query(ctx, listSamlConnections, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantSamlConnection{}
	for rows.Next() {
		var i TenantSamlConnection
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.IdpEntityID,
			&i.IdpSsoUrl,
			&i.IdpCertificate,
			&i.EmailAttribute,
			&i.NameAttribute,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSamlSPs = `-- name: ListSamlSPs :many
SELECT id, tenant_id, name, entity_id, acs_url, name_id_format,
       name_id_attribute, certificate, status, created_at, updated_at, last_login_at
FROM tenant.saml_service_providers WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSamlSPs(ctx context.Context, tenantID uuid.UUID) ([]TenantSamlServiceProvider, error) {
	rows, err := q.db.Query(ctx, listSamlSPs, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantSamlServiceProvider{}
	for rows.Next() {
		var i TenantSamlServiceProvider
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.EntityID,
			&i.AcsUrl,
			&i.NameIDFormat,
			&i.NameIDAttribute,
			&i.Certificate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSamlLoginCodeUsed = `-- name: MarkSamlLoginCodeUsed :exec
UPDATE auth.saml_login_codes SET used_at = NOW() WHERE code_hash = $1
`

func (q *Queries) MarkSamlLoginCodeUsed(ctx context.Context, codeHash string) error {
	_, err := q.db.Exec(ctx, markSamlLoginCodeUsed, codeHash)
	return err
}

const touchSamlLastLogin = `-- name: TouchSamlLastLogin :exec
UPDATE tenant.saml_connections SET last_login_at = NOW() WHERE id = $1
`

func (q *Queries) TouchSamlLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSamlLastLogin, id)
	return err
}

const touchSamlSPLastLogin = `-- name: TouchSamlSPLastLogin :exec
UPDATE tenant.saml_service_providers SET last_login_at = NOW() WHERE id = $1
`

func (q *Queries) TouchSamlSPLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSamlSPLastLogin, id)
	return err
}

const updateSamlConnection = `-- name: UpdateSamlConnection :one
UPDATE tenant.saml_connections SET
    name            = COALESCE($1, name),
    idp_entity_id   = COALESCE($2, idp_entity_id),
    idp_sso_url     = COALESCE($3, idp_sso_url),
    idp_certificate = COALESCE($4, idp_certificate),
    email_attribute = COALESCE($5, email_attribute),
    name_attribute  = COALESCE($6, name_attribute),
    status          = COALESCE($7, status),
    updated_at      = NOW()
WHERE id = $8 AND tenant_id = $9
RETURNING id, tenant_id, name, idp_entity_id, idp_sso_url, idp_certificate,
          email_attribute, name_attribute, status, created_at, updated_at, last_login_at
`

type UpdateSamlConnectionParams struct {
	Name           *string
	IdpEntityID    *string
	IdpSsoUrl      *string
	IdpCertificate *string
	EmailAttribute *string
	NameAttribute  *string
	Status         *string
	ID             uuid.UUID
	TenantID       uuid.UUID
}

func (q *Queries) UpdateSamlConnection(ctx context.Context, arg UpdateSamlConnectionParams) (TenantSamlConnection, error) {
	row := q.db.QueryRow(ctx, updateSamlConnection,
		arg.Name,
		arg.IdpEntityID,
		arg.IdpSsoUrl,
		arg.IdpCertificate,
		arg.EmailAttribute,
		arg.NameAttribute,
		arg.Status,
		arg.ID,
		arg.TenantID,
	)
	var i TenantSamlConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.IdpEntityID,
		&i.IdpSsoUrl,
		&i.IdpCertificate,
		&i.EmailAttribute,
		&i.NameAttribute,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const updateSamlSP = `-- name: UpdateSamlSP :one
UPDATE tenant.saml_service_providers SET
    name              = COALESCE($1, name),
    entity_id         = COALESCE($2, entity_id),
    acs_url           = COALESCE($3, acs_url),
    name_id_format    = COALESCE($4, name_id_format),
    name_id_attribute = COALESCE($5, name_id_attribute),
    certificate       = COALESCE($6, certificate),
    status            = COALESCE($7, status),
    updated_at        = NOW()
WHERE id = $8 AND tenant_id = $9
RETURNING id, tenant_id, name, entity_id, acs_url, name_id_format,
          name_id_attribute, certificate, status, created_at, updated_at, last_login_at
`

type UpdateSamlSPParams struct {
	Name            *string
	EntityID        *string
	AcsUrl          *string
	NameIDFormat    *string
	NameIDAttribute *string
	Certificate     *string
	Status          *string
	ID              uuid.UUID
	TenantID        uuid.UUID
}

func (q *Queries) UpdateSamlSP(ctx context.Context, arg UpdateSamlSPParams) (TenantSamlServiceProvider, error) {
	row := q.db.QueryRow(ctx, updateSamlSP,
		arg.Name,
		arg.EntityID,
		arg.AcsUrl,
		arg.NameIDFormat,
		arg.NameIDAttribute,
		arg.Certificate,
		arg.Status,
		arg.ID,
		arg.TenantID,
	)
	var i TenantSamlServiceProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.EntityID,
		&i.AcsUrl,
		&i.NameIDFormat,
		&i.NameIDAttribute,
		&i.Certificate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
