// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getActorBaseline = `-- name: GetActorBaseline :one
SELECT event_count, actions, hours, ips
FROM audit.actor_baselines
WHERE tenant_id = $1 AND actor_user_id = $2
FOR UPDATE
`

type GetActorBaselineParams struct {
	TenantID    uuid.UUID
	ActorUserID uuid.UUID
}

type GetActorBaselineRow struct {
	EventCount int64
	Actions    []byte
	Hours      []byte
	Ips        []byte
}

// Read the rolling counter baseline for one (tenant, actor) pair inside the
// caller's transaction.  FOR UPDATE serialises concurrent sweeps on the same
// actor so the fold step is applied exactly once per event.
func (q *Queries) GetActorBaseline(ctx context.Context, arg GetActorBaselineParams) (GetActorBaselineRow, error) {
	row := q.db.QueryRow(ctx, getActorBaseline, arg.TenantID, arg.ActorUserID)
	var i GetActorBaselineRow
	err := row.Scan(
		&i.EventCount,
		&i.Actions,
		&i.Hours,
		&i.Ips,
	)
	return i, err
}

const getAnomalySettings = `-- name: GetAnomalySettings :one

SELECT enabled, score_threshold, min_baseline_events
FROM audit.anomaly_settings WHERE tenant_id = $1
`

type GetAnomalySettingsRow struct {
	Enabled           bool
	ScoreThreshold    float64
	MinBaselineEvents int32
}

// Queries for the audit anomaly detection domain.
//
// All queries are static.  The List query is split into two variants
// (with/without status filter) following the sqlc idiomatic pattern used
// throughout the codebase for optional filters, rather than building the
// WHERE clause dynamically in Go.
// Load per-tenant anomaly detection settings; returns ErrNoRows when no row
// exists (the service falls back to package-level defaults in that case).
func (q *Queries) GetAnomalySettings(ctx context.Context, tenantID uuid.UUID) (GetAnomalySettingsRow, error) {
	row := q.db.QueryRow(ctx, getAnomalySettings, tenantID)
	var i GetAnomalySettingsRow
	err := row.Scan(&i.Enabled, &i.ScoreThreshold, &i.MinBaselineEvents)
	return i, err
}

const getAnomalySummary = `-- name: GetAnomalySummary :one
SELECT
    count(*) FILTER (WHERE status = 'open')                                          AS open_count,
    count(*) FILTER (WHERE status = 'resolved' AND resolved_at > NOW() - INTERVAL '7 days') AS resolved_7d,
    count(*) FILTER (WHERE status = 'open' AND score >= 0.85)                        AS high_score
FROM audit.anomalies WHERE tenant_id = $1
`

type GetAnomalySummaryRow struct {
	OpenCount  int64
	Resolved7d int64
	HighScore  int64
}

// Count open, recently-resolved, and high-score open anomalies for the
// tenant in a single pass (dashboard KPI cards).
func (q *Queries) GetAnomalySummary(ctx context.Context, tenantID uuid.UUID) (GetAnomalySummaryRow, error) {
	row := q.db.QueryRow(ctx, getAnomalySummary, tenantID)
	var i GetAnomalySummaryRow
	err := row.Scan(&i.OpenCount, &i.Resolved7d, &i.HighScore)
	return i, err
}

const insertAnomaly = `-- name: InsertAnomaly :exec
INSERT INTO audit.anomalies (tenant_id, event_id, actor_user_id, score, reasons)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (event_id) DO NOTHING
`

type InsertAnomalyParams struct {
	TenantID    uuid.UUID
	EventID     uuid.UUID
	ActorUserID pgtype.UUID
	Score       float64
	Reasons     []string
}

// Persist a scored deviation for admin review.  ON CONFLICT DO NOTHING is
// idempotent so a sweep retry can never create duplicate anomaly rows.
func (q *Queries) InsertAnomaly(ctx context.Context, arg InsertAnomalyParams) error {
	_, err := q.db.Exec(ctx, insertAnomaly,
		arg.TenantID,
		arg.EventID,
		arg.ActorUserID,
		arg.Score,
		arg.Reasons,
	)
	return err
}

const listAnomalies = `-- name: ListAnomalies :many
SELECT
    a.id, a.tenant_id, a.event_id, a.actor_user_id, u.email,
    a.score, a.reasons, a.status, a.resolved_at, a.resolved_by, a.created_at,
    e.action, e.resource_type, COALESCE(host(e.ip), '') AS ip, e.created_at AS event_at
FROM audit.anomalies a
JOIN audit.events e ON e.id = a.event_id
LEFT JOIN "user".users u ON u.id = a.actor_user_id
WHERE a.tenant_id = $1
ORDER BY a.created_at DESC
LIMIT $2
`

type ListAnomaliesParams struct {
	TenantID uuid.UUID
	RowLimit int32
}

type ListAnomaliesRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	EventID      uuid.UUID
	ActorUserID  pgtype.UUID
	Email        *string
	Score        float64
	Reasons      []string
	Status       string
	ResolvedAt   pgtype.Timestamptz
	ResolvedBy   pgtype.UUID
	CreatedAt    time.Time
	Action       string
	ResourceType string
	Ip           interface{}
	EventAt      time.Time
}

// List all anomalies (open and resolved) for a tenant, most recent first.
func (q *Queries) ListAnomalies(ctx context.Context, arg ListAnomaliesParams) ([]ListAnomaliesRow, error) {
	rows, err := q.db.Query(ctx, listAnomalies, arg.TenantID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnomaliesRow{}
	for rows.Next() {
		var i ListAnomaliesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventID,
			&i.ActorUserID,
			&i.Email,
			&i.Score,
			&i.Reasons,
			&i.Status,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.Action,
			&i.ResourceType,
			&i.Ip,
			&i.EventAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnomaliesFiltered = `-- name: ListAnomaliesFiltered :many
SELECT
    a.id, a.tenant_id, a.event_id, a.actor_user_id, u.email,
    a.score, a.reasons, a.status, a.resolved_at, a.resolved_by, a.created_at,
    e.action, e.resource_type, COALESCE(host(e.ip), '') AS ip, e.created_at AS event_at
FROM audit.anomalies a
JOIN audit.events e ON e.id = a.event_id
LEFT JOIN "user".users u ON u.id = a.actor_user_id
WHERE a.tenant_id = $1 AND a.status = $2
ORDER BY a.created_at DESC
LIMIT $3
`

type ListAnomaliesFilteredParams struct {
	TenantID uuid.UUID
	Status   string
	RowLimit int32
}

type ListAnomaliesFilteredRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	EventID      uuid.UUID
	ActorUserID  pgtype.UUID
	Email        *string
	Score        float64
	Reasons      []string
	Status       string
	ResolvedAt   pgtype.Timestamptz
	ResolvedBy   pgtype.UUID
	CreatedAt    time.Time
	Action       string
	ResourceType string
	Ip           interface{}
	EventAt      time.Time
}

// List anomalies for a tenant filtered by status, most recent first.
func (q *Queries) ListAnomaliesFiltered(ctx context.Context, arg ListAnomaliesFilteredParams) ([]ListAnomaliesFilteredRow, error) {
	rows, err := q.db.Query(ctx, listAnomaliesFiltered, arg.TenantID, arg.Status, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnomaliesFilteredRow{}
	for rows.Next() {
		var i ListAnomaliesFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventID,
			&i.ActorUserID,
			&i.Email,
			&i.Score,
			&i.Reasons,
			&i.Status,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.Action,
			&i.ResourceType,
			&i.Ip,
			&i.EventAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnscoredAuditEvents = `-- name: ListUnscoredAuditEvents :many
SELECT id, tenant_id, actor_user_id, action, COALESCE(host(ip), '') AS ip, created_at
FROM audit.events
WHERE scored_at IS NULL
ORDER BY created_at, id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type ListUnscoredAuditEventsRow struct {
	ID          uuid.UUID
	TenantID    pgtype.UUID
	ActorUserID pgtype.UUID
	Action      string
	Ip          interface{}
	CreatedAt   time.Time
}

// Pick a batch of unscored audit events in chronological order.
// FOR UPDATE SKIP LOCKED prevents two concurrent sweep workers from picking
// the same event (mirrors the outbox pattern).
// COALESCE ensures non-null result for ip (inet is nullable; host() of NULL = NULL).
func (q *Queries) ListUnscoredAuditEvents(ctx context.Context, batchSize int32) ([]ListUnscoredAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listUnscoredAuditEvents, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnscoredAuditEventsRow{}
	for rows.Next() {
		var i ListUnscoredAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorUserID,
			&i.Action,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAuditEventScored = `-- name: MarkAuditEventScored :exec
UPDATE audit.events SET scored_at = NOW() WHERE id = $1
`

// Stamp a processed event so it is never re-scored by the sweep.
func (q *Queries) MarkAuditEventScored(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAuditEventScored, id)
	return err
}

const resolveAnomaly = `-- name: ResolveAnomaly :execrows
UPDATE audit.anomalies
SET status = 'resolved', resolved_at = NOW(), resolved_by = $1
WHERE id = $2 AND tenant_id = $3 AND status = 'open'
`

type ResolveAnomalyParams struct {
	ResolvedBy pgtype.UUID
	ID         uuid.UUID
	TenantID   uuid.UUID
}

// Mark an open anomaly as resolved by a specific user.  Returns 0 rows
// affected when the anomaly is already resolved, not found, or belongs to a
// different tenant.
func (q *Queries) ResolveAnomaly(ctx context.Context, arg ResolveAnomalyParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveAnomaly, arg.ResolvedBy, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertActorBaseline = `-- name: UpsertActorBaseline :exec
INSERT INTO audit.actor_baselines
    (tenant_id, actor_user_id, event_count, actions, hours, ips, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (tenant_id, actor_user_id) DO UPDATE SET
    event_count = EXCLUDED.event_count,
    actions     = EXCLUDED.actions,
    hours       = EXCLUDED.hours,
    ips         = EXCLUDED.ips,
    updated_at  = NOW()
`

type UpsertActorBaselineParams struct {
	TenantID    uuid.UUID
	ActorUserID uuid.UUID
	EventCount  int64
	Actions     []byte
	Hours       []byte
	Ips         []byte
}

// Write (or create) the baseline counters after folding one event in.
func (q *Queries) UpsertActorBaseline(ctx context.Context, arg UpsertActorBaselineParams) error {
	_, err := q.db.Exec(ctx, upsertActorBaseline,
		arg.TenantID,
		arg.ActorUserID,
		arg.EventCount,
		arg.Actions,
		arg.Hours,
		arg.Ips,
	)
	return err
}

const upsertAnomalySettings = `-- name: UpsertAnomalySettings :exec
INSERT INTO audit.anomaly_settings
    (tenant_id, enabled, score_threshold, min_baseline_events, updated_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (tenant_id) DO UPDATE SET
    enabled             = EXCLUDED.enabled,
    score_threshold     = EXCLUDED.score_threshold,
    min_baseline_events = EXCLUDED.min_baseline_events,
    updated_at          = NOW()
`

type UpsertAnomalySettingsParams struct {
	TenantID          uuid.UUID
	Enabled           bool
	ScoreThreshold    float64
	MinBaselineEvents int32
}

// Create or replace per-tenant anomaly detection settings.
func (q *Queries) UpsertAnomalySettings(ctx context.Context, arg UpsertAnomalySettingsParams) error {
	_, err := q.db.Exec(ctx, upsertAnomalySettings,
		arg.TenantID,
		arg.Enabled,
		arg.ScoreThreshold,
		arg.MinBaselineEvents,
	)
	return err
}
