// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeSocialLoginCode = `-- name: ConsumeSocialLoginCode :one
SELECT user_id, tenant_id, expires_at, used_at
FROM auth.social_login_codes WHERE code_hash = $1 FOR UPDATE
`

type ConsumeSocialLoginCodeRow struct {
	UserID    uuid.UUID
	TenantID  uuid.UUID
	ExpiresAt time.Time
	UsedAt    pgtype.Timestamptz
}

func (q *Queries) ConsumeSocialLoginCode(ctx context.Context, codeHash string) (ConsumeSocialLoginCodeRow, error) {
	row := q.db.QueryRow(ctx, consumeSocialLoginCode, codeHash)
	var i ConsumeSocialLoginCodeRow
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const consumeSocialOAuthState = `-- name: ConsumeSocialOAuthState :one
DELETE FROM auth.social_oauth_states WHERE state_hash = $1
RETURNING tenant_id, provider, code_verifier, redirect_uri, return_to, expires_at
`

type ConsumeSocialOAuthStateRow struct {
	TenantID     uuid.UUID
	Provider     string
	CodeVerifier string
	RedirectUri  string
	ReturnTo     string
	ExpiresAt    time.Time
}

func (q *Queries) ConsumeSocialOAuthState(ctx context.Context, stateHash string) (ConsumeSocialOAuthStateRow, error) {
	row := q.db.QueryRow(ctx, consumeSocialOAuthState, stateHash)
	var i ConsumeSocialOAuthStateRow
	err := row.Scan(
		&i.TenantID,
		&i.Provider,
		&i.CodeVerifier,
		&i.RedirectUri,
		&i.ReturnTo,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExternalIdentity = `-- name: DeleteExternalIdentity :execrows
DELETE FROM "user".external_identities WHERE id = $1 AND tenant_id = $2
`

type DeleteExternalIdentityParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteExternalIdentity(ctx context.Context, arg DeleteExternalIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExternalIdentity, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enabledSocialProviderNames = `-- name: EnabledSocialProviderNames :many
SELECT provider FROM tenant.social_providers
WHERE tenant_id = $1 AND enabled ORDER BY provider
`

func (q *Queries) EnabledSocialProviderNames(ctx context.Context, tenantID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, enabledSocialProviderNames, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var provider string
		if err := rows.Scan(&provider); err != nil {
			return nil, err
		}
		items = append(items, provider)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExternalIdentityUser = `-- name: GetExternalIdentityUser :one

SELECT user_id FROM "user".external_identities
WHERE tenant_id = $1 AND provider = $2 AND subject = $3
`

type GetExternalIdentityUserParams struct {
	TenantID uuid.UUID
	Provider string
	Subject  string
}

// ==========================================================================
// findOrCreateUser — same cross-schema "user" pattern as ldap/saml
// ==========================================================================
func (q *Queries) GetExternalIdentityUser(ctx context.Context, arg GetExternalIdentityUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getExternalIdentityUser, arg.TenantID, arg.Provider, arg.Subject)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getTenantIDBySlug = `-- name: GetTenantIDBySlug :one
SELECT id FROM tenant.tenants WHERE slug = $1
`

func (q *Queries) GetTenantIDBySlug(ctx context.Context, slug string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTenantIDBySlug, slug)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id FROM "user".users WHERE LOWER(email) = LOWER($1) AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertSocialLoginCode = `-- name: InsertSocialLoginCode :exec
INSERT INTO auth.social_login_codes (code_hash, user_id, tenant_id, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertSocialLoginCodeParams struct {
	CodeHash  string
	UserID    uuid.UUID
	TenantID  uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) InsertSocialLoginCode(ctx context.Context, arg InsertSocialLoginCodeParams) error {
	_, err := q.db.Exec(ctx, insertSocialLoginCode,
		arg.CodeHash,
		arg.UserID,
		arg.TenantID,
		arg.ExpiresAt,
	)
	return err
}

const insertSocialOAuthState = `-- name: InsertSocialOAuthState :exec
INSERT INTO auth.social_oauth_states
    (state_hash, tenant_id, provider, code_verifier, redirect_uri, return_to, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertSocialOAuthStateParams struct {
	StateHash    string
	TenantID     uuid.UUID
	Provider     string
	CodeVerifier string
	RedirectUri  string
	ReturnTo     string
	ExpiresAt    time.Time
}

func (q *Queries) InsertSocialOAuthState(ctx context.Context, arg InsertSocialOAuthStateParams) error {
	_, err := q.db.Exec(ctx, insertSocialOAuthState,
		arg.StateHash,
		arg.TenantID,
		arg.Provider,
		arg.CodeVerifier,
		arg.RedirectUri,
		arg.ReturnTo,
		arg.ExpiresAt,
	)
	return err
}

const insertUserWithEmail = `-- name: InsertUserWithEmail :one
INSERT INTO "user".users (tenant_id, email, email_verified_at, display_name, status)
VALUES ($1, $2, NOW(), $3, 'active')
RETURNING id
`

type InsertUserWithEmailParams struct {
	TenantID    pgtype.UUID
	Email       string
	DisplayName *string
}

func (q *Queries) InsertUserWithEmail(ctx context.Context, arg InsertUserWithEmailParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertUserWithEmail, arg.TenantID, arg.Email, arg.DisplayName)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const linkExternalIdentity = `-- name: LinkExternalIdentity :exec
INSERT INTO "user".external_identities (user_id, tenant_id, provider, subject, email)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, provider, subject) DO NOTHING
`

type LinkExternalIdentityParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
	Provider string
	Subject  string
	Email    *string
}

func (q *Queries) LinkExternalIdentity(ctx context.Context, arg LinkExternalIdentityParams) error {
	_, err := q.db.Exec(ctx, linkExternalIdentity,
		arg.UserID,
		arg.TenantID,
		arg.Provider,
		arg.Subject,
		arg.Email,
	)
	return err
}

const listExternalIdentities = `-- name: ListExternalIdentities :many
SELECT ei.id, ei.user_id, ei.tenant_id, ei.provider, ei.subject, ei.email, ei.linked_at
FROM "user".external_identities ei
JOIN "user".users u ON u.id = ei.user_id
WHERE ei.user_id = $1 AND ei.tenant_id = $2 AND u.deleted_at IS NULL
ORDER BY ei.linked_at DESC
`

type ListExternalIdentitiesParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
}

type ListExternalIdentitiesRow struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	TenantID uuid.UUID
	Provider string
	Subject  string
	Email    *string
	LinkedAt time.Time
}

func (q *Queries) ListExternalIdentities(ctx context.Context, arg ListExternalIdentitiesParams) ([]ListExternalIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, listExternalIdentities, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExternalIdentitiesRow{}
	for rows.Next() {
		var i ListExternalIdentitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.Provider,
			&i.Subject,
			&i.Email,
			&i.LinkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSocialProviders = `-- name: ListSocialProviders :many
SELECT id, tenant_id, provider, client_id, discovery_url, enabled, created_at
FROM tenant.social_providers WHERE tenant_id = $1 ORDER BY provider
`

type ListSocialProvidersRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Provider     string
	ClientID     string
	DiscoveryUrl *string
	Enabled      bool
	CreatedAt    time.Time
}

func (q *Queries) ListSocialProviders(ctx context.Context, tenantID uuid.UUID) ([]ListSocialProvidersRow, error) {
	rows, err := q.db.Query(ctx, listSocialProviders, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSocialProvidersRow{}
	for rows.Next() {
		var i ListSocialProvidersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Provider,
			&i.ClientID,
			&i.DiscoveryUrl,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadSocialProvider = `-- name: LoadSocialProvider :one
SELECT client_id, client_secret, discovery_url, enabled
FROM tenant.social_providers WHERE tenant_id = $1 AND provider = $2
`

type LoadSocialProviderParams struct {
	TenantID uuid.UUID
	Provider string
}

type LoadSocialProviderRow struct {
	ClientID     string
	ClientSecret string
	DiscoveryUrl *string
	Enabled      bool
}

func (q *Queries) LoadSocialProvider(ctx context.Context, arg LoadSocialProviderParams) (LoadSocialProviderRow, error) {
	row := q.db.QueryRow(ctx, loadSocialProvider, arg.TenantID, arg.Provider)
	var i LoadSocialProviderRow
	err := row.Scan(
		&i.ClientID,
		&i.ClientSecret,
		&i.DiscoveryUrl,
		&i.Enabled,
	)
	return i, err
}

const markSocialLoginCodeUsed = `-- name: MarkSocialLoginCodeUsed :exec
UPDATE auth.social_login_codes SET used_at = NOW() WHERE code_hash = $1
`

func (q *Queries) MarkSocialLoginCodeUsed(ctx context.Context, codeHash string) error {
	_, err := q.db.Exec(ctx, markSocialLoginCodeUsed, codeHash)
	return err
}

const upsertSocialProvider = `-- name: UpsertSocialProvider :one

INSERT INTO tenant.social_providers (tenant_id, provider, client_id, client_secret, discovery_url)
VALUES ($1, $2, $3, $4, NULLIF($5,''))
ON CONFLICT (tenant_id, provider) DO UPDATE SET
    client_id     = EXCLUDED.client_id,
    client_secret = EXCLUDED.client_secret,
    discovery_url = EXCLUDED.discovery_url,
    enabled       = TRUE
RETURNING id, tenant_id, provider, client_id, discovery_url, enabled, created_at
`

type UpsertSocialProviderParams struct {
	TenantID     uuid.UUID
	Provider     string
	ClientID     string
	ClientSecret string
	DiscoveryUrl interface{}
}

type UpsertSocialProviderRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Provider     string
	ClientID     string
	DiscoveryUrl *string
	Enabled      bool
	CreatedAt    time.Time
}

// Queries for the social domain.
// All queries are STATIC and compiled by sqlc into ./dbgen.
func (q *Queries) UpsertSocialProvider(ctx context.Context, arg UpsertSocialProviderParams) (UpsertSocialProviderRow, error) {
	row := q.db.QueryRow(ctx, upsertSocialProvider,
		arg.TenantID,
		arg.Provider,
		arg.ClientID,
		arg.ClientSecret,
		arg.DiscoveryUrl,
	)
	var i UpsertSocialProviderRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.ClientID,
		&i.DiscoveryUrl,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}
