// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/google/uuid"
)

type AuthAbacPolicy struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Name         string
	Description  string
	Effect       string
	ResourceType string
	Action       string
	Condition    []byte
	Priority     int32
	Enabled      bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
