// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createAbacPolicy = `-- name: CreateAbacPolicy :one

INSERT INTO auth.abac_policies
    (tenant_id, name, description, effect, resource_type, action, condition, priority, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb, $8, $9)
RETURNING id, tenant_id, name, description, effect, resource_type, action, condition, priority, enabled, created_at, updated_at
`

type CreateAbacPolicyParams struct {
	TenantID     uuid.UUID
	Name         string
	Description  string
	Effect       string
	ResourceType string
	Action       string
	Condition    []byte
	Priority     int32
	Enabled      bool
}

// Queries for the abac (attribute-based access control) domain.
// Every statement here is a fixed-shape SQL: the condition tree is evaluated in
// Go (not in SQL), so both the CRUD statements and the Evaluate candidate load
// are static SELECTs/INSERT/UPDATE/DELETE and convert cleanly. Nothing in this
// module builds SQL dynamically.
func (q *Queries) CreateAbacPolicy(ctx context.Context, arg CreateAbacPolicyParams) (AuthAbacPolicy, error) {
	row := q.db.QueryRow(ctx, createAbacPolicy,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.Effect,
		arg.ResourceType,
		arg.Action,
		arg.Condition,
		arg.Priority,
		arg.Enabled,
	)
	var i AuthAbacPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Effect,
		&i.ResourceType,
		&i.Action,
		&i.Condition,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAbacPolicy = `-- name: DeleteAbacPolicy :one
DELETE FROM auth.abac_policies
WHERE id = $1 AND tenant_id = $2
RETURNING name
`

type DeleteAbacPolicyParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteAbacPolicy(ctx context.Context, arg DeleteAbacPolicyParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteAbacPolicy, arg.ID, arg.TenantID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getAbacPolicy = `-- name: GetAbacPolicy :one
SELECT id, tenant_id, name, description, effect, resource_type, action, condition, priority, enabled, created_at, updated_at
FROM auth.abac_policies
WHERE id = $1 AND tenant_id = $2
`

type GetAbacPolicyParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetAbacPolicy(ctx context.Context, arg GetAbacPolicyParams) (AuthAbacPolicy, error) {
	row := q.db.QueryRow(ctx, getAbacPolicy, arg.ID, arg.TenantID)
	var i AuthAbacPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Effect,
		&i.ResourceType,
		&i.Action,
		&i.Condition,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAbacPolicies = `-- name: ListAbacPolicies :many
SELECT id, tenant_id, name, description, effect, resource_type, action, condition, priority, enabled, created_at, updated_at
FROM auth.abac_policies
WHERE tenant_id = $1
ORDER BY priority DESC, name
`

func (q *Queries) ListAbacPolicies(ctx context.Context, tenantID uuid.UUID) ([]AuthAbacPolicy, error) {
	rows, err := q.db.Query(ctx, listAbacPolicies, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthAbacPolicy{}
	for rows.Next() {
		var i AuthAbacPolicy
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Effect,
			&i.ResourceType,
			&i.Action,
			&i.Condition,
			&i.Priority,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvaluationCandidates = `-- name: ListEvaluationCandidates :many
SELECT id, name, effect, condition, priority
FROM auth.abac_policies
WHERE tenant_id = $1
  AND enabled = true
  AND (resource_type = $2 OR resource_type = '*')
  AND (action = $3 OR action = '*')
ORDER BY priority DESC
`

type ListEvaluationCandidatesParams struct {
	TenantID     uuid.UUID
	ResourceType string
	Action       string
}

type ListEvaluationCandidatesRow struct {
	ID        uuid.UUID
	Name      string
	Effect    string
	Condition []byte
	Priority  int32
}

func (q *Queries) ListEvaluationCandidates(ctx context.Context, arg ListEvaluationCandidatesParams) ([]ListEvaluationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listEvaluationCandidates, arg.TenantID, arg.ResourceType, arg.Action)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEvaluationCandidatesRow{}
	for rows.Next() {
		var i ListEvaluationCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Effect,
			&i.Condition,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAbacPolicy = `-- name: UpdateAbacPolicy :one
UPDATE auth.abac_policies
SET name = $1, description = $2, effect = $3,
    resource_type = $4, action = $5, condition = $6::jsonb,
    priority = $7, enabled = $8, updated_at = now()
WHERE id = $9 AND tenant_id = $10
RETURNING id, tenant_id, name, description, effect, resource_type, action, condition, priority, enabled, created_at, updated_at
`

type UpdateAbacPolicyParams struct {
	Name         string
	Description  string
	Effect       string
	ResourceType string
	Action       string
	Condition    []byte
	Priority     int32
	Enabled      bool
	ID           uuid.UUID
	TenantID     uuid.UUID
}

func (q *Queries) UpdateAbacPolicy(ctx context.Context, arg UpdateAbacPolicyParams) (AuthAbacPolicy, error) {
	row := q.db.QueryRow(ctx, updateAbacPolicy,
		arg.Name,
		arg.Description,
		arg.Effect,
		arg.ResourceType,
		arg.Action,
		arg.Condition,
		arg.Priority,
		arg.Enabled,
		arg.ID,
		arg.TenantID,
	)
	var i AuthAbacPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Effect,
		&i.ResourceType,
		&i.Action,
		&i.Condition,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
