// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteLdapConnection = `-- name: DeleteLdapConnection :execrows
DELETE FROM tenant.ldap_connections WHERE id = $1 AND tenant_id = $2
`

type DeleteLdapConnectionParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteLdapConnection(ctx context.Context, arg DeleteLdapConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLdapConnection, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getExternalIdentityUser = `-- name: GetExternalIdentityUser :one
SELECT user_id FROM "user".external_identities
WHERE tenant_id = $1 AND provider = $2 AND subject = $3
`

type GetExternalIdentityUserParams struct {
	TenantID uuid.UUID
	Provider string
	Subject  string
}

func (q *Queries) GetExternalIdentityUser(ctx context.Context, arg GetExternalIdentityUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getExternalIdentityUser, arg.TenantID, arg.Provider, arg.Subject)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getLdapConnection = `-- name: GetLdapConnection :one
SELECT id, tenant_id, name, server_url, start_tls, skip_tls_verify, bind_dn,
       base_dn, user_filter, email_attribute, name_attribute, status,
       created_at, updated_at, last_login_at
FROM tenant.ldap_connections WHERE id = $1 AND tenant_id = $2
`

type GetLdapConnectionParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type GetLdapConnectionRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	Name           string
	ServerUrl      string
	StartTls       bool
	SkipTlsVerify  bool
	BindDn         string
	BaseDn         string
	UserFilter     string
	EmailAttribute string
	NameAttribute  string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LastLoginAt    pgtype.Timestamptz
}

func (q *Queries) GetLdapConnection(ctx context.Context, arg GetLdapConnectionParams) (GetLdapConnectionRow, error) {
	row := q.db.QueryRow(ctx, getLdapConnection, arg.ID, arg.TenantID)
	var i GetLdapConnectionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ServerUrl,
		&i.StartTls,
		&i.SkipTlsVerify,
		&i.BindDn,
		&i.BaseDn,
		&i.UserFilter,
		&i.EmailAttribute,
		&i.NameAttribute,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id FROM "user".users WHERE LOWER(email) = LOWER($1) AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertLdapConnection = `-- name: InsertLdapConnection :one

INSERT INTO tenant.ldap_connections
    (tenant_id, name, server_url, start_tls, skip_tls_verify, bind_dn, bind_password,
     base_dn, user_filter, email_attribute, name_attribute, status)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12)
RETURNING id, tenant_id, name, server_url, start_tls, skip_tls_verify, bind_dn,
          base_dn, user_filter, email_attribute, name_attribute, status,
          created_at, updated_at, last_login_at
`

type InsertLdapConnectionParams struct {
	TenantID       uuid.UUID
	Name           string
	ServerUrl      string
	StartTls       bool
	SkipTlsVerify  bool
	BindDn         string
	BindPassword   string
	BaseDn         string
	UserFilter     string
	EmailAttribute string
	NameAttribute  string
	Status         string
}

type InsertLdapConnectionRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	Name           string
	ServerUrl      string
	StartTls       bool
	SkipTlsVerify  bool
	BindDn         string
	BaseDn         string
	UserFilter     string
	EmailAttribute string
	NameAttribute  string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LastLoginAt    pgtype.Timestamptz
}

// Queries for the ldap domain.
// All queries below are STATIC and compiled by sqlc into ./dbgen.
// getFull (conditional WHERE tenant_id) stays hand-written in ldap.go.
func (q *Queries) InsertLdapConnection(ctx context.Context, arg InsertLdapConnectionParams) (InsertLdapConnectionRow, error) {
	row := q.db.QueryRow(ctx, insertLdapConnection,
		arg.TenantID,
		arg.Name,
		arg.ServerUrl,
		arg.StartTls,
		arg.SkipTlsVerify,
		arg.BindDn,
		arg.BindPassword,
		arg.BaseDn,
		arg.UserFilter,
		arg.EmailAttribute,
		arg.NameAttribute,
		arg.Status,
	)
	var i InsertLdapConnectionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ServerUrl,
		&i.StartTls,
		&i.SkipTlsVerify,
		&i.BindDn,
		&i.BaseDn,
		&i.UserFilter,
		&i.EmailAttribute,
		&i.NameAttribute,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const insertUserWithEmail = `-- name: InsertUserWithEmail :one
INSERT INTO "user".users (tenant_id, email, email_verified_at, display_name, status)
VALUES ($1, $2, NOW(), $3, 'active')
RETURNING id
`

type InsertUserWithEmailParams struct {
	TenantID    pgtype.UUID
	Email       string
	DisplayName *string
}

func (q *Queries) InsertUserWithEmail(ctx context.Context, arg InsertUserWithEmailParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertUserWithEmail, arg.TenantID, arg.Email, arg.DisplayName)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const linkExternalIdentity = `-- name: LinkExternalIdentity :exec
INSERT INTO "user".external_identities (user_id, tenant_id, provider, subject, email)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, provider, subject) DO NOTHING
`

type LinkExternalIdentityParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
	Provider string
	Subject  string
	Email    *string
}

func (q *Queries) LinkExternalIdentity(ctx context.Context, arg LinkExternalIdentityParams) error {
	_, err := q.db.Exec(ctx, linkExternalIdentity,
		arg.UserID,
		arg.TenantID,
		arg.Provider,
		arg.Subject,
		arg.Email,
	)
	return err
}

const listLdapConnections = `-- name: ListLdapConnections :many
SELECT id, tenant_id, name, server_url, start_tls, skip_tls_verify, bind_dn,
       base_dn, user_filter, email_attribute, name_attribute, status,
       created_at, updated_at, last_login_at
FROM tenant.ldap_connections WHERE tenant_id = $1 ORDER BY created_at DESC
`

type ListLdapConnectionsRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	Name           string
	ServerUrl      string
	StartTls       bool
	SkipTlsVerify  bool
	BindDn         string
	BaseDn         string
	UserFilter     string
	EmailAttribute string
	NameAttribute  string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LastLoginAt    pgtype.Timestamptz
}

func (q *Queries) ListLdapConnections(ctx context.Context, tenantID uuid.UUID) ([]ListLdapConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listLdapConnections, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLdapConnectionsRow{}
	for rows.Next() {
		var i ListLdapConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ServerUrl,
			&i.StartTls,
			&i.SkipTlsVerify,
			&i.BindDn,
			&i.BaseDn,
			&i.UserFilter,
			&i.EmailAttribute,
			&i.NameAttribute,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchLdapLastLogin = `-- name: TouchLdapLastLogin :exec
UPDATE tenant.ldap_connections SET last_login_at = NOW() WHERE id = $1
`

func (q *Queries) TouchLdapLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchLdapLastLogin, id)
	return err
}

const updateLdapConnection = `-- name: UpdateLdapConnection :one
UPDATE tenant.ldap_connections SET
    name            = COALESCE($1, name),
    server_url      = COALESCE($2, server_url),
    start_tls       = COALESCE($3, start_tls),
    skip_tls_verify = COALESCE($4, skip_tls_verify),
    bind_dn         = COALESCE($5, bind_dn),
    bind_password   = COALESCE($6, bind_password),
    base_dn         = COALESCE($7, base_dn),
    user_filter     = COALESCE($8, user_filter),
    email_attribute = COALESCE($9, email_attribute),
    name_attribute  = COALESCE($10, name_attribute),
    status          = COALESCE($11, status),
    updated_at      = NOW()
WHERE id = $12 AND tenant_id = $13
RETURNING id, tenant_id, name, server_url, start_tls, skip_tls_verify, bind_dn,
          base_dn, user_filter, email_attribute, name_attribute, status,
          created_at, updated_at, last_login_at
`

type UpdateLdapConnectionParams struct {
	Name           *string
	ServerUrl      *string
	StartTls       *bool
	SkipTlsVerify  *bool
	BindDn         *string
	BindPassword   *string
	BaseDn         *string
	UserFilter     *string
	EmailAttribute *string
	NameAttribute  *string
	Status         *string
	ID             uuid.UUID
	TenantID       uuid.UUID
}

type UpdateLdapConnectionRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	Name           string
	ServerUrl      string
	StartTls       bool
	SkipTlsVerify  bool
	BindDn         string
	BaseDn         string
	UserFilter     string
	EmailAttribute string
	NameAttribute  string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LastLoginAt    pgtype.Timestamptz
}

func (q *Queries) UpdateLdapConnection(ctx context.Context, arg UpdateLdapConnectionParams) (UpdateLdapConnectionRow, error) {
	row := q.db.QueryRow(ctx, updateLdapConnection,
		arg.Name,
		arg.ServerUrl,
		arg.StartTls,
		arg.SkipTlsVerify,
		arg.BindDn,
		arg.BindPassword,
		arg.BaseDn,
		arg.UserFilter,
		arg.EmailAttribute,
		arg.NameAttribute,
		arg.Status,
		arg.ID,
		arg.TenantID,
	)
	var i UpdateLdapConnectionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ServerUrl,
		&i.StartTls,
		&i.SkipTlsVerify,
		&i.BindDn,
		&i.BaseDn,
		&i.UserFilter,
		&i.EmailAttribute,
		&i.NameAttribute,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
