package audit

import (
	"context"
	"encoding/json"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	dbgen "github.com/qeetgroup/qeet-id-server/internal/operations/audit/dbgen"
)

// VerifyResult summarises a chain-verification pass for a single tenant.
type VerifyResult struct {
	OK             bool       `json:"ok"`
	RowsChecked    int        `json:"rows_checked"`
	LastVerifiedID *uuid.UUID `json:"last_verified_id,omitempty"`
	BrokenAtID     *uuid.UUID `json:"broken_at_id,omitempty"`
	BrokenReason   string     `json:"broken_reason,omitempty"`
}

type Verifier struct {
	pool *pgxpool.Pool
	q    *dbgen.Queries
}

func NewVerifier(pool *pgxpool.Pool) *Verifier {
	return &Verifier{pool: pool, q: dbgen.New(pool)}
}

// Verify walks the per-tenant hash chain in chronological order, recomputing
// each row's hash and comparing it against what is stored. Returns OK=false
// with BrokenAtID populated at the first row that fails validation.
//
// Pass tenantID=nil to verify the platform-level chain (rows with NULL
// tenant_id). Pre-migration rows (NULL hash columns) are skipped.
func (v *Verifier) Verify(ctx context.Context, tenantID *uuid.UUID) (VerifyResult, error) {
	rows, err := v.q.ListAuditEventsForVerify(ctx, pgUUIDNullable(tenantID))
	if err != nil {
		return VerifyResult{}, err
	}

	expectedPrev := chainSeed
	var (
		rowsChecked int
		lastID      *uuid.UUID
	)
	for _, row := range rows {
		tid := toUUIDPtr(row.TenantID)
		actor := toUUIDPtr(row.ActorUserID)
		resID := toUUIDPtr(row.ResourceID)

		// ip is COALESCE(host(ip), '') → interface{}; type-assert to string.
		ip, _ := row.Ip.(string)

		prevHashDB := ""
		if row.PrevHash != nil {
			prevHashDB = strings.TrimSpace(*row.PrevHash)
		}
		rowHashDB := ""
		if row.RowHash != nil {
			rowHashDB = strings.TrimSpace(*row.RowHash)
		}

		if prevHashDB != expectedPrev {
			brokenID := row.ID
			return VerifyResult{
				OK:             false,
				RowsChecked:    rowsChecked,
				LastVerifiedID: lastID,
				BrokenAtID:     &brokenID,
				BrokenReason:   "prev_hash does not match preceding row_hash",
			}, nil
		}

		metaJSON, err := normaliseMetadata(row.Metadata)
		if err != nil {
			return VerifyResult{}, err
		}
		canonical, err := canonicalize(Event{
			TenantID:     tid,
			ActorUserID:  actor,
			ActorType:    row.ActorType,
			Action:       row.Action,
			ResourceType: row.ResourceType,
			ResourceID:   resID,
			IP:           ip,
			UserAgent:    row.UserAgent, // already COALESCE'd to ""
			RequestID:    row.RequestID, // already COALESCE'd to ""
		}, row.ID, row.CreatedAt, metaJSON, prevHashDB)
		if err != nil {
			return VerifyResult{}, err
		}
		expectedRowHash := hashHex(canonical)
		if expectedRowHash != rowHashDB {
			brokenID := row.ID
			return VerifyResult{
				OK:             false,
				RowsChecked:    rowsChecked,
				LastVerifiedID: lastID,
				BrokenAtID:     &brokenID,
				BrokenReason:   "row_hash does not match recomputed hash",
			}, nil
		}

		expectedPrev = rowHashDB
		rowsChecked++
		idCopy := row.ID
		lastID = &idCopy
	}
	return VerifyResult{OK: true, RowsChecked: rowsChecked, LastVerifiedID: lastID}, nil
}

// toUUIDPtr converts a pgtype.UUID (generated by sqlc for nullable uuid
// columns) to a *uuid.UUID, returning nil for invalid (NULL) values.
func toUUIDPtr(u pgtype.UUID) *uuid.UUID {
	if !u.Valid {
		return nil
	}
	id := uuid.UUID(u.Bytes)
	return &id
}

// normaliseMetadata round-trips JSONB bytes through json.Unmarshal +
// json.Marshal so the canonical bytes match what Record produced at insert
// time, regardless of how Postgres formatted the JSONB on the way out.
func normaliseMetadata(raw []byte) ([]byte, error) {
	if len(raw) == 0 || string(raw) == "null" {
		return []byte("{}"), nil
	}
	var m map[string]any
	if err := json.Unmarshal(raw, &m); err != nil {
		return nil, err
	}
	if m == nil {
		return []byte("{}"), nil
	}
	return json.Marshal(m)
}

// Keep the time import alive — no other reference to the package remains.
var _ = time.Time{}
