// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookSubscription = `-- name: CreateWebhookSubscription :one

INSERT INTO tenant.webhook_subscriptions (tenant_id, url, secret, events)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, url, events, disabled_at, created_at
`

type CreateWebhookSubscriptionParams struct {
	TenantID uuid.UUID
	Url      string
	Secret   string
	Events   []string
}

type CreateWebhookSubscriptionRow struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Url        string
	Events     []string
	DisabledAt pgtype.Timestamptz
	CreatedAt  time.Time
}

// Queries for the webhooks domain.
// Create and Disable accept a pgx.Tx from the handler (audit sharing);
// they are called via q.WithTx(tx). Dispatcher (tick) queries are also
// static and included here.
func (q *Queries) CreateWebhookSubscription(ctx context.Context, arg CreateWebhookSubscriptionParams) (CreateWebhookSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, createWebhookSubscription,
		arg.TenantID,
		arg.Url,
		arg.Secret,
		arg.Events,
	)
	var i CreateWebhookSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Events,
		&i.DisabledAt,
		&i.CreatedAt,
	)
	return i, err
}

const deadLetterDelivery = `-- name: DeadLetterDelivery :exec
UPDATE tenant.webhook_deliveries
SET attempt = attempt + 1, status_code = $1, response_body = $2,
    error = $3, dead_at = NOW()
WHERE id = $4
`

type DeadLetterDeliveryParams struct {
	StatusCode   *int32
	ResponseBody *string
	Error        *string
	ID           uuid.UUID
}

func (q *Queries) DeadLetterDelivery(ctx context.Context, arg DeadLetterDeliveryParams) error {
	_, err := q.db.Exec(ctx, deadLetterDelivery,
		arg.StatusCode,
		arg.ResponseBody,
		arg.Error,
		arg.ID,
	)
	return err
}

const disableWebhookSubscription = `-- name: DisableWebhookSubscription :one
UPDATE tenant.webhook_subscriptions SET disabled_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND disabled_at IS NULL
RETURNING tenant_id, url
`

type DisableWebhookSubscriptionParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type DisableWebhookSubscriptionRow struct {
	TenantID uuid.UUID
	Url      string
}

// DisableWebhookSubscription marks the subscription disabled. RETURNING
// tenant_id and url for the audit row.
func (q *Queries) DisableWebhookSubscription(ctx context.Context, arg DisableWebhookSubscriptionParams) (DisableWebhookSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, disableWebhookSubscription, arg.ID, arg.TenantID)
	var i DisableWebhookSubscriptionRow
	err := row.Scan(&i.TenantID, &i.Url)
	return i, err
}

const getDueDeliveries = `-- name: GetDueDeliveries :many

SELECT d.id, d.subscription_id, d.event_type, d.payload, d.attempt, sub.url, sub.secret
FROM tenant.webhook_deliveries d
JOIN tenant.webhook_subscriptions sub ON sub.id = d.subscription_id
WHERE d.delivered_at IS NULL
  AND d.dead_at IS NULL
  AND d.next_attempt_at <= NOW()
  AND sub.disabled_at IS NULL
ORDER BY d.created_at
LIMIT 20
FOR UPDATE SKIP LOCKED
`

type GetDueDeliveriesRow struct {
	ID             uuid.UUID
	SubscriptionID uuid.UUID
	EventType      string
	Payload        []byte
	Attempt        int32
	Url            string
	Secret         string
}

// Dispatcher queries (tick): fetch due deliveries then update outcome.
func (q *Queries) GetDueDeliveries(ctx context.Context) ([]GetDueDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, getDueDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDueDeliveriesRow{}
	for rows.Next() {
		var i GetDueDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.EventType,
			&i.Payload,
			&i.Attempt,
			&i.Url,
			&i.Secret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionsForEvent = `-- name: GetSubscriptionsForEvent :many
SELECT id FROM tenant.webhook_subscriptions
WHERE tenant_id = $1 AND disabled_at IS NULL
  AND ($2::text = ANY(events) OR events = '{}'::text[])
`

type GetSubscriptionsForEventParams struct {
	TenantID  uuid.UUID
	EventType string
}

// GetSubscriptionsForEvent returns subscription IDs for Enqueue: active
// subscriptions matching the event type (or subscribed to all events).
func (q *Queries) GetSubscriptionsForEvent(ctx context.Context, arg GetSubscriptionsForEventParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getSubscriptionsForEvent, arg.TenantID, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebhookSubscription = `-- name: GetWebhookSubscription :one
SELECT id, tenant_id, url, events, disabled_at, created_at
FROM tenant.webhook_subscriptions WHERE id = $1 AND tenant_id = $2
`

type GetWebhookSubscriptionParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type GetWebhookSubscriptionRow struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Url        string
	Events     []string
	DisabledAt pgtype.Timestamptz
	CreatedAt  time.Time
}

func (q *Queries) GetWebhookSubscription(ctx context.Context, arg GetWebhookSubscriptionParams) (GetWebhookSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getWebhookSubscription, arg.ID, arg.TenantID)
	var i GetWebhookSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Events,
		&i.DisabledAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertDelivery = `-- name: InsertDelivery :exec
INSERT INTO tenant.webhook_deliveries (subscription_id, event_type, payload, next_attempt_at)
VALUES ($1, $2, $3, NOW())
`

type InsertDeliveryParams struct {
	SubscriptionID uuid.UUID
	EventType      string
	Payload        []byte
}

func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertDelivery, arg.SubscriptionID, arg.EventType, arg.Payload)
	return err
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT d.id, d.event_type, d.attempt, d.status_code, d.error,
       d.payload::text, d.response_body, d.delivered_at, d.next_attempt_at, d.dead_at, d.created_at
FROM tenant.webhook_deliveries d
JOIN tenant.webhook_subscriptions sub ON sub.id = d.subscription_id
WHERE d.subscription_id = $1 AND sub.tenant_id = $2
ORDER BY d.created_at DESC
LIMIT $3
`

type ListWebhookDeliveriesParams struct {
	SubscriptionID uuid.UUID
	TenantID       uuid.UUID
	RowLimit       int32
}

type ListWebhookDeliveriesRow struct {
	ID            uuid.UUID
	EventType     string
	Attempt       int32
	StatusCode    *int32
	Error         *string
	DPayload      string
	ResponseBody  *string
	DeliveredAt   pgtype.Timestamptz
	NextAttemptAt pgtype.Timestamptz
	DeadAt        pgtype.Timestamptz
	CreatedAt     time.Time
}

// ListWebhookDeliveries returns recent deliveries for a subscription, newest
// first. Tenant-scoped via the subscription join.
func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]ListWebhookDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries, arg.SubscriptionID, arg.TenantID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWebhookDeliveriesRow{}
	for rows.Next() {
		var i ListWebhookDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Attempt,
			&i.StatusCode,
			&i.Error,
			&i.DPayload,
			&i.ResponseBody,
			&i.DeliveredAt,
			&i.NextAttemptAt,
			&i.DeadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookSubscriptions = `-- name: ListWebhookSubscriptions :many
SELECT id, tenant_id, url, events, disabled_at, created_at
FROM tenant.webhook_subscriptions
WHERE tenant_id = $1 ORDER BY created_at DESC
`

type ListWebhookSubscriptionsRow struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Url        string
	Events     []string
	DisabledAt pgtype.Timestamptz
	CreatedAt  time.Time
}

func (q *Queries) ListWebhookSubscriptions(ctx context.Context, tenantID uuid.UUID) ([]ListWebhookSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listWebhookSubscriptions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWebhookSubscriptionsRow{}
	for rows.Next() {
		var i ListWebhookSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Url,
			&i.Events,
			&i.DisabledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeliverySucceeded = `-- name: MarkDeliverySucceeded :exec
UPDATE tenant.webhook_deliveries
SET delivered_at = NOW(), status_code = $1, response_body = $2,
    attempt = attempt + 1, error = NULL
WHERE id = $3
`

type MarkDeliverySucceededParams struct {
	StatusCode   *int32
	ResponseBody *string
	ID           uuid.UUID
}

func (q *Queries) MarkDeliverySucceeded(ctx context.Context, arg MarkDeliverySucceededParams) error {
	_, err := q.db.Exec(ctx, markDeliverySucceeded, arg.StatusCode, arg.ResponseBody, arg.ID)
	return err
}

const retryWebhookDelivery = `-- name: RetryWebhookDelivery :execrows
UPDATE tenant.webhook_deliveries d
SET delivered_at = NULL, dead_at = NULL, error = NULL, next_attempt_at = NOW()
FROM tenant.webhook_subscriptions sub
WHERE d.id = $1 AND d.subscription_id = sub.id AND sub.tenant_id = $2
`

type RetryWebhookDeliveryParams struct {
	DeliveryID uuid.UUID
	TenantID   uuid.UUID
}

func (q *Queries) RetryWebhookDelivery(ctx context.Context, arg RetryWebhookDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryWebhookDelivery, arg.DeliveryID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scheduleDeliveryRetry = `-- name: ScheduleDeliveryRetry :exec
UPDATE tenant.webhook_deliveries
SET attempt = attempt + 1,
    status_code = $1,
    response_body = $2,
    error = $3,
    next_attempt_at = $4
WHERE id = $5
`

type ScheduleDeliveryRetryParams struct {
	StatusCode    *int32
	ResponseBody  *string
	Error         *string
	NextAttemptAt pgtype.Timestamptz
	ID            uuid.UUID
}

func (q *Queries) ScheduleDeliveryRetry(ctx context.Context, arg ScheduleDeliveryRetryParams) error {
	_, err := q.db.Exec(ctx, scheduleDeliveryRetry,
		arg.StatusCode,
		arg.ResponseBody,
		arg.Error,
		arg.NextAttemptAt,
		arg.ID,
	)
	return err
}
