// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkEmailExistsForTenant = `-- name: CheckEmailExistsForTenant :one

SELECT EXISTS (
    SELECT 1 FROM "user".users
    WHERE LOWER(email) = LOWER($1) AND tenant_id = $2 AND deleted_at IS NULL
) OR EXISTS (
    SELECT 1 FROM auth.webauthn_sessions
    WHERE kind = 'signup' AND LOWER(pending_email) = LOWER($1)
      AND pending_tenant_id = $2 AND expires_at > now()
) AS exists
`

type CheckEmailExistsForTenantParams struct {
	Lower    string
	TenantID pgtype.UUID
}

// CheckEmailExistsForTenant checks if an email is taken for a specific tenant.
func (q *Queries) CheckEmailExistsForTenant(ctx context.Context, arg CheckEmailExistsForTenantParams) (*bool, error) {
	row := q.db.QueryRow(ctx, checkEmailExistsForTenant, arg.Lower, arg.TenantID)
	var exists *bool
	err := row.Scan(&exists)
	return exists, err
}

const checkEmailExistsNoTenant = `-- name: CheckEmailExistsNoTenant :one

SELECT EXISTS (
    SELECT 1 FROM "user".users
    WHERE LOWER(email) = LOWER($1) AND tenant_id IS NULL AND deleted_at IS NULL
) OR EXISTS (
    SELECT 1 FROM auth.webauthn_sessions
    WHERE kind = 'signup' AND LOWER(pending_email) = LOWER($1)
      AND pending_tenant_id IS NULL AND expires_at > now()
) AS exists
`

// CheckEmailExistsNoTenant checks if an email is taken by a real user or a pending
// signup session for the tenant-less flow.
func (q *Queries) CheckEmailExistsNoTenant(ctx context.Context, lower string) (*bool, error) {
	row := q.db.QueryRow(ctx, checkEmailExistsNoTenant, lower)
	var exists *bool
	err := row.Scan(&exists)
	return exists, err
}

const deletePasskeyCredential = `-- name: DeletePasskeyCredential :execrows
DELETE FROM auth.passkey_credentials WHERE id = $1 AND user_id = $2
`

type DeletePasskeyCredentialParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeletePasskeyCredential(ctx context.Context, arg DeletePasskeyCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePasskeyCredential, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPasskeyCredentialsForCeremony = `-- name: GetPasskeyCredentialsForCeremony :many
SELECT credential_id, public_key, sign_count, aaguid, transports
FROM auth.passkey_credentials WHERE user_id = $1
`

type GetPasskeyCredentialsForCeremonyRow struct {
	CredentialID []byte
	PublicKey    []byte
	SignCount    int64
	Aaguid       pgtype.UUID
	Transports   []string
}

func (q *Queries) GetPasskeyCredentialsForCeremony(ctx context.Context, userID uuid.UUID) ([]GetPasskeyCredentialsForCeremonyRow, error) {
	rows, err := q.db.Query(ctx, getPasskeyCredentialsForCeremony, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPasskeyCredentialsForCeremonyRow{}
	for rows.Next() {
		var i GetPasskeyCredentialsForCeremonyRow
		if err := rows.Scan(
			&i.CredentialID,
			&i.PublicKey,
			&i.SignCount,
			&i.Aaguid,
			&i.Transports,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserForWebAuthn = `-- name: GetUserForWebAuthn :one
SELECT email, display_name, tenant_id FROM "user".users
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserForWebAuthnRow struct {
	Email       string
	DisplayName *string
	TenantID    pgtype.UUID
}

func (q *Queries) GetUserForWebAuthn(ctx context.Context, id uuid.UUID) (GetUserForWebAuthnRow, error) {
	row := q.db.QueryRow(ctx, getUserForWebAuthn, id)
	var i GetUserForWebAuthnRow
	err := row.Scan(&i.Email, &i.DisplayName, &i.TenantID)
	return i, err
}

const getUserIDByEmail = `-- name: GetUserIDByEmail :one
SELECT id FROM "user".users
WHERE LOWER(email) = LOWER($1) AND deleted_at IS NULL
`

func (q *Queries) GetUserIDByEmail(ctx context.Context, lower string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByEmail, lower)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertPasskeyCredential = `-- name: InsertPasskeyCredential :exec
INSERT INTO auth.passkey_credentials (user_id, credential_id, public_key, sign_count, aaguid, transports, name)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertPasskeyCredentialParams struct {
	UserID       uuid.UUID
	CredentialID []byte
	PublicKey    []byte
	SignCount    int64
	Aaguid       pgtype.UUID
	Transports   []string
	Name         *string
}

func (q *Queries) InsertPasskeyCredential(ctx context.Context, arg InsertPasskeyCredentialParams) error {
	_, err := q.db.Exec(ctx, insertPasskeyCredential,
		arg.UserID,
		arg.CredentialID,
		arg.PublicKey,
		arg.SignCount,
		arg.Aaguid,
		arg.Transports,
		arg.Name,
	)
	return err
}

const insertSignupWebAuthnSession = `-- name: InsertSignupWebAuthnSession :one
INSERT INTO auth.webauthn_sessions (kind, data, expires_at, subject_id, pending_email, pending_display_name, pending_tenant_id)
VALUES ('signup', $1, $2, $3, $4, $5, $6) RETURNING id
`

type InsertSignupWebAuthnSessionParams struct {
	Data               []byte
	ExpiresAt          time.Time
	SubjectID          pgtype.UUID
	PendingEmail       *string
	PendingDisplayName *string
	PendingTenantID    pgtype.UUID
}

func (q *Queries) InsertSignupWebAuthnSession(ctx context.Context, arg InsertSignupWebAuthnSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertSignupWebAuthnSession,
		arg.Data,
		arg.ExpiresAt,
		arg.SubjectID,
		arg.PendingEmail,
		arg.PendingDisplayName,
		arg.PendingTenantID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertUserFromSignup = `-- name: InsertUserFromSignup :one
INSERT INTO "user".users (tenant_id, email, display_name)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertUserFromSignupParams struct {
	TenantID    pgtype.UUID
	Email       string
	DisplayName *string
}

func (q *Queries) InsertUserFromSignup(ctx context.Context, arg InsertUserFromSignupParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertUserFromSignup, arg.TenantID, arg.Email, arg.DisplayName)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertWebAuthnSession = `-- name: InsertWebAuthnSession :one
INSERT INTO auth.webauthn_sessions (user_id, kind, data, expires_at)
VALUES ($1, $2, $3, $4) RETURNING id
`

type InsertWebAuthnSessionParams struct {
	UserID    pgtype.UUID
	Kind      string
	Data      []byte
	ExpiresAt time.Time
}

func (q *Queries) InsertWebAuthnSession(ctx context.Context, arg InsertWebAuthnSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertWebAuthnSession,
		arg.UserID,
		arg.Kind,
		arg.Data,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listPasskeyCredentials = `-- name: ListPasskeyCredentials :many

SELECT id, user_id, name, transports, last_used_at, created_at
FROM auth.passkey_credentials WHERE user_id = $1 ORDER BY created_at DESC
`

type ListPasskeyCredentialsRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       *string
	Transports []string
	LastUsedAt pgtype.Timestamptz
	CreatedAt  time.Time
}

// Queries for the access/passkeys domain.
// All queries are static and compiled by sqlc into ./dbgen.
func (q *Queries) ListPasskeyCredentials(ctx context.Context, userID uuid.UUID) ([]ListPasskeyCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listPasskeyCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPasskeyCredentialsRow{}
	for rows.Next() {
		var i ListPasskeyCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Transports,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const takeSignupWebAuthnSession = `-- name: TakeSignupWebAuthnSession :one

DELETE FROM auth.webauthn_sessions WHERE id = $1
RETURNING kind, data, expires_at, subject_id, pending_email, pending_display_name, pending_tenant_id
`

type TakeSignupWebAuthnSessionRow struct {
	Kind               string
	Data               []byte
	ExpiresAt          time.Time
	SubjectID          pgtype.UUID
	PendingEmail       *string
	PendingDisplayName *string
	PendingTenantID    pgtype.UUID
}

// TakeSignupWebAuthnSession atomically removes a signup session and returns its data.
func (q *Queries) TakeSignupWebAuthnSession(ctx context.Context, id uuid.UUID) (TakeSignupWebAuthnSessionRow, error) {
	row := q.db.QueryRow(ctx, takeSignupWebAuthnSession, id)
	var i TakeSignupWebAuthnSessionRow
	err := row.Scan(
		&i.Kind,
		&i.Data,
		&i.ExpiresAt,
		&i.SubjectID,
		&i.PendingEmail,
		&i.PendingDisplayName,
		&i.PendingTenantID,
	)
	return i, err
}

const takeWebAuthnSession = `-- name: TakeWebAuthnSession :one

DELETE FROM auth.webauthn_sessions WHERE id = $1
RETURNING kind, user_id, data, expires_at
`

type TakeWebAuthnSessionRow struct {
	Kind      string
	UserID    pgtype.UUID
	Data      []byte
	ExpiresAt time.Time
}

// TakeWebAuthnSession atomically removes a session and returns its data (single-use).
func (q *Queries) TakeWebAuthnSession(ctx context.Context, id uuid.UUID) (TakeWebAuthnSessionRow, error) {
	row := q.db.QueryRow(ctx, takeWebAuthnSession, id)
	var i TakeWebAuthnSessionRow
	err := row.Scan(
		&i.Kind,
		&i.UserID,
		&i.Data,
		&i.ExpiresAt,
	)
	return i, err
}

const updatePasskeySignCount = `-- name: UpdatePasskeySignCount :exec
UPDATE auth.passkey_credentials SET sign_count = $1, last_used_at = NOW()
WHERE credential_id = $2
`

type UpdatePasskeySignCountParams struct {
	SignCount    int64
	CredentialID []byte
}

func (q *Queries) UpdatePasskeySignCount(ctx context.Context, arg UpdatePasskeySignCountParams) error {
	_, err := q.db.Exec(ctx, updatePasskeySignCount, arg.SignCount, arg.CredentialID)
	return err
}
