DROP SCHEMA IF EXISTS audit CASCADE;
DROP SCHEMA IF EXISTS rbac CASCADE;
DROP SCHEMA IF EXISTS auth CASCADE;
DROP SCHEMA IF EXISTS "user" CASCADE;
DROP SCHEMA IF EXISTS tenant CASCADE;
DROP SCHEMA IF EXISTS platform CASCADE;
