// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelSubscription = `-- name: CancelSubscription :execrows
UPDATE tenant.subscriptions
SET cancel_at_period_end = TRUE, updated_at = NOW()
WHERE tenant_id = $1
`

// Mark the subscription to cancel at end of current period.  Returns 0 rows
// affected when no active subscription exists.
func (q *Queries) CancelSubscription(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelSubscription, tenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeCheckout = `-- name: CompleteCheckout :one
UPDATE tenant.billing_checkouts
SET status = 'completed', completed_at = NOW()
WHERE id = $1 AND status = 'pending'
RETURNING tenant_id, plan_code, currency
`

type CompleteCheckoutRow struct {
	TenantID uuid.UUID
	PlanCode string
	Currency string
}

// Atomically flip a pending checkout to completed and return the plan details
// needed to activate the subscription.  Returns ErrNoRows when the checkout is
// already completed, failed, or unknown — callers treat that as an idempotent no-op.
func (q *Queries) CompleteCheckout(ctx context.Context, id uuid.UUID) (CompleteCheckoutRow, error) {
	row := q.db.QueryRow(ctx, completeCheckout, id)
	var i CompleteCheckoutRow
	err := row.Scan(&i.TenantID, &i.PlanCode, &i.Currency)
	return i, err
}

const getBillingPlanByCode = `-- name: GetBillingPlanByCode :one
SELECT id, interval, name
FROM platform.billing_plans
WHERE code = $1 AND active = TRUE
`

type GetBillingPlanByCodeRow struct {
	ID       uuid.UUID
	Interval string
	Name     string
}

// Look up a plan by its code for subscription/checkout flows.
func (q *Queries) GetBillingPlanByCode(ctx context.Context, code string) (GetBillingPlanByCodeRow, error) {
	row := q.db.QueryRow(ctx, getBillingPlanByCode, code)
	var i GetBillingPlanByCodeRow
	err := row.Scan(&i.ID, &i.Interval, &i.Name)
	return i, err
}

const getBillingPlanPrice = `-- name: GetBillingPlanPrice :one
SELECT amount_minor
FROM platform.billing_plan_prices
WHERE plan_id = $1 AND currency = $2
`

type GetBillingPlanPriceParams struct {
	PlanID   uuid.UUID
	Currency string
}

// Check whether a plan is priced in a given currency and fetch the amount.
func (q *Queries) GetBillingPlanPrice(ctx context.Context, arg GetBillingPlanPriceParams) (int64, error) {
	row := q.db.QueryRow(ctx, getBillingPlanPrice, arg.PlanID, arg.Currency)
	var amount_minor int64
	err := row.Scan(&amount_minor)
	return amount_minor, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT p.code, p.name, p.interval, s.currency, s.status,
       s.current_period_start, s.current_period_end, s.cancel_at_period_end,
       COALESCE(pp.amount_minor, 0) AS amount_minor
FROM tenant.subscriptions s
JOIN platform.billing_plans p ON p.id = s.plan_id
LEFT JOIN platform.billing_plan_prices pp
    ON pp.plan_id = s.plan_id AND pp.currency = s.currency
WHERE s.tenant_id = $1
`

type GetSubscriptionRow struct {
	Code               string
	Name               string
	Interval           string
	Currency           string
	Status             string
	CurrentPeriodStart time.Time
	CurrentPeriodEnd   time.Time
	CancelAtPeriodEnd  bool
	AmountMinor        int64
}

// Fetch the current subscription for a tenant, joining plan metadata and the
// currency-specific price in one round-trip.
func (q *Queries) GetSubscription(ctx context.Context, tenantID uuid.UUID) (GetSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getSubscription, tenantID)
	var i GetSubscriptionRow
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Interval,
		&i.Currency,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.AmountMinor,
	)
	return i, err
}

const insertBillingCheckout = `-- name: InsertBillingCheckout :one
INSERT INTO tenant.billing_checkouts
    (tenant_id, provider, plan_code, currency, amount_minor)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertBillingCheckoutParams struct {
	TenantID    uuid.UUID
	Provider    string
	PlanCode    string
	Currency    string
	AmountMinor int64
}

// Create a pending card-payment checkout row and return its id, which is
// passed to the provider as client_reference_id for webhook correlation.
func (q *Queries) InsertBillingCheckout(ctx context.Context, arg InsertBillingCheckoutParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertBillingCheckout,
		arg.TenantID,
		arg.Provider,
		arg.PlanCode,
		arg.Currency,
		arg.AmountMinor,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertInvoice = `-- name: InsertInvoice :exec
INSERT INTO tenant.invoices
    (tenant_id, plan_code, currency, amount_minor, status, period_start, period_end)
VALUES ($1, $2, $3, $4, 'paid', $5, $6)
`

type InsertInvoiceParams struct {
	TenantID    uuid.UUID
	PlanCode    string
	Currency    string
	AmountMinor int64
	PeriodStart time.Time
	PeriodEnd   time.Time
}

// Issue an invoice for one billing period (zero-amount plans still get a record).
func (q *Queries) InsertInvoice(ctx context.Context, arg InsertInvoiceParams) error {
	_, err := q.db.Exec(ctx, insertInvoice,
		arg.TenantID,
		arg.PlanCode,
		arg.Currency,
		arg.AmountMinor,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	return err
}

const listBillingPlanPrices = `-- name: ListBillingPlanPrices :many
SELECT plan_id, currency, amount_minor
FROM platform.billing_plan_prices
`

// Fetch all plan prices (joined in Go to populate Plan.Prices map).
func (q *Queries) ListBillingPlanPrices(ctx context.Context) ([]PlatformBillingPlanPrice, error) {
	rows, err := q.db.Query(ctx, listBillingPlanPrices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformBillingPlanPrice{}
	for rows.Next() {
		var i PlatformBillingPlanPrice
		if err := rows.Scan(&i.PlanID, &i.Currency, &i.AmountMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingPlans = `-- name: ListBillingPlans :many

SELECT id, code, name, description, interval, features
FROM platform.billing_plans
WHERE active = TRUE
ORDER BY sort, name
`

type ListBillingPlansRow struct {
	ID          uuid.UUID
	Code        string
	Name        string
	Description string
	Interval    string
	Features    []byte
}

// Queries for the billing domain.
// All SQL here is static; there are no dynamic WHERE/SET clauses.
// Return all active plans in display order (for the public /billing/plans endpoint).
func (q *Queries) ListBillingPlans(ctx context.Context) ([]ListBillingPlansRow, error) {
	rows, err := q.db.Query(ctx, listBillingPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBillingPlansRow{}
	for rows.Next() {
		var i ListBillingPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Interval,
			&i.Features,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, plan_code, currency, amount_minor, status, period_start, period_end, issued_at
FROM tenant.invoices
WHERE tenant_id = $1
ORDER BY issued_at DESC
LIMIT 100
`

type ListInvoicesRow struct {
	ID          uuid.UUID
	PlanCode    string
	Currency    string
	AmountMinor int64
	Status      string
	PeriodStart time.Time
	PeriodEnd   time.Time
	IssuedAt    time.Time
}

// Return the tenant's billing history, most recent first.
func (q *Queries) ListInvoices(ctx context.Context, tenantID uuid.UUID) ([]ListInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listInvoices, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoicesRow{}
	for rows.Next() {
		var i ListInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.PlanCode,
			&i.Currency,
			&i.AmountMinor,
			&i.Status,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.IssuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCheckoutFailed = `-- name: UpdateCheckoutFailed :exec
UPDATE tenant.billing_checkouts
SET status = 'failed'
WHERE id = $1
`

// Mark a checkout as failed when the provider call itself errors out.
func (q *Queries) UpdateCheckoutFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateCheckoutFailed, id)
	return err
}

const updateCheckoutProviderRef = `-- name: UpdateCheckoutProviderRef :exec
UPDATE tenant.billing_checkouts
SET provider_ref = $1
WHERE id = $2
`

type UpdateCheckoutProviderRefParams struct {
	ProviderRef string
	ID          uuid.UUID
}

// Store the provider's own checkout reference after a successful CreateCheckout call.
func (q *Queries) UpdateCheckoutProviderRef(ctx context.Context, arg UpdateCheckoutProviderRefParams) error {
	_, err := q.db.Exec(ctx, updateCheckoutProviderRef, arg.ProviderRef, arg.ID)
	return err
}

const upsertBillingPlan = `-- name: UpsertBillingPlan :one
INSERT INTO platform.billing_plans
    (code, name, description, interval, features, sort)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (code) DO UPDATE SET
    name        = EXCLUDED.name,
    description = EXCLUDED.description,
    interval    = EXCLUDED.interval,
    features    = EXCLUDED.features,
    sort        = EXCLUDED.sort
RETURNING id
`

type UpsertBillingPlanParams struct {
	Code        string
	Name        string
	Description string
	Interval    string
	Features    []byte
	Sort        int32
}

// Idempotent seed upsert for the built-in plan catalogue.
func (q *Queries) UpsertBillingPlan(ctx context.Context, arg UpsertBillingPlanParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertBillingPlan,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Interval,
		arg.Features,
		arg.Sort,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertBillingPlanPrice = `-- name: UpsertBillingPlanPrice :exec
INSERT INTO platform.billing_plan_prices (plan_id, currency, amount_minor)
VALUES ($1, $2, $3)
ON CONFLICT (plan_id, currency) DO UPDATE SET
    amount_minor = EXCLUDED.amount_minor
`

type UpsertBillingPlanPriceParams struct {
	PlanID      uuid.UUID
	Currency    string
	AmountMinor int64
}

// Idempotent seed upsert for per-currency plan pricing.
func (q *Queries) UpsertBillingPlanPrice(ctx context.Context, arg UpsertBillingPlanPriceParams) error {
	_, err := q.db.Exec(ctx, upsertBillingPlanPrice, arg.PlanID, arg.Currency, arg.AmountMinor)
	return err
}

const upsertSubscription = `-- name: UpsertSubscription :exec
INSERT INTO tenant.subscriptions
    (tenant_id, plan_id, currency, status,
     current_period_start, current_period_end, cancel_at_period_end, updated_at)
VALUES ($1, $2, $3, 'active', $4, $5, FALSE, NOW())
ON CONFLICT (tenant_id) DO UPDATE SET
    plan_id              = EXCLUDED.plan_id,
    currency             = EXCLUDED.currency,
    status               = 'active',
    current_period_start = EXCLUDED.current_period_start,
    current_period_end   = EXCLUDED.current_period_end,
    cancel_at_period_end = FALSE,
    updated_at           = NOW()
`

type UpsertSubscriptionParams struct {
	TenantID    uuid.UUID
	PlanID      uuid.UUID
	Currency    string
	PeriodStart time.Time
	PeriodEnd   time.Time
}

// Create or replace the tenant's subscription (one row per tenant).
func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertSubscription,
		arg.TenantID,
		arg.PlanID,
		arg.Currency,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	return err
}
