/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AccountSessionsRouteImport } from './routes/account/sessions'
import { Route as AccountSecurityRouteImport } from './routes/account/security'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountDataRouteImport } from './routes/account/data'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthMagicRouteImport } from './routes/_auth/magic'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppInvitationsRouteImport } from './routes/_app/invitations'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users/index'
import { Route as AppSecurityIndexRouteImport } from './routes/_app/security/index'
import { Route as AppGroupsIndexRouteImport } from './routes/_app/groups/index'
import { Route as AppAuthorizationIndexRouteImport } from './routes/_app/authorization/index'
import { Route as AuthSsoCallbackRouteImport } from './routes/_auth/sso.callback'
import { Route as AuthInviteAcceptRouteImport } from './routes/_auth/invite.accept'
import { Route as AppUsersSessionsRouteImport } from './routes/_app/users/sessions'
import { Route as AppUsersInvitationsRouteImport } from './routes/_app/users/invitations'
import { Route as AppUsersImportRouteImport } from './routes/_app/users/import'
import { Route as AppUsersDeletedRouteImport } from './routes/_app/users/deleted'
import { Route as AppUsersUserIdRouteImport } from './routes/_app/users/$userId'
import { Route as AppSettingsBrandingRouteImport } from './routes/_app/settings/branding'
import { Route as AppSettingsBillingRouteImport } from './routes/_app/settings/billing'
import { Route as AppSecuritySessionsRouteImport } from './routes/_app/security/sessions'
import { Route as AppSecurityRateLimitsRouteImport } from './routes/_app/security/rate-limits'
import { Route as AppSecurityLogStreamingRouteImport } from './routes/_app/security/log-streaming'
import { Route as AppSecurityDeviceAuthorizationsRouteImport } from './routes/_app/security/device-authorizations'
import { Route as AppSecurityAuditLogsRouteImport } from './routes/_app/security/audit-logs'
import { Route as AppSecurityAuditIntelligenceRouteImport } from './routes/_app/security/audit-intelligence'
import { Route as AppOrganizationsTenantsRouteImport } from './routes/_app/organizations/tenants'
import { Route as AppOrganizationsMembersRouteImport } from './routes/_app/organizations/members'
import { Route as AppOrganizationsDomainsRouteImport } from './routes/_app/organizations/domains'
import { Route as AppGroupsGroupIdRouteImport } from './routes/_app/groups/$groupId'
import { Route as AppDeveloperInfrastructureRouteImport } from './routes/_app/developer/infrastructure'
import { Route as AppDeveloperCredentialsRouteImport } from './routes/_app/developer/credentials'
import { Route as AppDeveloperBotsRouteImport } from './routes/_app/developer/bots'
import { Route as AppDeveloperAuthHooksRouteImport } from './routes/_app/developer/auth-hooks'
import { Route as AppDeveloperAgentsRouteImport } from './routes/_app/developer/agents'
import { Route as AppAuthorizationVersionsRouteImport } from './routes/_app/authorization/versions'
import { Route as AppAuthorizationTemplatesRouteImport } from './routes/_app/authorization/templates'
import { Route as AppAuthorizationSimulatorRouteImport } from './routes/_app/authorization/simulator'
import { Route as AppAuthorizationSettingsRouteImport } from './routes/_app/authorization/settings'
import { Route as AppAuthorizationRolesRouteImport } from './routes/_app/authorization/roles'
import { Route as AppAuthorizationResourcesRouteImport } from './routes/_app/authorization/resources'
import { Route as AppAuthorizationRebacRouteImport } from './routes/_app/authorization/rebac'
import { Route as AppAuthorizationRbacRouteImport } from './routes/_app/authorization/rbac'
import { Route as AppAuthorizationPermissionsRouteImport } from './routes/_app/authorization/permissions'
import { Route as AppAuthorizationExplorerRouteImport } from './routes/_app/authorization/explorer'
import { Route as AppAuthorizationBuilderRouteImport } from './routes/_app/authorization/builder'
import { Route as AppAuthorizationAuditRouteImport } from './routes/_app/authorization/audit'
import { Route as AppAuthorizationAssistantRouteImport } from './routes/_app/authorization/assistant'
import { Route as AppAuthorizationAccessTesterRouteImport } from './routes/_app/authorization/access-tester'
import { Route as AppAuthorizationAbacRouteImport } from './routes/_app/authorization/abac'
import { Route as AppAuthSocialRouteImport } from './routes/_app/auth/social'
import { Route as AppDeveloperWebhooksIndexRouteImport } from './routes/_app/developer/webhooks/index'
import { Route as AppAuthConnectionsIndexRouteImport } from './routes/_app/auth/connections/index'
import { Route as AppUsersUserIdTimelineRouteImport } from './routes/_app/users/$userId_.timeline'
import { Route as AppSettingsWorkspaceSecurityPolicyRouteImport } from './routes/_app/settings/workspace/security-policy'
import { Route as AppSettingsWorkspaceGeneralRouteImport } from './routes/_app/settings/workspace/general'
import { Route as AppSettingsWorkspaceEmailTemplatesRouteImport } from './routes/_app/settings/workspace/email-templates'
import { Route as AppSettingsWorkspaceDomainsRouteImport } from './routes/_app/settings/workspace/domains'
import { Route as AppSecurityThreatsRiskSettingsRouteImport } from './routes/_app/security/threats/risk-settings'
import { Route as AppSecurityThreatsRateLimitsRouteImport } from './routes/_app/security/threats/rate-limits'
import { Route as AppSecurityThreatsIpAllowlistRouteImport } from './routes/_app/security/threats/ip-allowlist'
import { Route as AppSecurityThreatsBotsRouteImport } from './routes/_app/security/threats/bots'
import { Route as AppSecurityThreatsAnomaliesRouteImport } from './routes/_app/security/threats/anomalies'
import { Route as AppSecurityComplianceSoc2RouteImport } from './routes/_app/security/compliance/soc2'
import { Route as AppSecurityComplianceRetentionRouteImport } from './routes/_app/security/compliance/retention'
import { Route as AppSecurityComplianceIso27001RouteImport } from './routes/_app/security/compliance/iso27001'
import { Route as AppSecurityComplianceGdprRouteImport } from './routes/_app/security/compliance/gdpr'
import { Route as AppDeveloperWebhooksIdRouteImport } from './routes/_app/developer/webhooks/$id'
import { Route as AppAuthMfaTotpRouteImport } from './routes/_app/auth/mfa/totp'
import { Route as AppAuthMfaSmsEmailRouteImport } from './routes/_app/auth/mfa/sms-email'
import { Route as AppAuthMfaRecoveryCodesRouteImport } from './routes/_app/auth/mfa/recovery-codes'
import { Route as AppAuthLoginMethodsPasswordlessRouteImport } from './routes/_app/auth/login-methods/passwordless'
import { Route as AppAuthLoginMethodsPasswordRouteImport } from './routes/_app/auth/login-methods/password'
import { Route as AppAuthLoginMethodsPasskeysRouteImport } from './routes/_app/auth/login-methods/passkeys'
import { Route as AppAuthLoginMethodsMagicLinksRouteImport } from './routes/_app/auth/login-methods/magic-links'
import { Route as AppAuthConnectionsScimRouteImport } from './routes/_app/auth/connections/scim'
import { Route as AppAuthConnectionsSamlIdpRouteImport } from './routes/_app/auth/connections/saml-idp'
import { Route as AppAuthConnectionsSamlRouteImport } from './routes/_app/auth/connections/saml'
import { Route as AppAuthConnectionsLdapRouteImport } from './routes/_app/auth/connections/ldap'
import { Route as AppAuthApiTokensRouteImport } from './routes/_app/auth/api/tokens'
import { Route as AppAuthApiSigningKeysRouteImport } from './routes/_app/auth/api/signing-keys'
import { Route as AppAuthApiSecretsRouteImport } from './routes/_app/auth/api/secrets'
import { Route as AppAuthApiMachineIdentitiesRouteImport } from './routes/_app/auth/api/machine-identities'
import { Route as AppAuthApiKeysRouteImport } from './routes/_app/auth/api/keys'
import { Route as AppAuthApiConsentGrantsRouteImport } from './routes/_app/auth/api/consent-grants'
import { Route as AppAuthConnectionsOidcIndexRouteImport } from './routes/_app/auth/connections/oidc/index'
import { Route as AppAuthConnectionsOidcClientIdRouteImport } from './routes/_app/auth/connections/oidc/$clientId'

const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AccountSessionsRoute = AccountSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountDataRoute = AccountDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AccountRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMagicRoute = AuthMagicRouteImport.update({
  id: '/magic',
  path: '/magic',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppInvitationsRoute = AppInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityIndexRoute = AppSecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthorizationIndexRoute = AppAuthorizationIndexRouteImport.update({
  id: '/authorization/',
  path: '/authorization/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSsoCallbackRoute = AuthSsoCallbackRouteImport.update({
  id: '/sso/callback',
  path: '/sso/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInviteAcceptRoute = AuthInviteAcceptRouteImport.update({
  id: '/invite/accept',
  path: '/invite/accept',
  getParentRoute: () => AuthRoute,
} as any)
const AppUsersSessionsRoute = AppUsersSessionsRouteImport.update({
  id: '/users/sessions',
  path: '/users/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersInvitationsRoute = AppUsersInvitationsRouteImport.update({
  id: '/users/invitations',
  path: '/users/invitations',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersImportRoute = AppUsersImportRouteImport.update({
  id: '/users/import',
  path: '/users/import',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersDeletedRoute = AppUsersDeletedRouteImport.update({
  id: '/users/deleted',
  path: '/users/deleted',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsBrandingRoute = AppSettingsBrandingRouteImport.update({
  id: '/settings/branding',
  path: '/settings/branding',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppSecuritySessionsRoute = AppSecuritySessionsRouteImport.update({
  id: '/security/sessions',
  path: '/security/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRateLimitsRoute = AppSecurityRateLimitsRouteImport.update({
  id: '/security/rate-limits',
  path: '/security/rate-limits',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityLogStreamingRoute = AppSecurityLogStreamingRouteImport.update({
  id: '/security/log-streaming',
  path: '/security/log-streaming',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityDeviceAuthorizationsRoute =
  AppSecurityDeviceAuthorizationsRouteImport.update({
    id: '/security/device-authorizations',
    path: '/security/device-authorizations',
    getParentRoute: () => AppRoute,
  } as any)
const AppSecurityAuditLogsRoute = AppSecurityAuditLogsRouteImport.update({
  id: '/security/audit-logs',
  path: '/security/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityAuditIntelligenceRoute =
  AppSecurityAuditIntelligenceRouteImport.update({
    id: '/security/audit-intelligence',
    path: '/security/audit-intelligence',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationsTenantsRoute = AppOrganizationsTenantsRouteImport.update({
  id: '/organizations/tenants',
  path: '/organizations/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsMembersRoute = AppOrganizationsMembersRouteImport.update({
  id: '/organizations/members',
  path: '/organizations/members',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsDomainsRoute = AppOrganizationsDomainsRouteImport.update({
  id: '/organizations/domains',
  path: '/organizations/domains',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsGroupIdRoute = AppGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => AppRoute,
} as any)
const AppDeveloperInfrastructureRoute =
  AppDeveloperInfrastructureRouteImport.update({
    id: '/developer/infrastructure',
    path: '/developer/infrastructure',
    getParentRoute: () => AppRoute,
  } as any)
const AppDeveloperCredentialsRoute = AppDeveloperCredentialsRouteImport.update({
  id: '/developer/credentials',
  path: '/developer/credentials',
  getParentRoute: () => AppRoute,
} as any)
const AppDeveloperBotsRoute = AppDeveloperBotsRouteImport.update({
  id: '/developer/bots',
  path: '/developer/bots',
  getParentRoute: () => AppRoute,
} as any)
const AppDeveloperAuthHooksRoute = AppDeveloperAuthHooksRouteImport.update({
  id: '/developer/auth-hooks',
  path: '/developer/auth-hooks',
  getParentRoute: () => AppRoute,
} as any)
const AppDeveloperAgentsRoute = AppDeveloperAgentsRouteImport.update({
  id: '/developer/agents',
  path: '/developer/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthorizationVersionsRoute =
  AppAuthorizationVersionsRouteImport.update({
    id: '/authorization/versions',
    path: '/authorization/versions',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthorizationTemplatesRoute =
  AppAuthorizationTemplatesRouteImport.update({
    id: '/authorization/templates',
    path: '/authorization/templates',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthorizationSimulatorRoute =
  AppAuthorizationSimulatorRouteImport.update({
    id: '/authorization/simulator',
    path: '/authorization/simulator',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthorizationSettingsRoute =
  AppAuthorizationSettingsRouteImport.update({
    id: '/authorization/settings',
    path: '/authorization/settings',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthorizationRolesRoute = AppAuthorizationRolesRouteImport.update({
  id: '/authorization/roles',
  path: '/authorization/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthorizationResourcesRoute =
  AppAuthorizationResourcesRouteImport.update({
    id: '/authorization/resources',
    path: '/authorization/resources',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthorizationRebacRoute = AppAuthorizationRebacRouteImport.update({
  id: '/authorization/rebac',
  path: '/authorization/rebac',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthorizationRbacRoute = AppAuthorizationRbacRouteImport.update({
  id: '/authorization/rbac',
  path: '/authorization/rbac',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthorizationPermissionsRoute =
  AppAuthorizationPermissionsRouteImport.update({
    id: '/authorization/permissions',
    path: '/authorization/permissions',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthorizationExplorerRoute =
  AppAuthorizationExplorerRouteImport.update({
    id: '/authorization/explorer',
    path: '/authorization/explorer',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthorizationBuilderRoute = AppAuthorizationBuilderRouteImport.update({
  id: '/authorization/builder',
  path: '/authorization/builder',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthorizationAuditRoute = AppAuthorizationAuditRouteImport.update({
  id: '/authorization/audit',
  path: '/authorization/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthorizationAssistantRoute =
  AppAuthorizationAssistantRouteImport.update({
    id: '/authorization/assistant',
    path: '/authorization/assistant',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthorizationAccessTesterRoute =
  AppAuthorizationAccessTesterRouteImport.update({
    id: '/authorization/access-tester',
    path: '/authorization/access-tester',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthorizationAbacRoute = AppAuthorizationAbacRouteImport.update({
  id: '/authorization/abac',
  path: '/authorization/abac',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthSocialRoute = AppAuthSocialRouteImport.update({
  id: '/auth/social',
  path: '/auth/social',
  getParentRoute: () => AppRoute,
} as any)
const AppDeveloperWebhooksIndexRoute =
  AppDeveloperWebhooksIndexRouteImport.update({
    id: '/developer/webhooks/',
    path: '/developer/webhooks/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthConnectionsIndexRoute = AppAuthConnectionsIndexRouteImport.update({
  id: '/auth/connections/',
  path: '/auth/connections/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersUserIdTimelineRoute = AppUsersUserIdTimelineRouteImport.update({
  id: '/users/$userId_/timeline',
  path: '/users/$userId/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsWorkspaceSecurityPolicyRoute =
  AppSettingsWorkspaceSecurityPolicyRouteImport.update({
    id: '/settings/workspace/security-policy',
    path: '/settings/workspace/security-policy',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsWorkspaceGeneralRoute =
  AppSettingsWorkspaceGeneralRouteImport.update({
    id: '/settings/workspace/general',
    path: '/settings/workspace/general',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsWorkspaceEmailTemplatesRoute =
  AppSettingsWorkspaceEmailTemplatesRouteImport.update({
    id: '/settings/workspace/email-templates',
    path: '/settings/workspace/email-templates',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsWorkspaceDomainsRoute =
  AppSettingsWorkspaceDomainsRouteImport.update({
    id: '/settings/workspace/domains',
    path: '/settings/workspace/domains',
    getParentRoute: () => AppRoute,
  } as any)
const AppSecurityThreatsRiskSettingsRoute =
  AppSecurityThreatsRiskSettingsRouteImport.update({
    id: '/security/threats/risk-settings',
    path: '/security/threats/risk-settings',
    getParentRoute: () => AppRoute,
  } as any)
const AppSecurityThreatsRateLimitsRoute =
  AppSecurityThreatsRateLimitsRouteImport.update({
    id: '/security/threats/rate-limits',
    path: '/security/threats/rate-limits',
    getParentRoute: () => AppRoute,
  } as any)
const AppSecurityThreatsIpAllowlistRoute =
  AppSecurityThreatsIpAllowlistRouteImport.update({
    id: '/security/threats/ip-allowlist',
    path: '/security/threats/ip-allowlist',
    getParentRoute: () => AppRoute,
  } as any)
const AppSecurityThreatsBotsRoute = AppSecurityThreatsBotsRouteImport.update({
  id: '/security/threats/bots',
  path: '/security/threats/bots',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityThreatsAnomaliesRoute =
  AppSecurityThreatsAnomaliesRouteImport.update({
    id: '/security/threats/anomalies',
    path: '/security/threats/anomalies',
    getParentRoute: () => AppRoute,
  } as any)
const AppSecurityComplianceSoc2Route =
  AppSecurityComplianceSoc2RouteImport.update({
    id: '/security/compliance/soc2',
    path: '/security/compliance/soc2',
    getParentRoute: () => AppRoute,
  } as any)
const AppSecurityComplianceRetentionRoute =
  AppSecurityComplianceRetentionRouteImport.update({
    id: '/security/compliance/retention',
    path: '/security/compliance/retention',
    getParentRoute: () => AppRoute,
  } as any)
const AppSecurityComplianceIso27001Route =
  AppSecurityComplianceIso27001RouteImport.update({
    id: '/security/compliance/iso27001',
    path: '/security/compliance/iso27001',
    getParentRoute: () => AppRoute,
  } as any)
const AppSecurityComplianceGdprRoute =
  AppSecurityComplianceGdprRouteImport.update({
    id: '/security/compliance/gdpr',
    path: '/security/compliance/gdpr',
    getParentRoute: () => AppRoute,
  } as any)
const AppDeveloperWebhooksIdRoute = AppDeveloperWebhooksIdRouteImport.update({
  id: '/developer/webhooks/$id',
  path: '/developer/webhooks/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthMfaTotpRoute = AppAuthMfaTotpRouteImport.update({
  id: '/auth/mfa/totp',
  path: '/auth/mfa/totp',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthMfaSmsEmailRoute = AppAuthMfaSmsEmailRouteImport.update({
  id: '/auth/mfa/sms-email',
  path: '/auth/mfa/sms-email',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthMfaRecoveryCodesRoute = AppAuthMfaRecoveryCodesRouteImport.update({
  id: '/auth/mfa/recovery-codes',
  path: '/auth/mfa/recovery-codes',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthLoginMethodsPasswordlessRoute =
  AppAuthLoginMethodsPasswordlessRouteImport.update({
    id: '/auth/login-methods/passwordless',
    path: '/auth/login-methods/passwordless',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthLoginMethodsPasswordRoute =
  AppAuthLoginMethodsPasswordRouteImport.update({
    id: '/auth/login-methods/password',
    path: '/auth/login-methods/password',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthLoginMethodsPasskeysRoute =
  AppAuthLoginMethodsPasskeysRouteImport.update({
    id: '/auth/login-methods/passkeys',
    path: '/auth/login-methods/passkeys',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthLoginMethodsMagicLinksRoute =
  AppAuthLoginMethodsMagicLinksRouteImport.update({
    id: '/auth/login-methods/magic-links',
    path: '/auth/login-methods/magic-links',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthConnectionsScimRoute = AppAuthConnectionsScimRouteImport.update({
  id: '/auth/connections/scim',
  path: '/auth/connections/scim',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthConnectionsSamlIdpRoute =
  AppAuthConnectionsSamlIdpRouteImport.update({
    id: '/auth/connections/saml-idp',
    path: '/auth/connections/saml-idp',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthConnectionsSamlRoute = AppAuthConnectionsSamlRouteImport.update({
  id: '/auth/connections/saml',
  path: '/auth/connections/saml',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthConnectionsLdapRoute = AppAuthConnectionsLdapRouteImport.update({
  id: '/auth/connections/ldap',
  path: '/auth/connections/ldap',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthApiTokensRoute = AppAuthApiTokensRouteImport.update({
  id: '/auth/api/tokens',
  path: '/auth/api/tokens',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthApiSigningKeysRoute = AppAuthApiSigningKeysRouteImport.update({
  id: '/auth/api/signing-keys',
  path: '/auth/api/signing-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthApiSecretsRoute = AppAuthApiSecretsRouteImport.update({
  id: '/auth/api/secrets',
  path: '/auth/api/secrets',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthApiMachineIdentitiesRoute =
  AppAuthApiMachineIdentitiesRouteImport.update({
    id: '/auth/api/machine-identities',
    path: '/auth/api/machine-identities',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthApiKeysRoute = AppAuthApiKeysRouteImport.update({
  id: '/auth/api/keys',
  path: '/auth/api/keys',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthApiConsentGrantsRoute = AppAuthApiConsentGrantsRouteImport.update({
  id: '/auth/api/consent-grants',
  path: '/auth/api/consent-grants',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthConnectionsOidcIndexRoute =
  AppAuthConnectionsOidcIndexRouteImport.update({
    id: '/auth/connections/oidc/',
    path: '/auth/connections/oidc/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthConnectionsOidcClientIdRoute =
  AppAuthConnectionsOidcClientIdRouteImport.update({
    id: '/auth/connections/oidc/$clientId',
    path: '/auth/connections/oidc/$clientId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/account': typeof AccountRouteWithChildren
  '/$': typeof AppSplatRoute
  '/activity': typeof AppActivityRoute
  '/analytics': typeof AppAnalyticsRoute
  '/invitations': typeof AppInvitationsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/magic': typeof AuthMagicRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/account/data': typeof AccountDataRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/auth/social': typeof AppAuthSocialRoute
  '/authorization/abac': typeof AppAuthorizationAbacRoute
  '/authorization/access-tester': typeof AppAuthorizationAccessTesterRoute
  '/authorization/assistant': typeof AppAuthorizationAssistantRoute
  '/authorization/audit': typeof AppAuthorizationAuditRoute
  '/authorization/builder': typeof AppAuthorizationBuilderRoute
  '/authorization/explorer': typeof AppAuthorizationExplorerRoute
  '/authorization/permissions': typeof AppAuthorizationPermissionsRoute
  '/authorization/rbac': typeof AppAuthorizationRbacRoute
  '/authorization/rebac': typeof AppAuthorizationRebacRoute
  '/authorization/resources': typeof AppAuthorizationResourcesRoute
  '/authorization/roles': typeof AppAuthorizationRolesRoute
  '/authorization/settings': typeof AppAuthorizationSettingsRoute
  '/authorization/simulator': typeof AppAuthorizationSimulatorRoute
  '/authorization/templates': typeof AppAuthorizationTemplatesRoute
  '/authorization/versions': typeof AppAuthorizationVersionsRoute
  '/developer/agents': typeof AppDeveloperAgentsRoute
  '/developer/auth-hooks': typeof AppDeveloperAuthHooksRoute
  '/developer/bots': typeof AppDeveloperBotsRoute
  '/developer/credentials': typeof AppDeveloperCredentialsRoute
  '/developer/infrastructure': typeof AppDeveloperInfrastructureRoute
  '/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/organizations/domains': typeof AppOrganizationsDomainsRoute
  '/organizations/members': typeof AppOrganizationsMembersRoute
  '/organizations/tenants': typeof AppOrganizationsTenantsRoute
  '/security/audit-intelligence': typeof AppSecurityAuditIntelligenceRoute
  '/security/audit-logs': typeof AppSecurityAuditLogsRoute
  '/security/device-authorizations': typeof AppSecurityDeviceAuthorizationsRoute
  '/security/log-streaming': typeof AppSecurityLogStreamingRoute
  '/security/rate-limits': typeof AppSecurityRateLimitsRoute
  '/security/sessions': typeof AppSecuritySessionsRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/branding': typeof AppSettingsBrandingRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/users/deleted': typeof AppUsersDeletedRoute
  '/users/import': typeof AppUsersImportRoute
  '/users/invitations': typeof AppUsersInvitationsRoute
  '/users/sessions': typeof AppUsersSessionsRoute
  '/invite/accept': typeof AuthInviteAcceptRoute
  '/sso/callback': typeof AuthSsoCallbackRoute
  '/authorization/': typeof AppAuthorizationIndexRoute
  '/groups/': typeof AppGroupsIndexRoute
  '/security/': typeof AppSecurityIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/auth/api/consent-grants': typeof AppAuthApiConsentGrantsRoute
  '/auth/api/keys': typeof AppAuthApiKeysRoute
  '/auth/api/machine-identities': typeof AppAuthApiMachineIdentitiesRoute
  '/auth/api/secrets': typeof AppAuthApiSecretsRoute
  '/auth/api/signing-keys': typeof AppAuthApiSigningKeysRoute
  '/auth/api/tokens': typeof AppAuthApiTokensRoute
  '/auth/connections/ldap': typeof AppAuthConnectionsLdapRoute
  '/auth/connections/saml': typeof AppAuthConnectionsSamlRoute
  '/auth/connections/saml-idp': typeof AppAuthConnectionsSamlIdpRoute
  '/auth/connections/scim': typeof AppAuthConnectionsScimRoute
  '/auth/login-methods/magic-links': typeof AppAuthLoginMethodsMagicLinksRoute
  '/auth/login-methods/passkeys': typeof AppAuthLoginMethodsPasskeysRoute
  '/auth/login-methods/password': typeof AppAuthLoginMethodsPasswordRoute
  '/auth/login-methods/passwordless': typeof AppAuthLoginMethodsPasswordlessRoute
  '/auth/mfa/recovery-codes': typeof AppAuthMfaRecoveryCodesRoute
  '/auth/mfa/sms-email': typeof AppAuthMfaSmsEmailRoute
  '/auth/mfa/totp': typeof AppAuthMfaTotpRoute
  '/developer/webhooks/$id': typeof AppDeveloperWebhooksIdRoute
  '/security/compliance/gdpr': typeof AppSecurityComplianceGdprRoute
  '/security/compliance/iso27001': typeof AppSecurityComplianceIso27001Route
  '/security/compliance/retention': typeof AppSecurityComplianceRetentionRoute
  '/security/compliance/soc2': typeof AppSecurityComplianceSoc2Route
  '/security/threats/anomalies': typeof AppSecurityThreatsAnomaliesRoute
  '/security/threats/bots': typeof AppSecurityThreatsBotsRoute
  '/security/threats/ip-allowlist': typeof AppSecurityThreatsIpAllowlistRoute
  '/security/threats/rate-limits': typeof AppSecurityThreatsRateLimitsRoute
  '/security/threats/risk-settings': typeof AppSecurityThreatsRiskSettingsRoute
  '/settings/workspace/domains': typeof AppSettingsWorkspaceDomainsRoute
  '/settings/workspace/email-templates': typeof AppSettingsWorkspaceEmailTemplatesRoute
  '/settings/workspace/general': typeof AppSettingsWorkspaceGeneralRoute
  '/settings/workspace/security-policy': typeof AppSettingsWorkspaceSecurityPolicyRoute
  '/users/$userId/timeline': typeof AppUsersUserIdTimelineRoute
  '/auth/connections/': typeof AppAuthConnectionsIndexRoute
  '/developer/webhooks/': typeof AppDeveloperWebhooksIndexRoute
  '/auth/connections/oidc/$clientId': typeof AppAuthConnectionsOidcClientIdRoute
  '/auth/connections/oidc/': typeof AppAuthConnectionsOidcIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/account': typeof AccountRouteWithChildren
  '/$': typeof AppSplatRoute
  '/activity': typeof AppActivityRoute
  '/analytics': typeof AppAnalyticsRoute
  '/invitations': typeof AppInvitationsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/magic': typeof AuthMagicRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/account/data': typeof AccountDataRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/auth/social': typeof AppAuthSocialRoute
  '/authorization/abac': typeof AppAuthorizationAbacRoute
  '/authorization/access-tester': typeof AppAuthorizationAccessTesterRoute
  '/authorization/assistant': typeof AppAuthorizationAssistantRoute
  '/authorization/audit': typeof AppAuthorizationAuditRoute
  '/authorization/builder': typeof AppAuthorizationBuilderRoute
  '/authorization/explorer': typeof AppAuthorizationExplorerRoute
  '/authorization/permissions': typeof AppAuthorizationPermissionsRoute
  '/authorization/rbac': typeof AppAuthorizationRbacRoute
  '/authorization/rebac': typeof AppAuthorizationRebacRoute
  '/authorization/resources': typeof AppAuthorizationResourcesRoute
  '/authorization/roles': typeof AppAuthorizationRolesRoute
  '/authorization/settings': typeof AppAuthorizationSettingsRoute
  '/authorization/simulator': typeof AppAuthorizationSimulatorRoute
  '/authorization/templates': typeof AppAuthorizationTemplatesRoute
  '/authorization/versions': typeof AppAuthorizationVersionsRoute
  '/developer/agents': typeof AppDeveloperAgentsRoute
  '/developer/auth-hooks': typeof AppDeveloperAuthHooksRoute
  '/developer/bots': typeof AppDeveloperBotsRoute
  '/developer/credentials': typeof AppDeveloperCredentialsRoute
  '/developer/infrastructure': typeof AppDeveloperInfrastructureRoute
  '/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/organizations/domains': typeof AppOrganizationsDomainsRoute
  '/organizations/members': typeof AppOrganizationsMembersRoute
  '/organizations/tenants': typeof AppOrganizationsTenantsRoute
  '/security/audit-intelligence': typeof AppSecurityAuditIntelligenceRoute
  '/security/audit-logs': typeof AppSecurityAuditLogsRoute
  '/security/device-authorizations': typeof AppSecurityDeviceAuthorizationsRoute
  '/security/log-streaming': typeof AppSecurityLogStreamingRoute
  '/security/rate-limits': typeof AppSecurityRateLimitsRoute
  '/security/sessions': typeof AppSecuritySessionsRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/branding': typeof AppSettingsBrandingRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/users/deleted': typeof AppUsersDeletedRoute
  '/users/import': typeof AppUsersImportRoute
  '/users/invitations': typeof AppUsersInvitationsRoute
  '/users/sessions': typeof AppUsersSessionsRoute
  '/invite/accept': typeof AuthInviteAcceptRoute
  '/sso/callback': typeof AuthSsoCallbackRoute
  '/authorization': typeof AppAuthorizationIndexRoute
  '/groups': typeof AppGroupsIndexRoute
  '/security': typeof AppSecurityIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/auth/api/consent-grants': typeof AppAuthApiConsentGrantsRoute
  '/auth/api/keys': typeof AppAuthApiKeysRoute
  '/auth/api/machine-identities': typeof AppAuthApiMachineIdentitiesRoute
  '/auth/api/secrets': typeof AppAuthApiSecretsRoute
  '/auth/api/signing-keys': typeof AppAuthApiSigningKeysRoute
  '/auth/api/tokens': typeof AppAuthApiTokensRoute
  '/auth/connections/ldap': typeof AppAuthConnectionsLdapRoute
  '/auth/connections/saml': typeof AppAuthConnectionsSamlRoute
  '/auth/connections/saml-idp': typeof AppAuthConnectionsSamlIdpRoute
  '/auth/connections/scim': typeof AppAuthConnectionsScimRoute
  '/auth/login-methods/magic-links': typeof AppAuthLoginMethodsMagicLinksRoute
  '/auth/login-methods/passkeys': typeof AppAuthLoginMethodsPasskeysRoute
  '/auth/login-methods/password': typeof AppAuthLoginMethodsPasswordRoute
  '/auth/login-methods/passwordless': typeof AppAuthLoginMethodsPasswordlessRoute
  '/auth/mfa/recovery-codes': typeof AppAuthMfaRecoveryCodesRoute
  '/auth/mfa/sms-email': typeof AppAuthMfaSmsEmailRoute
  '/auth/mfa/totp': typeof AppAuthMfaTotpRoute
  '/developer/webhooks/$id': typeof AppDeveloperWebhooksIdRoute
  '/security/compliance/gdpr': typeof AppSecurityComplianceGdprRoute
  '/security/compliance/iso27001': typeof AppSecurityComplianceIso27001Route
  '/security/compliance/retention': typeof AppSecurityComplianceRetentionRoute
  '/security/compliance/soc2': typeof AppSecurityComplianceSoc2Route
  '/security/threats/anomalies': typeof AppSecurityThreatsAnomaliesRoute
  '/security/threats/bots': typeof AppSecurityThreatsBotsRoute
  '/security/threats/ip-allowlist': typeof AppSecurityThreatsIpAllowlistRoute
  '/security/threats/rate-limits': typeof AppSecurityThreatsRateLimitsRoute
  '/security/threats/risk-settings': typeof AppSecurityThreatsRiskSettingsRoute
  '/settings/workspace/domains': typeof AppSettingsWorkspaceDomainsRoute
  '/settings/workspace/email-templates': typeof AppSettingsWorkspaceEmailTemplatesRoute
  '/settings/workspace/general': typeof AppSettingsWorkspaceGeneralRoute
  '/settings/workspace/security-policy': typeof AppSettingsWorkspaceSecurityPolicyRoute
  '/users/$userId/timeline': typeof AppUsersUserIdTimelineRoute
  '/auth/connections': typeof AppAuthConnectionsIndexRoute
  '/developer/webhooks': typeof AppDeveloperWebhooksIndexRoute
  '/auth/connections/oidc/$clientId': typeof AppAuthConnectionsOidcClientIdRoute
  '/auth/connections/oidc': typeof AppAuthConnectionsOidcIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/_app/$': typeof AppSplatRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/invitations': typeof AppInvitationsRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/magic': typeof AuthMagicRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/account/data': typeof AccountDataRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/auth/social': typeof AppAuthSocialRoute
  '/_app/authorization/abac': typeof AppAuthorizationAbacRoute
  '/_app/authorization/access-tester': typeof AppAuthorizationAccessTesterRoute
  '/_app/authorization/assistant': typeof AppAuthorizationAssistantRoute
  '/_app/authorization/audit': typeof AppAuthorizationAuditRoute
  '/_app/authorization/builder': typeof AppAuthorizationBuilderRoute
  '/_app/authorization/explorer': typeof AppAuthorizationExplorerRoute
  '/_app/authorization/permissions': typeof AppAuthorizationPermissionsRoute
  '/_app/authorization/rbac': typeof AppAuthorizationRbacRoute
  '/_app/authorization/rebac': typeof AppAuthorizationRebacRoute
  '/_app/authorization/resources': typeof AppAuthorizationResourcesRoute
  '/_app/authorization/roles': typeof AppAuthorizationRolesRoute
  '/_app/authorization/settings': typeof AppAuthorizationSettingsRoute
  '/_app/authorization/simulator': typeof AppAuthorizationSimulatorRoute
  '/_app/authorization/templates': typeof AppAuthorizationTemplatesRoute
  '/_app/authorization/versions': typeof AppAuthorizationVersionsRoute
  '/_app/developer/agents': typeof AppDeveloperAgentsRoute
  '/_app/developer/auth-hooks': typeof AppDeveloperAuthHooksRoute
  '/_app/developer/bots': typeof AppDeveloperBotsRoute
  '/_app/developer/credentials': typeof AppDeveloperCredentialsRoute
  '/_app/developer/infrastructure': typeof AppDeveloperInfrastructureRoute
  '/_app/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/_app/organizations/domains': typeof AppOrganizationsDomainsRoute
  '/_app/organizations/members': typeof AppOrganizationsMembersRoute
  '/_app/organizations/tenants': typeof AppOrganizationsTenantsRoute
  '/_app/security/audit-intelligence': typeof AppSecurityAuditIntelligenceRoute
  '/_app/security/audit-logs': typeof AppSecurityAuditLogsRoute
  '/_app/security/device-authorizations': typeof AppSecurityDeviceAuthorizationsRoute
  '/_app/security/log-streaming': typeof AppSecurityLogStreamingRoute
  '/_app/security/rate-limits': typeof AppSecurityRateLimitsRoute
  '/_app/security/sessions': typeof AppSecuritySessionsRoute
  '/_app/settings/billing': typeof AppSettingsBillingRoute
  '/_app/settings/branding': typeof AppSettingsBrandingRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/_app/users/deleted': typeof AppUsersDeletedRoute
  '/_app/users/import': typeof AppUsersImportRoute
  '/_app/users/invitations': typeof AppUsersInvitationsRoute
  '/_app/users/sessions': typeof AppUsersSessionsRoute
  '/_auth/invite/accept': typeof AuthInviteAcceptRoute
  '/_auth/sso/callback': typeof AuthSsoCallbackRoute
  '/_app/authorization/': typeof AppAuthorizationIndexRoute
  '/_app/groups/': typeof AppGroupsIndexRoute
  '/_app/security/': typeof AppSecurityIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_app/auth/api/consent-grants': typeof AppAuthApiConsentGrantsRoute
  '/_app/auth/api/keys': typeof AppAuthApiKeysRoute
  '/_app/auth/api/machine-identities': typeof AppAuthApiMachineIdentitiesRoute
  '/_app/auth/api/secrets': typeof AppAuthApiSecretsRoute
  '/_app/auth/api/signing-keys': typeof AppAuthApiSigningKeysRoute
  '/_app/auth/api/tokens': typeof AppAuthApiTokensRoute
  '/_app/auth/connections/ldap': typeof AppAuthConnectionsLdapRoute
  '/_app/auth/connections/saml': typeof AppAuthConnectionsSamlRoute
  '/_app/auth/connections/saml-idp': typeof AppAuthConnectionsSamlIdpRoute
  '/_app/auth/connections/scim': typeof AppAuthConnectionsScimRoute
  '/_app/auth/login-methods/magic-links': typeof AppAuthLoginMethodsMagicLinksRoute
  '/_app/auth/login-methods/passkeys': typeof AppAuthLoginMethodsPasskeysRoute
  '/_app/auth/login-methods/password': typeof AppAuthLoginMethodsPasswordRoute
  '/_app/auth/login-methods/passwordless': typeof AppAuthLoginMethodsPasswordlessRoute
  '/_app/auth/mfa/recovery-codes': typeof AppAuthMfaRecoveryCodesRoute
  '/_app/auth/mfa/sms-email': typeof AppAuthMfaSmsEmailRoute
  '/_app/auth/mfa/totp': typeof AppAuthMfaTotpRoute
  '/_app/developer/webhooks/$id': typeof AppDeveloperWebhooksIdRoute
  '/_app/security/compliance/gdpr': typeof AppSecurityComplianceGdprRoute
  '/_app/security/compliance/iso27001': typeof AppSecurityComplianceIso27001Route
  '/_app/security/compliance/retention': typeof AppSecurityComplianceRetentionRoute
  '/_app/security/compliance/soc2': typeof AppSecurityComplianceSoc2Route
  '/_app/security/threats/anomalies': typeof AppSecurityThreatsAnomaliesRoute
  '/_app/security/threats/bots': typeof AppSecurityThreatsBotsRoute
  '/_app/security/threats/ip-allowlist': typeof AppSecurityThreatsIpAllowlistRoute
  '/_app/security/threats/rate-limits': typeof AppSecurityThreatsRateLimitsRoute
  '/_app/security/threats/risk-settings': typeof AppSecurityThreatsRiskSettingsRoute
  '/_app/settings/workspace/domains': typeof AppSettingsWorkspaceDomainsRoute
  '/_app/settings/workspace/email-templates': typeof AppSettingsWorkspaceEmailTemplatesRoute
  '/_app/settings/workspace/general': typeof AppSettingsWorkspaceGeneralRoute
  '/_app/settings/workspace/security-policy': typeof AppSettingsWorkspaceSecurityPolicyRoute
  '/_app/users/$userId_/timeline': typeof AppUsersUserIdTimelineRoute
  '/_app/auth/connections/': typeof AppAuthConnectionsIndexRoute
  '/_app/developer/webhooks/': typeof AppDeveloperWebhooksIndexRoute
  '/_app/auth/connections/oidc/$clientId': typeof AppAuthConnectionsOidcClientIdRoute
  '/_app/auth/connections/oidc/': typeof AppAuthConnectionsOidcIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/$'
    | '/activity'
    | '/analytics'
    | '/invitations'
    | '/forgot-password'
    | '/magic'
    | '/sign-in'
    | '/sign-up'
    | '/account/data'
    | '/account/profile'
    | '/account/security'
    | '/account/sessions'
    | '/auth/social'
    | '/authorization/abac'
    | '/authorization/access-tester'
    | '/authorization/assistant'
    | '/authorization/audit'
    | '/authorization/builder'
    | '/authorization/explorer'
    | '/authorization/permissions'
    | '/authorization/rbac'
    | '/authorization/rebac'
    | '/authorization/resources'
    | '/authorization/roles'
    | '/authorization/settings'
    | '/authorization/simulator'
    | '/authorization/templates'
    | '/authorization/versions'
    | '/developer/agents'
    | '/developer/auth-hooks'
    | '/developer/bots'
    | '/developer/credentials'
    | '/developer/infrastructure'
    | '/groups/$groupId'
    | '/organizations/domains'
    | '/organizations/members'
    | '/organizations/tenants'
    | '/security/audit-intelligence'
    | '/security/audit-logs'
    | '/security/device-authorizations'
    | '/security/log-streaming'
    | '/security/rate-limits'
    | '/security/sessions'
    | '/settings/billing'
    | '/settings/branding'
    | '/users/$userId'
    | '/users/deleted'
    | '/users/import'
    | '/users/invitations'
    | '/users/sessions'
    | '/invite/accept'
    | '/sso/callback'
    | '/authorization/'
    | '/groups/'
    | '/security/'
    | '/users/'
    | '/auth/api/consent-grants'
    | '/auth/api/keys'
    | '/auth/api/machine-identities'
    | '/auth/api/secrets'
    | '/auth/api/signing-keys'
    | '/auth/api/tokens'
    | '/auth/connections/ldap'
    | '/auth/connections/saml'
    | '/auth/connections/saml-idp'
    | '/auth/connections/scim'
    | '/auth/login-methods/magic-links'
    | '/auth/login-methods/passkeys'
    | '/auth/login-methods/password'
    | '/auth/login-methods/passwordless'
    | '/auth/mfa/recovery-codes'
    | '/auth/mfa/sms-email'
    | '/auth/mfa/totp'
    | '/developer/webhooks/$id'
    | '/security/compliance/gdpr'
    | '/security/compliance/iso27001'
    | '/security/compliance/retention'
    | '/security/compliance/soc2'
    | '/security/threats/anomalies'
    | '/security/threats/bots'
    | '/security/threats/ip-allowlist'
    | '/security/threats/rate-limits'
    | '/security/threats/risk-settings'
    | '/settings/workspace/domains'
    | '/settings/workspace/email-templates'
    | '/settings/workspace/general'
    | '/settings/workspace/security-policy'
    | '/users/$userId/timeline'
    | '/auth/connections/'
    | '/developer/webhooks/'
    | '/auth/connections/oidc/$clientId'
    | '/auth/connections/oidc/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/$'
    | '/activity'
    | '/analytics'
    | '/invitations'
    | '/forgot-password'
    | '/magic'
    | '/sign-in'
    | '/sign-up'
    | '/account/data'
    | '/account/profile'
    | '/account/security'
    | '/account/sessions'
    | '/auth/social'
    | '/authorization/abac'
    | '/authorization/access-tester'
    | '/authorization/assistant'
    | '/authorization/audit'
    | '/authorization/builder'
    | '/authorization/explorer'
    | '/authorization/permissions'
    | '/authorization/rbac'
    | '/authorization/rebac'
    | '/authorization/resources'
    | '/authorization/roles'
    | '/authorization/settings'
    | '/authorization/simulator'
    | '/authorization/templates'
    | '/authorization/versions'
    | '/developer/agents'
    | '/developer/auth-hooks'
    | '/developer/bots'
    | '/developer/credentials'
    | '/developer/infrastructure'
    | '/groups/$groupId'
    | '/organizations/domains'
    | '/organizations/members'
    | '/organizations/tenants'
    | '/security/audit-intelligence'
    | '/security/audit-logs'
    | '/security/device-authorizations'
    | '/security/log-streaming'
    | '/security/rate-limits'
    | '/security/sessions'
    | '/settings/billing'
    | '/settings/branding'
    | '/users/$userId'
    | '/users/deleted'
    | '/users/import'
    | '/users/invitations'
    | '/users/sessions'
    | '/invite/accept'
    | '/sso/callback'
    | '/authorization'
    | '/groups'
    | '/security'
    | '/users'
    | '/auth/api/consent-grants'
    | '/auth/api/keys'
    | '/auth/api/machine-identities'
    | '/auth/api/secrets'
    | '/auth/api/signing-keys'
    | '/auth/api/tokens'
    | '/auth/connections/ldap'
    | '/auth/connections/saml'
    | '/auth/connections/saml-idp'
    | '/auth/connections/scim'
    | '/auth/login-methods/magic-links'
    | '/auth/login-methods/passkeys'
    | '/auth/login-methods/password'
    | '/auth/login-methods/passwordless'
    | '/auth/mfa/recovery-codes'
    | '/auth/mfa/sms-email'
    | '/auth/mfa/totp'
    | '/developer/webhooks/$id'
    | '/security/compliance/gdpr'
    | '/security/compliance/iso27001'
    | '/security/compliance/retention'
    | '/security/compliance/soc2'
    | '/security/threats/anomalies'
    | '/security/threats/bots'
    | '/security/threats/ip-allowlist'
    | '/security/threats/rate-limits'
    | '/security/threats/risk-settings'
    | '/settings/workspace/domains'
    | '/settings/workspace/email-templates'
    | '/settings/workspace/general'
    | '/settings/workspace/security-policy'
    | '/users/$userId/timeline'
    | '/auth/connections'
    | '/developer/webhooks'
    | '/auth/connections/oidc/$clientId'
    | '/auth/connections/oidc'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/account'
    | '/_app/$'
    | '/_app/activity'
    | '/_app/analytics'
    | '/_app/invitations'
    | '/_auth/forgot-password'
    | '/_auth/magic'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/account/data'
    | '/account/profile'
    | '/account/security'
    | '/account/sessions'
    | '/_app/'
    | '/_app/auth/social'
    | '/_app/authorization/abac'
    | '/_app/authorization/access-tester'
    | '/_app/authorization/assistant'
    | '/_app/authorization/audit'
    | '/_app/authorization/builder'
    | '/_app/authorization/explorer'
    | '/_app/authorization/permissions'
    | '/_app/authorization/rbac'
    | '/_app/authorization/rebac'
    | '/_app/authorization/resources'
    | '/_app/authorization/roles'
    | '/_app/authorization/settings'
    | '/_app/authorization/simulator'
    | '/_app/authorization/templates'
    | '/_app/authorization/versions'
    | '/_app/developer/agents'
    | '/_app/developer/auth-hooks'
    | '/_app/developer/bots'
    | '/_app/developer/credentials'
    | '/_app/developer/infrastructure'
    | '/_app/groups/$groupId'
    | '/_app/organizations/domains'
    | '/_app/organizations/members'
    | '/_app/organizations/tenants'
    | '/_app/security/audit-intelligence'
    | '/_app/security/audit-logs'
    | '/_app/security/device-authorizations'
    | '/_app/security/log-streaming'
    | '/_app/security/rate-limits'
    | '/_app/security/sessions'
    | '/_app/settings/billing'
    | '/_app/settings/branding'
    | '/_app/users/$userId'
    | '/_app/users/deleted'
    | '/_app/users/import'
    | '/_app/users/invitations'
    | '/_app/users/sessions'
    | '/_auth/invite/accept'
    | '/_auth/sso/callback'
    | '/_app/authorization/'
    | '/_app/groups/'
    | '/_app/security/'
    | '/_app/users/'
    | '/_app/auth/api/consent-grants'
    | '/_app/auth/api/keys'
    | '/_app/auth/api/machine-identities'
    | '/_app/auth/api/secrets'
    | '/_app/auth/api/signing-keys'
    | '/_app/auth/api/tokens'
    | '/_app/auth/connections/ldap'
    | '/_app/auth/connections/saml'
    | '/_app/auth/connections/saml-idp'
    | '/_app/auth/connections/scim'
    | '/_app/auth/login-methods/magic-links'
    | '/_app/auth/login-methods/passkeys'
    | '/_app/auth/login-methods/password'
    | '/_app/auth/login-methods/passwordless'
    | '/_app/auth/mfa/recovery-codes'
    | '/_app/auth/mfa/sms-email'
    | '/_app/auth/mfa/totp'
    | '/_app/developer/webhooks/$id'
    | '/_app/security/compliance/gdpr'
    | '/_app/security/compliance/iso27001'
    | '/_app/security/compliance/retention'
    | '/_app/security/compliance/soc2'
    | '/_app/security/threats/anomalies'
    | '/_app/security/threats/bots'
    | '/_app/security/threats/ip-allowlist'
    | '/_app/security/threats/rate-limits'
    | '/_app/security/threats/risk-settings'
    | '/_app/settings/workspace/domains'
    | '/_app/settings/workspace/email-templates'
    | '/_app/settings/workspace/general'
    | '/_app/settings/workspace/security-policy'
    | '/_app/users/$userId_/timeline'
    | '/_app/auth/connections/'
    | '/_app/developer/webhooks/'
    | '/_app/auth/connections/oidc/$clientId'
    | '/_app/auth/connections/oidc/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/account/sessions': {
      id: '/account/sessions'
      path: '/sessions'
      fullPath: '/account/sessions'
      preLoaderRoute: typeof AccountSessionsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/data': {
      id: '/account/data'
      path: '/data'
      fullPath: '/account/data'
      preLoaderRoute: typeof AccountDataRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/magic': {
      id: '/_auth/magic'
      path: '/magic'
      fullPath: '/magic'
      preLoaderRoute: typeof AuthMagicRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/invitations': {
      id: '/_app/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AppInvitationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/': {
      id: '/_app/security/'
      path: '/security'
      fullPath: '/security/'
      preLoaderRoute: typeof AppSecurityIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/': {
      id: '/_app/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/authorization/': {
      id: '/_app/authorization/'
      path: '/authorization'
      fullPath: '/authorization/'
      preLoaderRoute: typeof AppAuthorizationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/sso/callback': {
      id: '/_auth/sso/callback'
      path: '/sso/callback'
      fullPath: '/sso/callback'
      preLoaderRoute: typeof AuthSsoCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/invite/accept': {
      id: '/_auth/invite/accept'
      path: '/invite/accept'
      fullPath: '/invite/accept'
      preLoaderRoute: typeof AuthInviteAcceptRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/users/sessions': {
      id: '/_app/users/sessions'
      path: '/users/sessions'
      fullPath: '/users/sessions'
      preLoaderRoute: typeof AppUsersSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/invitations': {
      id: '/_app/users/invitations'
      path: '/users/invitations'
      fullPath: '/users/invitations'
      preLoaderRoute: typeof AppUsersInvitationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/import': {
      id: '/_app/users/import'
      path: '/users/import'
      fullPath: '/users/import'
      preLoaderRoute: typeof AppUsersImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/deleted': {
      id: '/_app/users/deleted'
      path: '/users/deleted'
      fullPath: '/users/deleted'
      preLoaderRoute: typeof AppUsersDeletedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/branding': {
      id: '/_app/settings/branding'
      path: '/settings/branding'
      fullPath: '/settings/branding'
      preLoaderRoute: typeof AppSettingsBrandingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/billing': {
      id: '/_app/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/sessions': {
      id: '/_app/security/sessions'
      path: '/security/sessions'
      fullPath: '/security/sessions'
      preLoaderRoute: typeof AppSecuritySessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/rate-limits': {
      id: '/_app/security/rate-limits'
      path: '/security/rate-limits'
      fullPath: '/security/rate-limits'
      preLoaderRoute: typeof AppSecurityRateLimitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/log-streaming': {
      id: '/_app/security/log-streaming'
      path: '/security/log-streaming'
      fullPath: '/security/log-streaming'
      preLoaderRoute: typeof AppSecurityLogStreamingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/device-authorizations': {
      id: '/_app/security/device-authorizations'
      path: '/security/device-authorizations'
      fullPath: '/security/device-authorizations'
      preLoaderRoute: typeof AppSecurityDeviceAuthorizationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/audit-logs': {
      id: '/_app/security/audit-logs'
      path: '/security/audit-logs'
      fullPath: '/security/audit-logs'
      preLoaderRoute: typeof AppSecurityAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/audit-intelligence': {
      id: '/_app/security/audit-intelligence'
      path: '/security/audit-intelligence'
      fullPath: '/security/audit-intelligence'
      preLoaderRoute: typeof AppSecurityAuditIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/tenants': {
      id: '/_app/organizations/tenants'
      path: '/organizations/tenants'
      fullPath: '/organizations/tenants'
      preLoaderRoute: typeof AppOrganizationsTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/members': {
      id: '/_app/organizations/members'
      path: '/organizations/members'
      fullPath: '/organizations/members'
      preLoaderRoute: typeof AppOrganizationsMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/domains': {
      id: '/_app/organizations/domains'
      path: '/organizations/domains'
      fullPath: '/organizations/domains'
      preLoaderRoute: typeof AppOrganizationsDomainsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/$groupId': {
      id: '/_app/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AppGroupsGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developer/infrastructure': {
      id: '/_app/developer/infrastructure'
      path: '/developer/infrastructure'
      fullPath: '/developer/infrastructure'
      preLoaderRoute: typeof AppDeveloperInfrastructureRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developer/credentials': {
      id: '/_app/developer/credentials'
      path: '/developer/credentials'
      fullPath: '/developer/credentials'
      preLoaderRoute: typeof AppDeveloperCredentialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developer/bots': {
      id: '/_app/developer/bots'
      path: '/developer/bots'
      fullPath: '/developer/bots'
      preLoaderRoute: typeof AppDeveloperBotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developer/auth-hooks': {
      id: '/_app/developer/auth-hooks'
      path: '/developer/auth-hooks'
      fullPath: '/developer/auth-hooks'
      preLoaderRoute: typeof AppDeveloperAuthHooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developer/agents': {
      id: '/_app/developer/agents'
      path: '/developer/agents'
      fullPath: '/developer/agents'
      preLoaderRoute: typeof AppDeveloperAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/authorization/versions': {
      id: '/_app/authorization/versions'
      path: '/authorization/versions'
      fullPath: '/authorization/versions'
      preLoaderRoute: typeof AppAuthorizationVersionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/authorization/templates': {
      id: '/_app/authorization/templates'
      path: '/authorization/templates'
      fullPath: '/authorization/templates'
      preLoaderRoute: typeof AppAuthorizationTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/authorization/simulator': {
      id: '/_app/authorization/simulator'
      path: '/authorization/simulator'
      fullPath: '/authorization/simulator'
      preLoaderRoute: typeof AppAuthorizationSimulatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/authorization/settings': {
      id: '/_app/authorization/settings'
      path: '/authorization/settings'
      fullPath: '/authorization/settings'
      preLoaderRoute: typeof AppAuthorizationSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/authorization/roles': {
      id: '/_app/authorization/roles'
      path: '/authorization/roles'
      fullPath: '/authorization/roles'
      preLoaderRoute: typeof AppAuthorizationRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/authorization/resources': {
      id: '/_app/authorization/resources'
      path: '/authorization/resources'
      fullPath: '/authorization/resources'
      preLoaderRoute: typeof AppAuthorizationResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/authorization/rebac': {
      id: '/_app/authorization/rebac'
      path: '/authorization/rebac'
      fullPath: '/authorization/rebac'
      preLoaderRoute: typeof AppAuthorizationRebacRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/authorization/rbac': {
      id: '/_app/authorization/rbac'
      path: '/authorization/rbac'
      fullPath: '/authorization/rbac'
      preLoaderRoute: typeof AppAuthorizationRbacRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/authorization/permissions': {
      id: '/_app/authorization/permissions'
      path: '/authorization/permissions'
      fullPath: '/authorization/permissions'
      preLoaderRoute: typeof AppAuthorizationPermissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/authorization/explorer': {
      id: '/_app/authorization/explorer'
      path: '/authorization/explorer'
      fullPath: '/authorization/explorer'
      preLoaderRoute: typeof AppAuthorizationExplorerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/authorization/builder': {
      id: '/_app/authorization/builder'
      path: '/authorization/builder'
      fullPath: '/authorization/builder'
      preLoaderRoute: typeof AppAuthorizationBuilderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/authorization/audit': {
      id: '/_app/authorization/audit'
      path: '/authorization/audit'
      fullPath: '/authorization/audit'
      preLoaderRoute: typeof AppAuthorizationAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/authorization/assistant': {
      id: '/_app/authorization/assistant'
      path: '/authorization/assistant'
      fullPath: '/authorization/assistant'
      preLoaderRoute: typeof AppAuthorizationAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/authorization/access-tester': {
      id: '/_app/authorization/access-tester'
      path: '/authorization/access-tester'
      fullPath: '/authorization/access-tester'
      preLoaderRoute: typeof AppAuthorizationAccessTesterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/authorization/abac': {
      id: '/_app/authorization/abac'
      path: '/authorization/abac'
      fullPath: '/authorization/abac'
      preLoaderRoute: typeof AppAuthorizationAbacRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/social': {
      id: '/_app/auth/social'
      path: '/auth/social'
      fullPath: '/auth/social'
      preLoaderRoute: typeof AppAuthSocialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developer/webhooks/': {
      id: '/_app/developer/webhooks/'
      path: '/developer/webhooks'
      fullPath: '/developer/webhooks/'
      preLoaderRoute: typeof AppDeveloperWebhooksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/connections/': {
      id: '/_app/auth/connections/'
      path: '/auth/connections'
      fullPath: '/auth/connections/'
      preLoaderRoute: typeof AppAuthConnectionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/$userId_/timeline': {
      id: '/_app/users/$userId_/timeline'
      path: '/users/$userId/timeline'
      fullPath: '/users/$userId/timeline'
      preLoaderRoute: typeof AppUsersUserIdTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/workspace/security-policy': {
      id: '/_app/settings/workspace/security-policy'
      path: '/settings/workspace/security-policy'
      fullPath: '/settings/workspace/security-policy'
      preLoaderRoute: typeof AppSettingsWorkspaceSecurityPolicyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/workspace/general': {
      id: '/_app/settings/workspace/general'
      path: '/settings/workspace/general'
      fullPath: '/settings/workspace/general'
      preLoaderRoute: typeof AppSettingsWorkspaceGeneralRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/workspace/email-templates': {
      id: '/_app/settings/workspace/email-templates'
      path: '/settings/workspace/email-templates'
      fullPath: '/settings/workspace/email-templates'
      preLoaderRoute: typeof AppSettingsWorkspaceEmailTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/workspace/domains': {
      id: '/_app/settings/workspace/domains'
      path: '/settings/workspace/domains'
      fullPath: '/settings/workspace/domains'
      preLoaderRoute: typeof AppSettingsWorkspaceDomainsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/threats/risk-settings': {
      id: '/_app/security/threats/risk-settings'
      path: '/security/threats/risk-settings'
      fullPath: '/security/threats/risk-settings'
      preLoaderRoute: typeof AppSecurityThreatsRiskSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/threats/rate-limits': {
      id: '/_app/security/threats/rate-limits'
      path: '/security/threats/rate-limits'
      fullPath: '/security/threats/rate-limits'
      preLoaderRoute: typeof AppSecurityThreatsRateLimitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/threats/ip-allowlist': {
      id: '/_app/security/threats/ip-allowlist'
      path: '/security/threats/ip-allowlist'
      fullPath: '/security/threats/ip-allowlist'
      preLoaderRoute: typeof AppSecurityThreatsIpAllowlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/threats/bots': {
      id: '/_app/security/threats/bots'
      path: '/security/threats/bots'
      fullPath: '/security/threats/bots'
      preLoaderRoute: typeof AppSecurityThreatsBotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/threats/anomalies': {
      id: '/_app/security/threats/anomalies'
      path: '/security/threats/anomalies'
      fullPath: '/security/threats/anomalies'
      preLoaderRoute: typeof AppSecurityThreatsAnomaliesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/compliance/soc2': {
      id: '/_app/security/compliance/soc2'
      path: '/security/compliance/soc2'
      fullPath: '/security/compliance/soc2'
      preLoaderRoute: typeof AppSecurityComplianceSoc2RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/compliance/retention': {
      id: '/_app/security/compliance/retention'
      path: '/security/compliance/retention'
      fullPath: '/security/compliance/retention'
      preLoaderRoute: typeof AppSecurityComplianceRetentionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/compliance/iso27001': {
      id: '/_app/security/compliance/iso27001'
      path: '/security/compliance/iso27001'
      fullPath: '/security/compliance/iso27001'
      preLoaderRoute: typeof AppSecurityComplianceIso27001RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/compliance/gdpr': {
      id: '/_app/security/compliance/gdpr'
      path: '/security/compliance/gdpr'
      fullPath: '/security/compliance/gdpr'
      preLoaderRoute: typeof AppSecurityComplianceGdprRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developer/webhooks/$id': {
      id: '/_app/developer/webhooks/$id'
      path: '/developer/webhooks/$id'
      fullPath: '/developer/webhooks/$id'
      preLoaderRoute: typeof AppDeveloperWebhooksIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/mfa/totp': {
      id: '/_app/auth/mfa/totp'
      path: '/auth/mfa/totp'
      fullPath: '/auth/mfa/totp'
      preLoaderRoute: typeof AppAuthMfaTotpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/mfa/sms-email': {
      id: '/_app/auth/mfa/sms-email'
      path: '/auth/mfa/sms-email'
      fullPath: '/auth/mfa/sms-email'
      preLoaderRoute: typeof AppAuthMfaSmsEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/mfa/recovery-codes': {
      id: '/_app/auth/mfa/recovery-codes'
      path: '/auth/mfa/recovery-codes'
      fullPath: '/auth/mfa/recovery-codes'
      preLoaderRoute: typeof AppAuthMfaRecoveryCodesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/login-methods/passwordless': {
      id: '/_app/auth/login-methods/passwordless'
      path: '/auth/login-methods/passwordless'
      fullPath: '/auth/login-methods/passwordless'
      preLoaderRoute: typeof AppAuthLoginMethodsPasswordlessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/login-methods/password': {
      id: '/_app/auth/login-methods/password'
      path: '/auth/login-methods/password'
      fullPath: '/auth/login-methods/password'
      preLoaderRoute: typeof AppAuthLoginMethodsPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/login-methods/passkeys': {
      id: '/_app/auth/login-methods/passkeys'
      path: '/auth/login-methods/passkeys'
      fullPath: '/auth/login-methods/passkeys'
      preLoaderRoute: typeof AppAuthLoginMethodsPasskeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/login-methods/magic-links': {
      id: '/_app/auth/login-methods/magic-links'
      path: '/auth/login-methods/magic-links'
      fullPath: '/auth/login-methods/magic-links'
      preLoaderRoute: typeof AppAuthLoginMethodsMagicLinksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/connections/scim': {
      id: '/_app/auth/connections/scim'
      path: '/auth/connections/scim'
      fullPath: '/auth/connections/scim'
      preLoaderRoute: typeof AppAuthConnectionsScimRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/connections/saml-idp': {
      id: '/_app/auth/connections/saml-idp'
      path: '/auth/connections/saml-idp'
      fullPath: '/auth/connections/saml-idp'
      preLoaderRoute: typeof AppAuthConnectionsSamlIdpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/connections/saml': {
      id: '/_app/auth/connections/saml'
      path: '/auth/connections/saml'
      fullPath: '/auth/connections/saml'
      preLoaderRoute: typeof AppAuthConnectionsSamlRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/connections/ldap': {
      id: '/_app/auth/connections/ldap'
      path: '/auth/connections/ldap'
      fullPath: '/auth/connections/ldap'
      preLoaderRoute: typeof AppAuthConnectionsLdapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/api/tokens': {
      id: '/_app/auth/api/tokens'
      path: '/auth/api/tokens'
      fullPath: '/auth/api/tokens'
      preLoaderRoute: typeof AppAuthApiTokensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/api/signing-keys': {
      id: '/_app/auth/api/signing-keys'
      path: '/auth/api/signing-keys'
      fullPath: '/auth/api/signing-keys'
      preLoaderRoute: typeof AppAuthApiSigningKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/api/secrets': {
      id: '/_app/auth/api/secrets'
      path: '/auth/api/secrets'
      fullPath: '/auth/api/secrets'
      preLoaderRoute: typeof AppAuthApiSecretsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/api/machine-identities': {
      id: '/_app/auth/api/machine-identities'
      path: '/auth/api/machine-identities'
      fullPath: '/auth/api/machine-identities'
      preLoaderRoute: typeof AppAuthApiMachineIdentitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/api/keys': {
      id: '/_app/auth/api/keys'
      path: '/auth/api/keys'
      fullPath: '/auth/api/keys'
      preLoaderRoute: typeof AppAuthApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/api/consent-grants': {
      id: '/_app/auth/api/consent-grants'
      path: '/auth/api/consent-grants'
      fullPath: '/auth/api/consent-grants'
      preLoaderRoute: typeof AppAuthApiConsentGrantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/connections/oidc/': {
      id: '/_app/auth/connections/oidc/'
      path: '/auth/connections/oidc'
      fullPath: '/auth/connections/oidc/'
      preLoaderRoute: typeof AppAuthConnectionsOidcIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/connections/oidc/$clientId': {
      id: '/_app/auth/connections/oidc/$clientId'
      path: '/auth/connections/oidc/$clientId'
      fullPath: '/auth/connections/oidc/$clientId'
      preLoaderRoute: typeof AppAuthConnectionsOidcClientIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppActivityRoute: typeof AppActivityRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppInvitationsRoute: typeof AppInvitationsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAuthSocialRoute: typeof AppAuthSocialRoute
  AppAuthorizationAbacRoute: typeof AppAuthorizationAbacRoute
  AppAuthorizationAccessTesterRoute: typeof AppAuthorizationAccessTesterRoute
  AppAuthorizationAssistantRoute: typeof AppAuthorizationAssistantRoute
  AppAuthorizationAuditRoute: typeof AppAuthorizationAuditRoute
  AppAuthorizationBuilderRoute: typeof AppAuthorizationBuilderRoute
  AppAuthorizationExplorerRoute: typeof AppAuthorizationExplorerRoute
  AppAuthorizationPermissionsRoute: typeof AppAuthorizationPermissionsRoute
  AppAuthorizationRbacRoute: typeof AppAuthorizationRbacRoute
  AppAuthorizationRebacRoute: typeof AppAuthorizationRebacRoute
  AppAuthorizationResourcesRoute: typeof AppAuthorizationResourcesRoute
  AppAuthorizationRolesRoute: typeof AppAuthorizationRolesRoute
  AppAuthorizationSettingsRoute: typeof AppAuthorizationSettingsRoute
  AppAuthorizationSimulatorRoute: typeof AppAuthorizationSimulatorRoute
  AppAuthorizationTemplatesRoute: typeof AppAuthorizationTemplatesRoute
  AppAuthorizationVersionsRoute: typeof AppAuthorizationVersionsRoute
  AppDeveloperAgentsRoute: typeof AppDeveloperAgentsRoute
  AppDeveloperAuthHooksRoute: typeof AppDeveloperAuthHooksRoute
  AppDeveloperBotsRoute: typeof AppDeveloperBotsRoute
  AppDeveloperCredentialsRoute: typeof AppDeveloperCredentialsRoute
  AppDeveloperInfrastructureRoute: typeof AppDeveloperInfrastructureRoute
  AppGroupsGroupIdRoute: typeof AppGroupsGroupIdRoute
  AppOrganizationsDomainsRoute: typeof AppOrganizationsDomainsRoute
  AppOrganizationsMembersRoute: typeof AppOrganizationsMembersRoute
  AppOrganizationsTenantsRoute: typeof AppOrganizationsTenantsRoute
  AppSecurityAuditIntelligenceRoute: typeof AppSecurityAuditIntelligenceRoute
  AppSecurityAuditLogsRoute: typeof AppSecurityAuditLogsRoute
  AppSecurityDeviceAuthorizationsRoute: typeof AppSecurityDeviceAuthorizationsRoute
  AppSecurityLogStreamingRoute: typeof AppSecurityLogStreamingRoute
  AppSecurityRateLimitsRoute: typeof AppSecurityRateLimitsRoute
  AppSecuritySessionsRoute: typeof AppSecuritySessionsRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsBrandingRoute: typeof AppSettingsBrandingRoute
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppUsersDeletedRoute: typeof AppUsersDeletedRoute
  AppUsersImportRoute: typeof AppUsersImportRoute
  AppUsersInvitationsRoute: typeof AppUsersInvitationsRoute
  AppUsersSessionsRoute: typeof AppUsersSessionsRoute
  AppAuthorizationIndexRoute: typeof AppAuthorizationIndexRoute
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
  AppSecurityIndexRoute: typeof AppSecurityIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppAuthApiConsentGrantsRoute: typeof AppAuthApiConsentGrantsRoute
  AppAuthApiKeysRoute: typeof AppAuthApiKeysRoute
  AppAuthApiMachineIdentitiesRoute: typeof AppAuthApiMachineIdentitiesRoute
  AppAuthApiSecretsRoute: typeof AppAuthApiSecretsRoute
  AppAuthApiSigningKeysRoute: typeof AppAuthApiSigningKeysRoute
  AppAuthApiTokensRoute: typeof AppAuthApiTokensRoute
  AppAuthConnectionsLdapRoute: typeof AppAuthConnectionsLdapRoute
  AppAuthConnectionsSamlRoute: typeof AppAuthConnectionsSamlRoute
  AppAuthConnectionsSamlIdpRoute: typeof AppAuthConnectionsSamlIdpRoute
  AppAuthConnectionsScimRoute: typeof AppAuthConnectionsScimRoute
  AppAuthLoginMethodsMagicLinksRoute: typeof AppAuthLoginMethodsMagicLinksRoute
  AppAuthLoginMethodsPasskeysRoute: typeof AppAuthLoginMethodsPasskeysRoute
  AppAuthLoginMethodsPasswordRoute: typeof AppAuthLoginMethodsPasswordRoute
  AppAuthLoginMethodsPasswordlessRoute: typeof AppAuthLoginMethodsPasswordlessRoute
  AppAuthMfaRecoveryCodesRoute: typeof AppAuthMfaRecoveryCodesRoute
  AppAuthMfaSmsEmailRoute: typeof AppAuthMfaSmsEmailRoute
  AppAuthMfaTotpRoute: typeof AppAuthMfaTotpRoute
  AppDeveloperWebhooksIdRoute: typeof AppDeveloperWebhooksIdRoute
  AppSecurityComplianceGdprRoute: typeof AppSecurityComplianceGdprRoute
  AppSecurityComplianceIso27001Route: typeof AppSecurityComplianceIso27001Route
  AppSecurityComplianceRetentionRoute: typeof AppSecurityComplianceRetentionRoute
  AppSecurityComplianceSoc2Route: typeof AppSecurityComplianceSoc2Route
  AppSecurityThreatsAnomaliesRoute: typeof AppSecurityThreatsAnomaliesRoute
  AppSecurityThreatsBotsRoute: typeof AppSecurityThreatsBotsRoute
  AppSecurityThreatsIpAllowlistRoute: typeof AppSecurityThreatsIpAllowlistRoute
  AppSecurityThreatsRateLimitsRoute: typeof AppSecurityThreatsRateLimitsRoute
  AppSecurityThreatsRiskSettingsRoute: typeof AppSecurityThreatsRiskSettingsRoute
  AppSettingsWorkspaceDomainsRoute: typeof AppSettingsWorkspaceDomainsRoute
  AppSettingsWorkspaceEmailTemplatesRoute: typeof AppSettingsWorkspaceEmailTemplatesRoute
  AppSettingsWorkspaceGeneralRoute: typeof AppSettingsWorkspaceGeneralRoute
  AppSettingsWorkspaceSecurityPolicyRoute: typeof AppSettingsWorkspaceSecurityPolicyRoute
  AppUsersUserIdTimelineRoute: typeof AppUsersUserIdTimelineRoute
  AppAuthConnectionsIndexRoute: typeof AppAuthConnectionsIndexRoute
  AppDeveloperWebhooksIndexRoute: typeof AppDeveloperWebhooksIndexRoute
  AppAuthConnectionsOidcClientIdRoute: typeof AppAuthConnectionsOidcClientIdRoute
  AppAuthConnectionsOidcIndexRoute: typeof AppAuthConnectionsOidcIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppActivityRoute: AppActivityRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppInvitationsRoute: AppInvitationsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAuthSocialRoute: AppAuthSocialRoute,
  AppAuthorizationAbacRoute: AppAuthorizationAbacRoute,
  AppAuthorizationAccessTesterRoute: AppAuthorizationAccessTesterRoute,
  AppAuthorizationAssistantRoute: AppAuthorizationAssistantRoute,
  AppAuthorizationAuditRoute: AppAuthorizationAuditRoute,
  AppAuthorizationBuilderRoute: AppAuthorizationBuilderRoute,
  AppAuthorizationExplorerRoute: AppAuthorizationExplorerRoute,
  AppAuthorizationPermissionsRoute: AppAuthorizationPermissionsRoute,
  AppAuthorizationRbacRoute: AppAuthorizationRbacRoute,
  AppAuthorizationRebacRoute: AppAuthorizationRebacRoute,
  AppAuthorizationResourcesRoute: AppAuthorizationResourcesRoute,
  AppAuthorizationRolesRoute: AppAuthorizationRolesRoute,
  AppAuthorizationSettingsRoute: AppAuthorizationSettingsRoute,
  AppAuthorizationSimulatorRoute: AppAuthorizationSimulatorRoute,
  AppAuthorizationTemplatesRoute: AppAuthorizationTemplatesRoute,
  AppAuthorizationVersionsRoute: AppAuthorizationVersionsRoute,
  AppDeveloperAgentsRoute: AppDeveloperAgentsRoute,
  AppDeveloperAuthHooksRoute: AppDeveloperAuthHooksRoute,
  AppDeveloperBotsRoute: AppDeveloperBotsRoute,
  AppDeveloperCredentialsRoute: AppDeveloperCredentialsRoute,
  AppDeveloperInfrastructureRoute: AppDeveloperInfrastructureRoute,
  AppGroupsGroupIdRoute: AppGroupsGroupIdRoute,
  AppOrganizationsDomainsRoute: AppOrganizationsDomainsRoute,
  AppOrganizationsMembersRoute: AppOrganizationsMembersRoute,
  AppOrganizationsTenantsRoute: AppOrganizationsTenantsRoute,
  AppSecurityAuditIntelligenceRoute: AppSecurityAuditIntelligenceRoute,
  AppSecurityAuditLogsRoute: AppSecurityAuditLogsRoute,
  AppSecurityDeviceAuthorizationsRoute: AppSecurityDeviceAuthorizationsRoute,
  AppSecurityLogStreamingRoute: AppSecurityLogStreamingRoute,
  AppSecurityRateLimitsRoute: AppSecurityRateLimitsRoute,
  AppSecuritySessionsRoute: AppSecuritySessionsRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsBrandingRoute: AppSettingsBrandingRoute,
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppUsersDeletedRoute: AppUsersDeletedRoute,
  AppUsersImportRoute: AppUsersImportRoute,
  AppUsersInvitationsRoute: AppUsersInvitationsRoute,
  AppUsersSessionsRoute: AppUsersSessionsRoute,
  AppAuthorizationIndexRoute: AppAuthorizationIndexRoute,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
  AppSecurityIndexRoute: AppSecurityIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppAuthApiConsentGrantsRoute: AppAuthApiConsentGrantsRoute,
  AppAuthApiKeysRoute: AppAuthApiKeysRoute,
  AppAuthApiMachineIdentitiesRoute: AppAuthApiMachineIdentitiesRoute,
  AppAuthApiSecretsRoute: AppAuthApiSecretsRoute,
  AppAuthApiSigningKeysRoute: AppAuthApiSigningKeysRoute,
  AppAuthApiTokensRoute: AppAuthApiTokensRoute,
  AppAuthConnectionsLdapRoute: AppAuthConnectionsLdapRoute,
  AppAuthConnectionsSamlRoute: AppAuthConnectionsSamlRoute,
  AppAuthConnectionsSamlIdpRoute: AppAuthConnectionsSamlIdpRoute,
  AppAuthConnectionsScimRoute: AppAuthConnectionsScimRoute,
  AppAuthLoginMethodsMagicLinksRoute: AppAuthLoginMethodsMagicLinksRoute,
  AppAuthLoginMethodsPasskeysRoute: AppAuthLoginMethodsPasskeysRoute,
  AppAuthLoginMethodsPasswordRoute: AppAuthLoginMethodsPasswordRoute,
  AppAuthLoginMethodsPasswordlessRoute: AppAuthLoginMethodsPasswordlessRoute,
  AppAuthMfaRecoveryCodesRoute: AppAuthMfaRecoveryCodesRoute,
  AppAuthMfaSmsEmailRoute: AppAuthMfaSmsEmailRoute,
  AppAuthMfaTotpRoute: AppAuthMfaTotpRoute,
  AppDeveloperWebhooksIdRoute: AppDeveloperWebhooksIdRoute,
  AppSecurityComplianceGdprRoute: AppSecurityComplianceGdprRoute,
  AppSecurityComplianceIso27001Route: AppSecurityComplianceIso27001Route,
  AppSecurityComplianceRetentionRoute: AppSecurityComplianceRetentionRoute,
  AppSecurityComplianceSoc2Route: AppSecurityComplianceSoc2Route,
  AppSecurityThreatsAnomaliesRoute: AppSecurityThreatsAnomaliesRoute,
  AppSecurityThreatsBotsRoute: AppSecurityThreatsBotsRoute,
  AppSecurityThreatsIpAllowlistRoute: AppSecurityThreatsIpAllowlistRoute,
  AppSecurityThreatsRateLimitsRoute: AppSecurityThreatsRateLimitsRoute,
  AppSecurityThreatsRiskSettingsRoute: AppSecurityThreatsRiskSettingsRoute,
  AppSettingsWorkspaceDomainsRoute: AppSettingsWorkspaceDomainsRoute,
  AppSettingsWorkspaceEmailTemplatesRoute:
    AppSettingsWorkspaceEmailTemplatesRoute,
  AppSettingsWorkspaceGeneralRoute: AppSettingsWorkspaceGeneralRoute,
  AppSettingsWorkspaceSecurityPolicyRoute:
    AppSettingsWorkspaceSecurityPolicyRoute,
  AppUsersUserIdTimelineRoute: AppUsersUserIdTimelineRoute,
  AppAuthConnectionsIndexRoute: AppAuthConnectionsIndexRoute,
  AppDeveloperWebhooksIndexRoute: AppDeveloperWebhooksIndexRoute,
  AppAuthConnectionsOidcClientIdRoute: AppAuthConnectionsOidcClientIdRoute,
  AppAuthConnectionsOidcIndexRoute: AppAuthConnectionsOidcIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthMagicRoute: typeof AuthMagicRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthInviteAcceptRoute: typeof AuthInviteAcceptRoute
  AuthSsoCallbackRoute: typeof AuthSsoCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthMagicRoute: AuthMagicRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthInviteAcceptRoute: AuthInviteAcceptRoute,
  AuthSsoCallbackRoute: AuthSsoCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AccountRouteChildren {
  AccountDataRoute: typeof AccountDataRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountSessionsRoute: typeof AccountSessionsRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountDataRoute: AccountDataRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountSessionsRoute: AccountSessionsRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
