// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignRoleToGroup = `-- name: AssignRoleToGroup :one
WITH ins AS (
    INSERT INTO rbac.group_roles (tenant_id, group_id, role_id, granted_by)
    SELECT $3, $1, $2, $4
    WHERE EXISTS (SELECT 1 FROM tenant.groups g WHERE g.id = $1 AND g.tenant_id = $3)
      AND EXISTS (SELECT 1 FROM rbac.roles ro WHERE ro.id = $2 AND ro.tenant_id = $3)
    ON CONFLICT DO NOTHING
    RETURNING 1
)
SELECT (
    EXISTS (SELECT 1 FROM ins)
    OR EXISTS (SELECT 1 FROM rbac.group_roles existing WHERE existing.group_id = $1 AND existing.role_id = $2 AND existing.tenant_id = $3)
) AS valid
`

type AssignRoleToGroupParams struct {
	GroupID   uuid.UUID
	RoleID    uuid.UUID
	TenantID  uuid.UUID
	GrantedBy pgtype.UUID
}

func (q *Queries) AssignRoleToGroup(ctx context.Context, arg AssignRoleToGroupParams) (*bool, error) {
	row := q.db.QueryRow(ctx, assignRoleToGroup,
		arg.GroupID,
		arg.RoleID,
		arg.TenantID,
		arg.GrantedBy,
	)
	var valid *bool
	err := row.Scan(&valid)
	return valid, err
}

const assignUserRole = `-- name: AssignUserRole :exec
INSERT INTO rbac.user_roles (user_id, tenant_id, role_id, granted_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type AssignUserRoleParams struct {
	UserID    uuid.UUID
	TenantID  uuid.UUID
	RoleID    uuid.UUID
	GrantedBy pgtype.UUID
}

func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error {
	_, err := q.db.Exec(ctx, assignUserRole,
		arg.UserID,
		arg.TenantID,
		arg.RoleID,
		arg.GrantedBy,
	)
	return err
}

const checkPermission = `-- name: CheckPermission :one
SELECT EXISTS (
    SELECT 1
    FROM rbac.user_roles ur
    JOIN rbac.role_permissions rp ON rp.role_id = ur.role_id
    JOIN rbac.permissions p ON p.id = rp.permission_id
    WHERE ur.user_id = $1 AND ur.tenant_id = $2 AND p.key = $3
    UNION ALL
    SELECT 1
    FROM tenant.group_members gm
    JOIN rbac.group_roles gr ON gr.group_id = gm.group_id AND gr.tenant_id = gm.tenant_id
    JOIN rbac.role_permissions rp ON rp.role_id = gr.role_id
    JOIN rbac.permissions p ON p.id = rp.permission_id
    WHERE gm.user_id = $1 AND gm.tenant_id = $2 AND p.key = $3
) AS allowed
`

type CheckPermissionParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
	PermKey  string
}

func (q *Queries) CheckPermission(ctx context.Context, arg CheckPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkPermission, arg.UserID, arg.TenantID, arg.PermKey)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO rbac.roles (tenant_id, name, description, is_system)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name, description, is_system, created_at
`

type CreateRoleParams struct {
	TenantID    uuid.UUID
	Name        string
	Description string
	IsSystem    bool
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (RbacRole, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.IsSystem,
	)
	var i RbacRole
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const explainGrants = `-- name: ExplainGrants :many
SELECT 'direct'::text AS via, NULL::uuid AS group_id, NULL::text AS group_name, ro.id AS role_id, ro.name AS role_name
FROM rbac.user_roles ur
JOIN rbac.roles ro ON ro.id = ur.role_id
JOIN rbac.role_permissions rp ON rp.role_id = ur.role_id
JOIN rbac.permissions p ON p.id = rp.permission_id
WHERE ur.user_id = $1 AND ur.tenant_id = $2 AND p.key = $3
UNION ALL
SELECT 'group'::text AS via, g.id AS group_id, g.name AS group_name, ro.id AS role_id, ro.name AS role_name
FROM tenant.group_members gm
JOIN tenant.groups g ON g.id = gm.group_id AND g.tenant_id = gm.tenant_id
JOIN rbac.group_roles gr ON gr.group_id = gm.group_id AND gr.tenant_id = gm.tenant_id
JOIN rbac.roles ro ON ro.id = gr.role_id
JOIN rbac.role_permissions rp ON rp.role_id = gr.role_id
JOIN rbac.permissions p ON p.id = rp.permission_id
WHERE gm.user_id = $1 AND gm.tenant_id = $2 AND p.key = $3
ORDER BY via, group_name NULLS FIRST
`

type ExplainGrantsParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
	PermKey  string
}

type ExplainGrantsRow struct {
	Via       string
	GroupID   pgtype.UUID
	GroupName *string
	RoleID    uuid.UUID
	RoleName  string
}

func (q *Queries) ExplainGrants(ctx context.Context, arg ExplainGrantsParams) ([]ExplainGrantsRow, error) {
	rows, err := q.db.Query(ctx, explainGrants, arg.UserID, arg.TenantID, arg.PermKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExplainGrantsRow{}
	for rows.Next() {
		var i ExplainGrantsRow
		if err := rows.Scan(
			&i.Via,
			&i.GroupID,
			&i.GroupName,
			&i.RoleID,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleTenant = `-- name: GetRoleTenant :one
SELECT tenant_id FROM rbac.roles WHERE id = $1
`

func (q *Queries) GetRoleTenant(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getRoleTenant, id)
	var tenant_id uuid.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}

const grantPermission = `-- name: GrantPermission :exec
INSERT INTO rbac.role_permissions (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type GrantPermissionParams struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

func (q *Queries) GrantPermission(ctx context.Context, arg GrantPermissionParams) error {
	_, err := q.db.Exec(ctx, grantPermission, arg.RoleID, arg.PermissionID)
	return err
}

const listEffectivePermissions = `-- name: ListEffectivePermissions :many
SELECT p.key
FROM rbac.user_roles ur
JOIN rbac.role_permissions rp ON rp.role_id = ur.role_id
JOIN rbac.permissions p ON p.id = rp.permission_id
WHERE ur.user_id = $1 AND ur.tenant_id = $2
UNION
SELECT p.key
FROM tenant.group_members gm
JOIN rbac.group_roles gr ON gr.group_id = gm.group_id AND gr.tenant_id = gm.tenant_id
JOIN rbac.role_permissions rp ON rp.role_id = gr.role_id
JOIN rbac.permissions p ON p.id = rp.permission_id
WHERE gm.user_id = $1 AND gm.tenant_id = $2
ORDER BY key
`

type ListEffectivePermissionsParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) ListEffectivePermissions(ctx context.Context, arg ListEffectivePermissionsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listEffectivePermissions, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupRoles = `-- name: ListGroupRoles :many
SELECT gr.role_id, ro.name, gr.granted_at
FROM rbac.group_roles gr
JOIN rbac.roles ro ON ro.id = gr.role_id
WHERE gr.group_id = $1 AND gr.tenant_id = $2
ORDER BY ro.name
`

type ListGroupRolesParams struct {
	GroupID  uuid.UUID
	TenantID uuid.UUID
}

type ListGroupRolesRow struct {
	RoleID    uuid.UUID
	Name      string
	GrantedAt time.Time
}

func (q *Queries) ListGroupRoles(ctx context.Context, arg ListGroupRolesParams) ([]ListGroupRolesRow, error) {
	rows, err := q.db.Query(ctx, listGroupRoles, arg.GroupID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupRolesRow{}
	for rows.Next() {
		var i ListGroupRolesRow
		if err := rows.Scan(&i.RoleID, &i.Name, &i.GrantedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, key, description FROM rbac.permissions ORDER BY key
`

func (q *Queries) ListPermissions(ctx context.Context) ([]RbacPermission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RbacPermission{}
	for rows.Next() {
		var i RbacPermission
		if err := rows.Scan(&i.ID, &i.Key, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT p.id, p.key, p.description
FROM rbac.permissions p
JOIN rbac.role_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = $1
ORDER BY p.key
`

func (q *Queries) ListRolePermissions(ctx context.Context, roleID uuid.UUID) ([]RbacPermission, error) {
	rows, err := q.db.Query(ctx, listRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RbacPermission{}
	for rows.Next() {
		var i RbacPermission
		if err := rows.Scan(&i.ID, &i.Key, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, tenant_id, name, description, is_system, created_at
FROM rbac.roles
WHERE tenant_id = $1
ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context, tenantID uuid.UUID) ([]RbacRole, error) {
	rows, err := q.db.Query(ctx, listRoles, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RbacRole{}
	for rows.Next() {
		var i RbacRole
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleFromGroup = `-- name: RemoveRoleFromGroup :exec
DELETE FROM rbac.group_roles WHERE group_id = $1 AND tenant_id = $2 AND role_id = $3
`

type RemoveRoleFromGroupParams struct {
	GroupID  uuid.UUID
	TenantID uuid.UUID
	RoleID   uuid.UUID
}

func (q *Queries) RemoveRoleFromGroup(ctx context.Context, arg RemoveRoleFromGroupParams) error {
	_, err := q.db.Exec(ctx, removeRoleFromGroup, arg.GroupID, arg.TenantID, arg.RoleID)
	return err
}

const revokePermission = `-- name: RevokePermission :exec
DELETE FROM rbac.role_permissions WHERE role_id = $1 AND permission_id = $2
`

type RevokePermissionParams struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

func (q *Queries) RevokePermission(ctx context.Context, arg RevokePermissionParams) error {
	_, err := q.db.Exec(ctx, revokePermission, arg.RoleID, arg.PermissionID)
	return err
}

const unassignUserRole = `-- name: UnassignUserRole :exec
DELETE FROM rbac.user_roles WHERE user_id = $1 AND tenant_id = $2 AND role_id = $3
`

type UnassignUserRoleParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
	RoleID   uuid.UUID
}

func (q *Queries) UnassignUserRole(ctx context.Context, arg UnassignUserRoleParams) error {
	_, err := q.db.Exec(ctx, unassignUserRole, arg.UserID, arg.TenantID, arg.RoleID)
	return err
}

const upsertPermission = `-- name: UpsertPermission :one

INSERT INTO rbac.permissions (key, description)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET description = EXCLUDED.description
RETURNING id, key, description
`

type UpsertPermissionParams struct {
	Key         string
	Description string
}

// Queries for the rbac domain. All queries are sqlc-generated, including the two
// awkward ones: AssignRoleToGroup (a conditional CTE INSERT whose RETURNING is
// folded into an EXISTS check, returning a single bool) and ExplainGrants (a
// two-armed UNION ALL with typed NULL columns for the direct arm).
func (q *Queries) UpsertPermission(ctx context.Context, arg UpsertPermissionParams) (RbacPermission, error) {
	row := q.db.QueryRow(ctx, upsertPermission, arg.Key, arg.Description)
	var i RbacPermission
	err := row.Scan(&i.ID, &i.Key, &i.Description)
	return i, err
}
