// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCredential = `-- name: CreateCredential :one

INSERT INTO auth.credentials (tenant_id, subject, type, claims, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, issued_at
`

type CreateCredentialParams struct {
	TenantID  uuid.UUID
	Subject   string
	Type      string
	Claims    []byte
	ExpiresAt pgtype.Timestamptz
}

type CreateCredentialRow struct {
	ID       uuid.UUID
	IssuedAt time.Time
}

// Queries for the Verifiable Credentials domain.
// All queries are static; signing/verification logic stays in the Service layer.
func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (CreateCredentialRow, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.TenantID,
		arg.Subject,
		arg.Type,
		arg.Claims,
		arg.ExpiresAt,
	)
	var i CreateCredentialRow
	err := row.Scan(&i.ID, &i.IssuedAt)
	return i, err
}

const getCredentialRevocation = `-- name: GetCredentialRevocation :one
SELECT revoked_at FROM auth.credentials WHERE id = $1
`

// GetCredentialRevocation checks the revocation registry for a presented
// JWT-VC (jti = credential id). Absent record is treated as valid by the caller.
func (q *Queries) GetCredentialRevocation(ctx context.Context, id uuid.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getCredentialRevocation, id)
	var revoked_at pgtype.Timestamptz
	err := row.Scan(&revoked_at)
	return revoked_at, err
}

const listCredentials = `-- name: ListCredentials :many
SELECT id, subject, type, issued_at, expires_at, revoked_at
FROM auth.credentials WHERE tenant_id = $1 ORDER BY issued_at DESC LIMIT 200
`

type ListCredentialsRow struct {
	ID        uuid.UUID
	Subject   string
	Type      string
	IssuedAt  time.Time
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) ListCredentials(ctx context.Context, tenantID uuid.UUID) ([]ListCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listCredentials, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCredentialsRow{}
	for rows.Next() {
		var i ListCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Type,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCredential = `-- name: RevokeCredential :execrows
UPDATE auth.credentials SET revoked_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND revoked_at IS NULL
`

type RevokeCredentialParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) RevokeCredential(ctx context.Context, arg RevokeCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeCredential, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
