// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGroup = `-- name: DeleteGroup :one
DELETE FROM tenant.groups WHERE id = $1 AND tenant_id = $2 RETURNING name
`

type DeleteGroupParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteGroup, arg.ID, arg.TenantID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const deleteGroupMember = `-- name: DeleteGroupMember :exec
DELETE FROM tenant.group_members
WHERE group_id = $1 AND user_id = $2 AND tenant_id = $3
`

type DeleteGroupMemberParams struct {
	GroupID  uuid.UUID
	UserID   uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteGroupMember(ctx context.Context, arg DeleteGroupMemberParams) error {
	_, err := q.db.Exec(ctx, deleteGroupMember, arg.GroupID, arg.UserID, arg.TenantID)
	return err
}

const groupExists = `-- name: GroupExists :one
SELECT EXISTS(SELECT 1 FROM tenant.groups WHERE id = $1 AND tenant_id = $2)
`

type GroupExistsParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GroupExists(ctx context.Context, arg GroupExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, groupExists, arg.ID, arg.TenantID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertGroup = `-- name: InsertGroup :one

INSERT INTO tenant.groups (tenant_id, parent_id, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, parent_id, name, description, created_at
`

type InsertGroupParams struct {
	TenantID    uuid.UUID
	ParentID    pgtype.UUID
	Name        string
	Description string
}

type InsertGroupRow struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	ParentID    pgtype.UUID
	Name        string
	Description string
	CreatedAt   time.Time
}

// Queries for the groups domain.
// All queries are static; audit.Record and outbox.Enqueue cross-context calls
// stay hand-written on the same pgx.Tx.
func (q *Queries) InsertGroup(ctx context.Context, arg InsertGroupParams) (InsertGroupRow, error) {
	row := q.db.QueryRow(ctx, insertGroup,
		arg.TenantID,
		arg.ParentID,
		arg.Name,
		arg.Description,
	)
	var i InsertGroupRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const insertGroupMember = `-- name: InsertGroupMember :exec
INSERT INTO tenant.group_members (group_id, user_id, tenant_id)
VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type InsertGroupMemberParams struct {
	GroupID  uuid.UUID
	UserID   uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) InsertGroupMember(ctx context.Context, arg InsertGroupMemberParams) error {
	_, err := q.db.Exec(ctx, insertGroupMember, arg.GroupID, arg.UserID, arg.TenantID)
	return err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT gm.user_id, u.email, u.display_name
FROM tenant.group_members gm
JOIN "user".users u ON u.id = gm.user_id
WHERE gm.group_id = $1 AND gm.tenant_id = $2 AND u.deleted_at IS NULL
ORDER BY u.email
`

type ListGroupMembersParams struct {
	GroupID  uuid.UUID
	TenantID uuid.UUID
}

type ListGroupMembersRow struct {
	UserID      uuid.UUID
	Email       string
	DisplayName *string
}

func (q *Queries) ListGroupMembers(ctx context.Context, arg ListGroupMembersParams) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, arg.GroupID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupMembersRow{}
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(&i.UserID, &i.Email, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, tenant_id, parent_id, name, description, created_at
FROM tenant.groups WHERE tenant_id = $1 ORDER BY name
`

type ListGroupsRow struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	ParentID    pgtype.UUID
	Name        string
	Description string
	CreatedAt   time.Time
}

func (q *Queries) ListGroups(ctx context.Context, tenantID uuid.UUID) ([]ListGroupsRow, error) {
	rows, err := q.db.Query(ctx, listGroups, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupsRow{}
	for rows.Next() {
		var i ListGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE tenant.groups
SET name = $1, description = $2, parent_id = $3
WHERE id = $4 AND tenant_id = $5
RETURNING id, tenant_id, parent_id, name, description, created_at
`

type UpdateGroupParams struct {
	Name        string
	Description string
	ParentID    pgtype.UUID
	ID          uuid.UUID
	TenantID    uuid.UUID
}

type UpdateGroupRow struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	ParentID    pgtype.UUID
	Name        string
	Description string
	CreatedAt   time.Time
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (UpdateGroupRow, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.Name,
		arg.Description,
		arg.ParentID,
		arg.ID,
		arg.TenantID,
	)
	var i UpdateGroupRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
