// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestEmailVerification = `-- name: GetLatestEmailVerification :one
SELECT id, expires_at, used_at
FROM "user".email_verifications
WHERE user_id = $1 AND code_hash = $2
ORDER BY created_at DESC
LIMIT 1
FOR UPDATE
`

type GetLatestEmailVerificationParams struct {
	UserID   uuid.UUID
	CodeHash string
}

type GetLatestEmailVerificationRow struct {
	ID        uuid.UUID
	ExpiresAt time.Time
	UsedAt    pgtype.Timestamptz
}

// GetLatestEmailVerification selects the most-recent verification row for the
// given user + code and locks it for update so concurrent Confirm calls don't race.
func (q *Queries) GetLatestEmailVerification(ctx context.Context, arg GetLatestEmailVerificationParams) (GetLatestEmailVerificationRow, error) {
	row := q.db.QueryRow(ctx, getLatestEmailVerification, arg.UserID, arg.CodeHash)
	var i GetLatestEmailVerificationRow
	err := row.Scan(&i.ID, &i.ExpiresAt, &i.UsedAt)
	return i, err
}

const getLatestPhoneVerification = `-- name: GetLatestPhoneVerification :one
SELECT id, expires_at, used_at
FROM "user".phone_verifications
WHERE user_id = $1 AND code_hash = $2
ORDER BY created_at DESC
LIMIT 1
FOR UPDATE
`

type GetLatestPhoneVerificationParams struct {
	UserID   uuid.UUID
	CodeHash string
}

type GetLatestPhoneVerificationRow struct {
	ID        uuid.UUID
	ExpiresAt time.Time
	UsedAt    pgtype.Timestamptz
}

func (q *Queries) GetLatestPhoneVerification(ctx context.Context, arg GetLatestPhoneVerificationParams) (GetLatestPhoneVerificationRow, error) {
	row := q.db.QueryRow(ctx, getLatestPhoneVerification, arg.UserID, arg.CodeHash)
	var i GetLatestPhoneVerificationRow
	err := row.Scan(&i.ID, &i.ExpiresAt, &i.UsedAt)
	return i, err
}

const getUserEmail = `-- name: GetUserEmail :one

SELECT email FROM "user".users WHERE id = $1
`

// Queries for the verification domain.
// All queries are static. Queries that touch "user".users are cross-schema reads
// that are acceptable here (verification is a "user" subdomain and needs the address
// on file). audit/outbox are not involved in this domain.
// GetUserEmail fetches the email address for the given user (used by StartEmail
// when the caller omits the address so we default to the one on file).
func (q *Queries) GetUserEmail(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserEmail, id)
	var email string
	err := row.Scan(&email)
	return email, err
}

const getUserPhone = `-- name: GetUserPhone :one
SELECT phone FROM "user".users WHERE id = $1
`

// GetUserPhone fetches the phone number for the given user (used by StartPhone
// when the caller omits the number).
func (q *Queries) GetUserPhone(ctx context.Context, id uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getUserPhone, id)
	var phone *string
	err := row.Scan(&phone)
	return phone, err
}

const insertEmailVerification = `-- name: InsertEmailVerification :exec
INSERT INTO "user".email_verifications (user_id, email, code_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertEmailVerificationParams struct {
	UserID    uuid.UUID
	Email     string
	CodeHash  string
	ExpiresAt time.Time
}

func (q *Queries) InsertEmailVerification(ctx context.Context, arg InsertEmailVerificationParams) error {
	_, err := q.db.Exec(ctx, insertEmailVerification,
		arg.UserID,
		arg.Email,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	return err
}

const insertPhoneVerification = `-- name: InsertPhoneVerification :exec
INSERT INTO "user".phone_verifications (user_id, phone, code_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertPhoneVerificationParams struct {
	UserID    uuid.UUID
	Phone     string
	CodeHash  string
	ExpiresAt time.Time
}

func (q *Queries) InsertPhoneVerification(ctx context.Context, arg InsertPhoneVerificationParams) error {
	_, err := q.db.Exec(ctx, insertPhoneVerification,
		arg.UserID,
		arg.Phone,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	return err
}

const markEmailVerificationUsed = `-- name: MarkEmailVerificationUsed :exec
UPDATE "user".email_verifications SET used_at = NOW() WHERE id = $1
`

func (q *Queries) MarkEmailVerificationUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerificationUsed, id)
	return err
}

const markPhoneVerificationUsed = `-- name: MarkPhoneVerificationUsed :exec
UPDATE "user".phone_verifications SET used_at = NOW() WHERE id = $1
`

func (q *Queries) MarkPhoneVerificationUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPhoneVerificationUsed, id)
	return err
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :exec
UPDATE "user".users
SET email_verified_at = COALESCE(email_verified_at, NOW()), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkUserEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markUserEmailVerified, id)
	return err
}

const markUserPhoneVerified = `-- name: MarkUserPhoneVerified :exec
UPDATE "user".users
SET phone_verified_at = COALESCE(phone_verified_at, NOW()), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkUserPhoneVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markUserPhoneVerified, id)
	return err
}
