// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type CopilotConversation struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.UUID
	Title     string
	Pinned    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CopilotMessage struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ConversationID uuid.UUID
	Role           string
	Content        json.RawMessage
	CreatedAt      time.Time
}
