// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createConversation = `-- name: CreateConversation :one

INSERT INTO copilot.conversations (tenant_id, user_id, title)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, user_id, title, pinned, created_at, updated_at
`

type CreateConversationParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
	Title    string
}

// Queries for the copilot domain.
// Static queries against copilot.conversations and copilot.messages; compiled
// by sqlc into ./dbgen. All queries are scoped by tenant_id (multi-tenancy).
func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (CopilotConversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.TenantID, arg.UserID, arg.Title)
	var i CopilotConversation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Title,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :execrows
DELETE FROM copilot.conversations
WHERE id = $1 AND tenant_id = $2 AND user_id = $3
`

type DeleteConversationParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) DeleteConversation(ctx context.Context, arg DeleteConversationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConversation, arg.ID, arg.TenantID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConversation = `-- name: GetConversation :one
SELECT id, tenant_id, user_id, title, pinned, created_at, updated_at
FROM copilot.conversations
WHERE id = $1 AND tenant_id = $2 AND user_id = $3
`

type GetConversationParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (CopilotConversation, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.ID, arg.TenantID, arg.UserID)
	var i CopilotConversation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Title,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO copilot.messages (tenant_id, conversation_id, role, content)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, conversation_id, role, content, created_at
`

type InsertMessageParams struct {
	TenantID       uuid.UUID
	ConversationID uuid.UUID
	Role           string
	Content        json.RawMessage
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (CopilotMessage, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.TenantID,
		arg.ConversationID,
		arg.Role,
		arg.Content,
	)
	var i CopilotMessage
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, tenant_id, user_id, title, pinned, created_at, updated_at
FROM copilot.conversations
WHERE tenant_id = $1 AND user_id = $2
ORDER BY pinned DESC, updated_at DESC
`

type ListConversationsParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]CopilotConversation, error) {
	rows, err := q.db.Query(ctx, listConversations, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CopilotConversation{}
	for rows.Next() {
		var i CopilotConversation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Title,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, tenant_id, conversation_id, role, content, created_at
FROM copilot.messages
WHERE conversation_id = $1 AND tenant_id = $2
ORDER BY created_at ASC
`

type ListMessagesParams struct {
	ConversationID uuid.UUID
	TenantID       uuid.UUID
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]CopilotMessage, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ConversationID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CopilotMessage{}
	for rows.Next() {
		var i CopilotMessage
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchConversation = `-- name: PatchConversation :one
UPDATE copilot.conversations
SET
    title      = COALESCE($1, title),
    pinned     = COALESCE($2, pinned),
    updated_at = now()
WHERE id = $3 AND tenant_id = $4 AND user_id = $5
RETURNING id, tenant_id, user_id, title, pinned, created_at, updated_at
`

type PatchConversationParams struct {
	Title    *string
	Pinned   *bool
	ID       uuid.UUID
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) PatchConversation(ctx context.Context, arg PatchConversationParams) (CopilotConversation, error) {
	row := q.db.QueryRow(ctx, patchConversation,
		arg.Title,
		arg.Pinned,
		arg.ID,
		arg.TenantID,
		arg.UserID,
	)
	var i CopilotConversation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Title,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE copilot.conversations
SET updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type TouchConversationParams struct {
	ConversationID uuid.UUID
	TenantID       uuid.UUID
}

func (q *Queries) TouchConversation(ctx context.Context, arg TouchConversationParams) error {
	_, err := q.db.Exec(ctx, touchConversation, arg.ConversationID, arg.TenantID)
	return err
}
