// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSecurityEventSummary = `-- name: GetSecurityEventSummary :one

SELECT
    COUNT(*) FILTER (WHERE status = 'open')                                               AS open,
    COUNT(*) FILTER (WHERE resolved_at >= NOW() - INTERVAL '24 hours')                   AS resolved_24h,
    COUNT(DISTINCT user_id) FILTER (WHERE status = 'open' AND user_id IS NOT NULL)       AS affected_accounts,
    COUNT(*) FILTER (WHERE severity = 'high' AND created_at >= NOW() - INTERVAL '24 hours') AS high_severity_24h
FROM auth.security_events
WHERE tenant_id = $1
`

type GetSecurityEventSummaryRow struct {
	Open             int64
	Resolved24h      int64
	AffectedAccounts int64
	HighSeverity24h  int64
}

// ListSecurityEvents is intentionally hand-written in threat.go because
// COALESCE(host(e.ip),”) causes sqlc to generate interface{} for the column,
// making type-safe scanning impossible without runtime assertions.
func (q *Queries) GetSecurityEventSummary(ctx context.Context, tenantID uuid.UUID) (GetSecurityEventSummaryRow, error) {
	row := q.db.QueryRow(ctx, getSecurityEventSummary, tenantID)
	var i GetSecurityEventSummaryRow
	err := row.Scan(
		&i.Open,
		&i.Resolved24h,
		&i.AffectedAccounts,
		&i.HighSeverity24h,
	)
	return i, err
}

const getUserForAnomaly = `-- name: GetUserForAnomaly :one

SELECT id, tenant_id FROM "user".users
WHERE LOWER(email) = LOWER($1) AND deleted_at IS NULL AND tenant_id IS NOT NULL
LIMIT 1
`

type GetUserForAnomalyRow struct {
	ID       uuid.UUID
	TenantID pgtype.UUID
}

// Queries for the threat-detection/threat domain.
// Static queries are compiled by sqlc into ./dbgen.
// InsertSecurityEvent is intentionally hand-written in threat.go because it
// uses NULLIF($7,”)::inet — the inet cast makes sqlc parameter-type inference
// ambiguous; correctness takes priority over coverage.
func (q *Queries) GetUserForAnomaly(ctx context.Context, lower string) (GetUserForAnomalyRow, error) {
	row := q.db.QueryRow(ctx, getUserForAnomaly, lower)
	var i GetUserForAnomalyRow
	err := row.Scan(&i.ID, &i.TenantID)
	return i, err
}

const resolveSecurityEvent = `-- name: ResolveSecurityEvent :execrows
UPDATE auth.security_events
SET status = 'resolved', resolved_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND resolved_at IS NULL
`

type ResolveSecurityEventParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) ResolveSecurityEvent(ctx context.Context, arg ResolveSecurityEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveSecurityEvent, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
