// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/google/uuid"
)

type TenantAuthPolicy struct {
	TenantID                 uuid.UUID
	PasswordEnabled          bool
	PasswordMinLength        int32
	PasswordRequireUppercase bool
	PasswordRequireNumber    bool
	PasswordRequireSymbol    bool
	MagicLinkEnabled         bool
	PasskeyEnabled           bool
	OtpEmailEnabled          bool
	OtpSmsEnabled            bool
	UpdatedAt                time.Time
	MagicLinkTtlMinutes      int32
	SelfRegistrationEnabled  bool
	RememberDeviceEnabled    bool
}
