// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/google/uuid"
)

type TenantIpRule struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Cidr      string
	Label     string
	Action    string
	CreatedAt time.Time
}
