// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteIPRule = `-- name: DeleteIPRule :execrows
DELETE FROM tenant.ip_rules WHERE id = $1 AND tenant_id = $2
`

type DeleteIPRuleParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteIPRule(ctx context.Context, arg DeleteIPRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIPRule, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIPRulesEnabled = `-- name: GetIPRulesEnabled :one
SELECT enabled FROM tenant.ip_rules_config WHERE tenant_id = $1
`

func (q *Queries) GetIPRulesEnabled(ctx context.Context, tenantID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getIPRulesEnabled, tenantID)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const insertIPRule = `-- name: InsertIPRule :one
INSERT INTO tenant.ip_rules (tenant_id, cidr, label, action)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, cidr, label, action, created_at
`

type InsertIPRuleParams struct {
	TenantID uuid.UUID
	Cidr     string
	Label    string
	Action   string
}

func (q *Queries) InsertIPRule(ctx context.Context, arg InsertIPRuleParams) (TenantIpRule, error) {
	row := q.db.QueryRow(ctx, insertIPRule,
		arg.TenantID,
		arg.Cidr,
		arg.Label,
		arg.Action,
	)
	var i TenantIpRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Cidr,
		&i.Label,
		&i.Action,
		&i.CreatedAt,
	)
	return i, err
}

const listIPRules = `-- name: ListIPRules :many

SELECT id, tenant_id, cidr, label, action, created_at
FROM tenant.ip_rules WHERE tenant_id = $1 ORDER BY action, created_at
`

// Queries for the risk/ipallow domain.
// All queries are static and compiled by sqlc into ./dbgen.
func (q *Queries) ListIPRules(ctx context.Context, tenantID uuid.UUID) ([]TenantIpRule, error) {
	rows, err := q.db.Query(ctx, listIPRules, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantIpRule{}
	for rows.Next() {
		var i TenantIpRule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Cidr,
			&i.Label,
			&i.Action,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIPRulesEnabled = `-- name: SetIPRulesEnabled :exec
INSERT INTO tenant.ip_rules_config (tenant_id, enabled, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (tenant_id) DO UPDATE SET enabled = EXCLUDED.enabled, updated_at = NOW()
`

type SetIPRulesEnabledParams struct {
	TenantID uuid.UUID
	Enabled  bool
}

func (q *Queries) SetIPRulesEnabled(ctx context.Context, arg SetIPRulesEnabledParams) error {
	_, err := q.db.Exec(ctx, setIPRulesEnabled, arg.TenantID, arg.Enabled)
	return err
}
