// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listActivityHistory = `-- name: ListActivityHistory :many

SELECT id, actor_user_id, actor_type, action, resource_type, resource_id,
       COALESCE(host(ip), '')::text AS ip, user_agent, created_at, metadata, tenant_id
FROM audit.events
WHERE tenant_id = $1
  AND ($2::text[] IS NULL OR action = ANY($2))
  AND ($3::uuid IS NULL OR actor_user_id = $3)
  AND ($4::timestamptz IS NULL OR created_at >= $4)
  AND ($5::timestamptz IS NULL OR created_at <= $5)
  AND ($6::text IS NULL OR search_vector @@ websearch_to_tsquery('simple', $6))
  AND ($7::timestamptz IS NULL OR created_at < $7 OR (created_at = $7 AND id < $8::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $9
`

type ListActivityHistoryParams struct {
	TenantID pgtype.UUID
	Actions  []string
	ActorID  pgtype.UUID
	FromTs   pgtype.Timestamptz
	ToTs     pgtype.Timestamptz
	Q        *string
	CursorTs pgtype.Timestamptz
	CursorID pgtype.UUID
	RowLimit int32
}

type ListActivityHistoryRow struct {
	ID           uuid.UUID
	ActorUserID  pgtype.UUID
	ActorType    string
	Action       string
	ResourceType string
	ResourceID   pgtype.UUID
	Ip           string
	UserAgent    *string
	CreatedAt    time.Time
	Metadata     json.RawMessage
	TenantID     pgtype.UUID
}

// Queries for the activity domain.
// Static queries against audit.events; compiled by sqlc into ./dbgen.
// All queries are scoped by tenant_id (multi-tenancy).
// Cursor-paginated history, newest first. Optional filters: action type array,
// actor, time range, and GIN full-text search. The cursor carries both
// created_at and id so the tuple comparison can be expanded — sqlc does not
// support row-value predicates, so (created_at, id) < (cursor_ts, cursor_id)
// is rewritten as the equivalent OR expression.
// ip is nullable INET; COALESCE(host(ip), ”)::text ensures a non-null string.
func (q *Queries) ListActivityHistory(ctx context.Context, arg ListActivityHistoryParams) ([]ListActivityHistoryRow, error) {
	rows, err := q.db.Query(ctx, listActivityHistory,
		arg.TenantID,
		arg.Actions,
		arg.ActorID,
		arg.FromTs,
		arg.ToTs,
		arg.Q,
		arg.CursorTs,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityHistoryRow{}
	for rows.Next() {
		var i ListActivityHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.ActorType,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
			&i.Metadata,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replayActivityHistory = `-- name: ReplayActivityHistory :many
SELECT id, actor_user_id, actor_type, action, resource_type, resource_id,
       COALESCE(host(ip), '')::text AS ip, user_agent, created_at, metadata, tenant_id
FROM audit.events
WHERE tenant_id = $1
  AND (created_at > $2 OR (created_at = $2 AND id > $3))
ORDER BY created_at ASC, id ASC
LIMIT 100
`

type ReplayActivityHistoryParams struct {
	TenantID pgtype.UUID
	AfterTs  time.Time
	AfterID  uuid.UUID
}

type ReplayActivityHistoryRow struct {
	ID           uuid.UUID
	ActorUserID  pgtype.UUID
	ActorType    string
	Action       string
	ResourceType string
	ResourceID   pgtype.UUID
	Ip           string
	UserAgent    *string
	CreatedAt    time.Time
	Metadata     json.RawMessage
	TenantID     pgtype.UUID
}

// Replay events newer than (after_ts, after_id) in chronological order (ASC).
// Used by the SSE handler to replay missed events on reconnect. The tuple
// comparison (created_at, id) > (after_ts, after_id) is expanded — the #1
// sqlc gotcha with row-value predicates.
func (q *Queries) ReplayActivityHistory(ctx context.Context, arg ReplayActivityHistoryParams) ([]ReplayActivityHistoryRow, error) {
	rows, err := q.db.Query(ctx, replayActivityHistory, arg.TenantID, arg.AfterTs, arg.AfterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReplayActivityHistoryRow{}
	for rows.Next() {
		var i ReplayActivityHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.ActorType,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
			&i.Metadata,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
