// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type QeetaiConversation struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.UUID
	Title     string
	Pinned    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type QeetaiMessage struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ConversationID uuid.UUID
	Role           string
	Content        json.RawMessage
	CreatedAt      time.Time
}

type QeetaiProviderSetting struct {
	TenantID      uuid.UUID
	Provider      string
	Model         string
	BaseUrl       string
	MaxTokens     int32
	KeyCiphertext []byte
	KeyNonce      []byte
	KeyLast4      string
	Enabled       bool
	UpdatedBy     pgtype.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
