// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRipeDeletedUsers = `-- name: CountRipeDeletedUsers :one
SELECT count(*)
FROM "user".users
WHERE tenant_id = $1
  AND deleted_at IS NOT NULL
  AND deleted_at < NOW() - make_interval(days => $2)
`

type CountRipeDeletedUsersParams struct {
	TenantID pgtype.UUID
	Days     int32
}

// Count soft-deleted users older than `days` days for a given tenant.
// The days value is clamped to [1,3650] by the caller before it reaches here.
func (q *Queries) CountRipeDeletedUsers(ctx context.Context, arg CountRipeDeletedUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRipeDeletedUsers, arg.TenantID, arg.Days)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRetentionPolicy = `-- name: GetRetentionPolicy :one

SELECT deleted_users_enabled, deleted_users_days
FROM tenant.retention_policy
WHERE tenant_id = $1
`

type GetRetentionPolicyRow struct {
	DeletedUsersEnabled bool
	DeletedUsersDays    int32
}

// Queries for the retention domain.
// Static queries against tenant.retention_policy and "user".users live here
// and are compiled by sqlc into ./dbgen.
func (q *Queries) GetRetentionPolicy(ctx context.Context, tenantID uuid.UUID) (GetRetentionPolicyRow, error) {
	row := q.db.QueryRow(ctx, getRetentionPolicy, tenantID)
	var i GetRetentionPolicyRow
	err := row.Scan(&i.DeletedUsersEnabled, &i.DeletedUsersDays)
	return i, err
}

const listEnabledRetentionPolicies = `-- name: ListEnabledRetentionPolicies :many
SELECT tenant_id, deleted_users_days
FROM tenant.retention_policy
WHERE deleted_users_enabled = TRUE
`

type ListEnabledRetentionPoliciesRow struct {
	TenantID         uuid.UUID
	DeletedUsersDays int32
}

func (q *Queries) ListEnabledRetentionPolicies(ctx context.Context) ([]ListEnabledRetentionPoliciesRow, error) {
	rows, err := q.db.Query(ctx, listEnabledRetentionPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledRetentionPoliciesRow{}
	for rows.Next() {
		var i ListEnabledRetentionPoliciesRow
		if err := rows.Scan(&i.TenantID, &i.DeletedUsersDays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeRipeDeletedUsers = `-- name: PurgeRipeDeletedUsers :execrows
DELETE FROM "user".users
WHERE tenant_id = $1
  AND deleted_at IS NOT NULL
  AND deleted_at < NOW() - make_interval(days => $2)
`

type PurgeRipeDeletedUsersParams struct {
	TenantID pgtype.UUID
	Days     int32
}

// Permanently remove soft-deleted users older than `days` days.
// Returns the number of rows deleted via :execrows.
func (q *Queries) PurgeRipeDeletedUsers(ctx context.Context, arg PurgeRipeDeletedUsersParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeRipeDeletedUsers, arg.TenantID, arg.Days)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertRetentionPolicy = `-- name: UpsertRetentionPolicy :one
INSERT INTO tenant.retention_policy (tenant_id, deleted_users_enabled, deleted_users_days, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (tenant_id) DO UPDATE SET
    deleted_users_enabled = EXCLUDED.deleted_users_enabled,
    deleted_users_days    = EXCLUDED.deleted_users_days,
    updated_at            = NOW()
RETURNING deleted_users_enabled, deleted_users_days
`

type UpsertRetentionPolicyParams struct {
	TenantID            uuid.UUID
	DeletedUsersEnabled bool
	DeletedUsersDays    int32
}

type UpsertRetentionPolicyRow struct {
	DeletedUsersEnabled bool
	DeletedUsersDays    int32
}

// Upsert a tenant's retention policy and return the stored values.
func (q *Queries) UpsertRetentionPolicy(ctx context.Context, arg UpsertRetentionPolicyParams) (UpsertRetentionPolicyRow, error) {
	row := q.db.QueryRow(ctx, upsertRetentionPolicy, arg.TenantID, arg.DeletedUsersEnabled, arg.DeletedUsersDays)
	var i UpsertRetentionPolicyRow
	err := row.Scan(&i.DeletedUsersEnabled, &i.DeletedUsersDays)
	return i, err
}
