// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkTenantMembership = `-- name: CheckTenantMembership :one
SELECT EXISTS (
    SELECT 1 FROM rbac.user_roles WHERE user_id = $1 AND tenant_id = $2
) AS is_member
`

type CheckTenantMembershipParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) CheckTenantMembership(ctx context.Context, arg CheckTenantMembershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkTenantMembership, arg.UserID, arg.TenantID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const deleteLoginAttempt = `-- name: DeleteLoginAttempt :exec
DELETE FROM auth.login_attempts WHERE email = $1
`

func (q *Queries) DeleteLoginAttempt(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteLoginAttempt, email)
	return err
}

const deleteLoginSession = `-- name: DeleteLoginSession :exec
DELETE FROM auth.login_sessions WHERE token_hash = $1
`

func (q *Queries) DeleteLoginSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteLoginSession, tokenHash)
	return err
}

const deleteMFALoginChallenge = `-- name: DeleteMFALoginChallenge :exec
DELETE FROM auth.mfa_login_challenges WHERE id = $1
`

func (q *Queries) DeleteMFALoginChallenge(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMFALoginChallenge, id)
	return err
}

const getLoginAttempt = `-- name: GetLoginAttempt :one

SELECT locked_until FROM auth.login_attempts WHERE email = $1
`

// Queries for the authentication domain.
// Static queries with fully-typed, non-nullable parameters are converted.
// Queries involving nullable UUID columns passed as Go interface{}/nil
// (sessions.tenant_id, mfa_login_challenges.tenant_id, trusted_devices.tenant_id)
// remain hand-written because they require Go-nil → SQL NULL semantics that
// sqlc's uuid override cannot express without additional NULLIF wrappers that
// would silently treat the zero UUID as NULL.
// The Refresh join (FOR UPDATE OF rt across three tables) is also left raw.
// Returns the locked_until column for a given email; pgx.ErrNoRows when no row.
func (q *Queries) GetLoginAttempt(ctx context.Context, email string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLoginAttempt, email)
	var locked_until pgtype.Timestamptz
	err := row.Scan(&locked_until)
	return locked_until, err
}

const getLoginSession = `-- name: GetLoginSession :one
SELECT user_id, expires_at FROM auth.login_sessions WHERE token_hash = $1
`

type GetLoginSessionRow struct {
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) GetLoginSession(ctx context.Context, tokenHash string) (GetLoginSessionRow, error) {
	row := q.db.QueryRow(ctx, getLoginSession, tokenHash)
	var i GetLoginSessionRow
	err := row.Scan(&i.UserID, &i.ExpiresAt)
	return i, err
}

const insertLoginSession = `-- name: InsertLoginSession :exec
INSERT INTO auth.login_sessions (token_hash, user_id, expires_at, ip, user_agent)
VALUES ($1, $2, $3, NULLIF($4::text, '')::inet, $5)
`

type InsertLoginSessionParams struct {
	TokenHash string
	UserID    uuid.UUID
	ExpiresAt time.Time
	Ip        string
	UserAgent *string
}

func (q *Queries) InsertLoginSession(ctx context.Context, arg InsertLoginSessionParams) error {
	_, err := q.db.Exec(ctx, insertLoginSession,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const insertPasswordCredential = `-- name: InsertPasswordCredential :exec
INSERT INTO auth.password_credentials (user_id, password_hash)
VALUES ($1, $2)
`

type InsertPasswordCredentialParams struct {
	UserID       uuid.UUID
	PasswordHash string
}

// Stores the Argon2id hash for a newly created identity (signup / hosted register).
func (q *Queries) InsertPasswordCredential(ctx context.Context, arg InsertPasswordCredentialParams) error {
	_, err := q.db.Exec(ctx, insertPasswordCredential, arg.UserID, arg.PasswordHash)
	return err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO auth.refresh_tokens (session_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertRefreshTokenParams struct {
	SessionID uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken, arg.SessionID, arg.TokenHash, arg.ExpiresAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertTenantlessSession = `-- name: InsertTenantlessSession :exec
INSERT INTO auth.sessions (id, user_id, tenant_id, ip, user_agent)
VALUES ($1, $2, NULL, NULLIF($3::text, '')::inet, $4)
`

type InsertTenantlessSessionParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Ip        string
	UserAgent *string
}

// Tenant-less session: tenant_id is a literal NULL (not a bind). ip goes through
// NULLIF so an empty string stores as SQL NULL, matching InsertLoginSession.
func (q *Queries) InsertTenantlessSession(ctx context.Context, arg InsertTenantlessSessionParams) error {
	_, err := q.db.Exec(ctx, insertTenantlessSession,
		arg.ID,
		arg.UserID,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const insertTenantlessUser = `-- name: InsertTenantlessUser :one
INSERT INTO "user".users (tenant_id, email, display_name)
VALUES (NULL, $1, $2)
RETURNING id, created_at, updated_at
`

type InsertTenantlessUserParams struct {
	Email       string
	DisplayName *string
}

type InsertTenantlessUserRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Tenant-less signup: creates the identity with tenant_id NULL (a literal, not a
// bind — membership lives in rbac.user_roles). display_name is nullable text.
func (q *Queries) InsertTenantlessUser(ctx context.Context, arg InsertTenantlessUserParams) (InsertTenantlessUserRow, error) {
	row := q.db.QueryRow(ctx, insertTenantlessUser, arg.Email, arg.DisplayName)
	var i InsertTenantlessUserRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :exec
UPDATE auth.refresh_tokens SET used_at = NOW(), replaced_by = $1 WHERE id = $2
`

type MarkRefreshTokenUsedParams struct {
	ReplacedBy pgtype.UUID
	ID         uuid.UUID
}

func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markRefreshTokenUsed, arg.ReplacedBy, arg.ID)
	return err
}

const revokeSessionById = `-- name: RevokeSessionById :exec
UPDATE auth.sessions SET revoked_at = NOW()
WHERE id = $1 AND revoked_at IS NULL
`

// Idempotent: no-op on an already-revoked session.
func (q *Queries) RevokeSessionById(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSessionById, sessionID)
	return err
}

const touchTrustedDevice = `-- name: TouchTrustedDevice :execrows
UPDATE auth.trusted_devices SET last_used_at = NOW()
WHERE token_hash = $1 AND user_id = $2 AND expires_at > NOW()
`

type TouchTrustedDeviceParams struct {
	TokenHash string
	UserID    uuid.UUID
}

// Refreshes last_used_at and returns 1 when a live token was found, 0 otherwise.
func (q *Queries) TouchTrustedDevice(ctx context.Context, arg TouchTrustedDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchTrustedDevice, arg.TokenHash, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePasswordCredentialHash = `-- name: UpdatePasswordCredentialHash :exec
UPDATE auth.password_credentials SET password_hash = $1, updated_at = NOW()
WHERE user_id = $2
`

type UpdatePasswordCredentialHashParams struct {
	PasswordHash string
	UserID       uuid.UUID
}

func (q *Queries) UpdatePasswordCredentialHash(ctx context.Context, arg UpdatePasswordCredentialHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordCredentialHash, arg.PasswordHash, arg.UserID)
	return err
}

const updateSessionLastSeen = `-- name: UpdateSessionLastSeen :exec
UPDATE auth.sessions SET last_seen_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateSessionLastSeen(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateSessionLastSeen, sessionID)
	return err
}

const upsertLoginAttempt = `-- name: UpsertLoginAttempt :one
INSERT INTO auth.login_attempts (email, failed_count, first_failed_at, last_failed_at)
VALUES ($1, 1, NOW(), NOW())
ON CONFLICT (email) DO UPDATE SET
    failed_count = CASE
        WHEN login_attempts.last_failed_at < $2 THEN 1
        ELSE login_attempts.failed_count + 1 END,
    first_failed_at = CASE
        WHEN login_attempts.last_failed_at < $2 THEN NOW()
        ELSE login_attempts.first_failed_at END,
    last_failed_at = NOW(),
    locked_until = CASE
        WHEN (CASE
            WHEN login_attempts.last_failed_at < $2 THEN 1
            ELSE login_attempts.failed_count + 1 END) >= $3::int4
        THEN $4::timestamptz ELSE NULL END
RETURNING failed_count
`

type UpsertLoginAttemptParams struct {
	Email           string
	WindowStart     time.Time
	MaxFailedLogins int32
	LockUntil       time.Time
}

// Upserts the failed-login counter. @window_start resets the counter when the
// last failure is older than the failure window; @max_failed_logins and
// @lock_until trigger the lockout.
func (q *Queries) UpsertLoginAttempt(ctx context.Context, arg UpsertLoginAttemptParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertLoginAttempt,
		arg.Email,
		arg.WindowStart,
		arg.MaxFailedLogins,
		arg.LockUntil,
	)
	var failed_count int32
	err := row.Scan(&failed_count)
	return failed_count, err
}
