// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveCIBARequest = `-- name: ApproveCIBARequest :exec
UPDATE auth.oidc_ciba_requests SET status = 'authorized', approved_at = NOW() WHERE id = $1
`

func (q *Queries) ApproveCIBARequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, approveCIBARequest, id)
	return err
}

const approveDevice = `-- name: ApproveDevice :exec
UPDATE auth.oidc_device_codes SET status = 'authorized', user_id = $1, approved_at = NOW()
WHERE id = $2
`

type ApproveDeviceParams struct {
	UserID pgtype.UUID
	ID     uuid.UUID
}

func (q *Queries) ApproveDevice(ctx context.Context, arg ApproveDeviceParams) error {
	_, err := q.db.Exec(ctx, approveDevice, arg.UserID, arg.ID)
	return err
}

const checkUserInDeviceTenant = `-- name: CheckUserInDeviceTenant :one
SELECT EXISTS(SELECT 1 FROM "user".users WHERE id = $1 AND tenant_id = $2)
`

type CheckUserInDeviceTenantParams struct {
	ID       uuid.UUID
	TenantID pgtype.UUID
}

func (q *Queries) CheckUserInDeviceTenant(ctx context.Context, arg CheckUserInDeviceTenantParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserInDeviceTenant, arg.ID, arg.TenantID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const consumeAuthorizationCode = `-- name: ConsumeAuthorizationCode :one
SELECT user_id, tenant_id, redirect_uri, scopes,
       nonce, code_challenge, code_challenge_method, expires_at, used_at
FROM auth.oidc_authorization_codes
WHERE code_hash = $1 AND client_id = $2
FOR UPDATE
`

type ConsumeAuthorizationCodeParams struct {
	CodeHash string
	ClientID string
}

type ConsumeAuthorizationCodeRow struct {
	UserID              uuid.UUID
	TenantID            uuid.UUID
	RedirectUri         string
	Scopes              []string
	Nonce               *string
	CodeChallenge       *string
	CodeChallengeMethod *string
	ExpiresAt           time.Time
	UsedAt              pgtype.Timestamptz
}

func (q *Queries) ConsumeAuthorizationCode(ctx context.Context, arg ConsumeAuthorizationCodeParams) (ConsumeAuthorizationCodeRow, error) {
	row := q.db.QueryRow(ctx, consumeAuthorizationCode, arg.CodeHash, arg.ClientID)
	var i ConsumeAuthorizationCodeRow
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.RedirectUri,
		&i.Scopes,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const consumeCIBARequest = `-- name: ConsumeCIBARequest :exec
UPDATE auth.oidc_ciba_requests SET consumed_at = NOW() WHERE id = $1
`

func (q *Queries) ConsumeCIBARequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeCIBARequest, id)
	return err
}

const consumeDeviceCode = `-- name: ConsumeDeviceCode :exec
UPDATE auth.oidc_device_codes SET consumed_at = NOW() WHERE id = $1
`

func (q *Queries) ConsumeDeviceCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeDeviceCode, id)
	return err
}

const deleteOIDCClient = `-- name: DeleteOIDCClient :one
DELETE FROM auth.oidc_clients WHERE id = $1 AND tenant_id = $2 RETURNING client_id
`

type DeleteOIDCClientParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteOIDCClient(ctx context.Context, arg DeleteOIDCClientParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteOIDCClient, arg.ID, arg.TenantID)
	var client_id string
	err := row.Scan(&client_id)
	return client_id, err
}

const denyCIBARequest = `-- name: DenyCIBARequest :exec
UPDATE auth.oidc_ciba_requests SET status = 'denied' WHERE id = $1
`

func (q *Queries) DenyCIBARequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, denyCIBARequest, id)
	return err
}

const denyDevice = `-- name: DenyDevice :exec
UPDATE auth.oidc_device_codes SET status = 'denied' WHERE id = $1
`

func (q *Queries) DenyDevice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, denyDevice, id)
	return err
}

const getClientForAuth = `-- name: GetClientForAuth :one
SELECT client_secret_hash, type, grant_types
FROM auth.oidc_clients WHERE client_id = $1
`

type GetClientForAuthRow struct {
	ClientSecretHash *string
	Type             string
	GrantTypes       []string
}

func (q *Queries) GetClientForAuth(ctx context.Context, clientID string) (GetClientForAuthRow, error) {
	row := q.db.QueryRow(ctx, getClientForAuth, clientID)
	var i GetClientForAuthRow
	err := row.Scan(&i.ClientSecretHash, &i.Type, &i.GrantTypes)
	return i, err
}

const getClientGrantTypes = `-- name: GetClientGrantTypes :one
SELECT grant_types FROM auth.oidc_clients WHERE client_id = $1
`

func (q *Queries) GetClientGrantTypes(ctx context.Context, clientID string) ([]string, error) {
	row := q.db.QueryRow(ctx, getClientGrantTypes, clientID)
	var grant_types []string
	err := row.Scan(&grant_types)
	return grant_types, err
}

const getClientName = `-- name: GetClientName :one
SELECT name, tenant_id FROM auth.oidc_clients WHERE client_id = $1
`

type GetClientNameRow struct {
	Name     string
	TenantID uuid.UUID
}

func (q *Queries) GetClientName(ctx context.Context, clientID string) (GetClientNameRow, error) {
	row := q.db.QueryRow(ctx, getClientName, clientID)
	var i GetClientNameRow
	err := row.Scan(&i.Name, &i.TenantID)
	return i, err
}

const getClientPostLogoutURIs = `-- name: GetClientPostLogoutURIs :one
SELECT post_logout_uris FROM auth.oidc_clients WHERE client_id = $1
`

func (q *Queries) GetClientPostLogoutURIs(ctx context.Context, clientID string) ([]string, error) {
	row := q.db.QueryRow(ctx, getClientPostLogoutURIs, clientID)
	var post_logout_uris []string
	err := row.Scan(&post_logout_uris)
	return post_logout_uris, err
}

const getClientRedirectInfo = `-- name: GetClientRedirectInfo :one
SELECT tenant_id, scopes, redirect_uris FROM auth.oidc_clients WHERE client_id = $1
`

type GetClientRedirectInfoRow struct {
	TenantID     uuid.UUID
	Scopes       []string
	RedirectUris []string
}

func (q *Queries) GetClientRedirectInfo(ctx context.Context, clientID string) (GetClientRedirectInfoRow, error) {
	row := q.db.QueryRow(ctx, getClientRedirectInfo, clientID)
	var i GetClientRedirectInfoRow
	err := row.Scan(&i.TenantID, &i.Scopes, &i.RedirectUris)
	return i, err
}

const getClientTenantAndScopes = `-- name: GetClientTenantAndScopes :one
SELECT tenant_id, scopes FROM auth.oidc_clients WHERE client_id = $1
`

type GetClientTenantAndScopesRow struct {
	TenantID uuid.UUID
	Scopes   []string
}

func (q *Queries) GetClientTenantAndScopes(ctx context.Context, clientID string) (GetClientTenantAndScopesRow, error) {
	row := q.db.QueryRow(ctx, getClientTenantAndScopes, clientID)
	var i GetClientTenantAndScopesRow
	err := row.Scan(&i.TenantID, &i.Scopes)
	return i, err
}

const getConsent = `-- name: GetConsent :one

SELECT scopes FROM auth.oidc_consents WHERE user_id = $1 AND client_id = $2
`

type GetConsentParams struct {
	UserID   uuid.UUID
	ClientID string
}

// ==========================================================================
// Consents
// ==========================================================================
func (q *Queries) GetConsent(ctx context.Context, arg GetConsentParams) ([]string, error) {
	row := q.db.QueryRow(ctx, getConsent, arg.UserID, arg.ClientID)
	var scopes []string
	err := row.Scan(&scopes)
	return scopes, err
}

const getDeviceByUserCode = `-- name: GetDeviceByUserCode :one
SELECT client_id, scopes, status, expires_at
FROM auth.oidc_device_codes WHERE user_code = $1
`

type GetDeviceByUserCodeRow struct {
	ClientID  string
	Scopes    []string
	Status    string
	ExpiresAt time.Time
}

func (q *Queries) GetDeviceByUserCode(ctx context.Context, userCode string) (GetDeviceByUserCodeRow, error) {
	row := q.db.QueryRow(ctx, getDeviceByUserCode, userCode)
	var i GetDeviceByUserCodeRow
	err := row.Scan(
		&i.ClientID,
		&i.Scopes,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const getGrantForRevoke = `-- name: GetGrantForRevoke :one
SELECT client_id, user_id FROM auth.oidc_refresh_tokens
WHERE id = $1 AND tenant_id = $2
`

type GetGrantForRevokeParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type GetGrantForRevokeRow struct {
	ClientID string
	UserID   uuid.UUID
}

func (q *Queries) GetGrantForRevoke(ctx context.Context, arg GetGrantForRevokeParams) (GetGrantForRevokeRow, error) {
	row := q.db.QueryRow(ctx, getGrantForRevoke, arg.ID, arg.TenantID)
	var i GetGrantForRevokeRow
	err := row.Scan(&i.ClientID, &i.UserID)
	return i, err
}

const getOIDCClient = `-- name: GetOIDCClient :one
SELECT id, tenant_id, client_id, type, name, redirect_uris,
       post_logout_uris, grant_types, scopes, created_at
FROM auth.oidc_clients WHERE id = $1 AND tenant_id = $2
`

type GetOIDCClientParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type GetOIDCClientRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ClientID       string
	Type           string
	Name           string
	RedirectUris   []string
	PostLogoutUris []string
	GrantTypes     []string
	Scopes         []string
	CreatedAt      time.Time
}

func (q *Queries) GetOIDCClient(ctx context.Context, arg GetOIDCClientParams) (GetOIDCClientRow, error) {
	row := q.db.QueryRow(ctx, getOIDCClient, arg.ID, arg.TenantID)
	var i GetOIDCClientRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Type,
		&i.Name,
		&i.RedirectUris,
		&i.PostLogoutUris,
		&i.GrantTypes,
		&i.Scopes,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenForIntrospect = `-- name: GetRefreshTokenForIntrospect :one
SELECT client_id, user_id, tenant_id, scopes, issued_at, expires_at, used_at, revoked_at
FROM auth.oidc_refresh_tokens WHERE token_hash = $1
`

type GetRefreshTokenForIntrospectRow struct {
	ClientID  string
	UserID    uuid.UUID
	TenantID  uuid.UUID
	Scopes    []string
	IssuedAt  time.Time
	ExpiresAt time.Time
	UsedAt    pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) GetRefreshTokenForIntrospect(ctx context.Context, tokenHash string) (GetRefreshTokenForIntrospectRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForIntrospect, tokenHash)
	var i GetRefreshTokenForIntrospectRow
	err := row.Scan(
		&i.ClientID,
		&i.UserID,
		&i.TenantID,
		&i.Scopes,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserByEmailInTenant = `-- name: GetUserByEmailInTenant :one

SELECT id FROM "user".users
WHERE tenant_id = $1 AND LOWER(email) = LOWER($2) AND deleted_at IS NULL
`

type GetUserByEmailInTenantParams struct {
	TenantID pgtype.UUID
	Email    string
}

// ==========================================================================
// CIBA (OpenID Connect Client-Initiated Backchannel Authentication)
// ==========================================================================
func (q *Queries) GetUserByEmailInTenant(ctx context.Context, arg GetUserByEmailInTenantParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserByEmailInTenant, arg.TenantID, arg.Email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertAuthorizationCode = `-- name: InsertAuthorizationCode :exec

INSERT INTO auth.oidc_authorization_codes (
    code_hash, client_id, user_id, tenant_id, redirect_uri,
    scopes, nonce, code_challenge, code_challenge_method, expires_at
) VALUES ($1, $2, $3, $4, $5,
          $6, NULLIF($7,''), NULLIF($8,''), NULLIF($9,''),
          NOW() + INTERVAL '10 minutes')
`

type InsertAuthorizationCodeParams struct {
	CodeHash            string
	ClientID            string
	UserID              uuid.UUID
	TenantID            uuid.UUID
	RedirectUri         string
	Scopes              []string
	Nonce               interface{}
	CodeChallenge       interface{}
	CodeChallengeMethod interface{}
}

// ==========================================================================
// Authorization codes
// ==========================================================================
func (q *Queries) InsertAuthorizationCode(ctx context.Context, arg InsertAuthorizationCodeParams) error {
	_, err := q.db.Exec(ctx, insertAuthorizationCode,
		arg.CodeHash,
		arg.ClientID,
		arg.UserID,
		arg.TenantID,
		arg.RedirectUri,
		arg.Scopes,
		arg.Nonce,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
	)
	return err
}

const insertCIBARequest = `-- name: InsertCIBARequest :exec
INSERT INTO auth.oidc_ciba_requests (
    auth_req_id_hash, client_id, tenant_id, user_id, scopes,
    binding_message, interval_seconds, expires_at
) VALUES ($1, $2, $3, $4, $5,
          $6, $7, NOW() + INTERVAL '10 minutes')
`

type InsertCIBARequestParams struct {
	AuthReqIDHash   string
	ClientID        string
	TenantID        uuid.UUID
	UserID          uuid.UUID
	Scopes          []string
	BindingMessage  *string
	IntervalSeconds int32
}

func (q *Queries) InsertCIBARequest(ctx context.Context, arg InsertCIBARequestParams) error {
	_, err := q.db.Exec(ctx, insertCIBARequest,
		arg.AuthReqIDHash,
		arg.ClientID,
		arg.TenantID,
		arg.UserID,
		arg.Scopes,
		arg.BindingMessage,
		arg.IntervalSeconds,
	)
	return err
}

const insertDeviceCode = `-- name: InsertDeviceCode :exec

INSERT INTO auth.oidc_device_codes (
    device_code_hash, user_code, client_id, tenant_id, scopes,
    interval_seconds, expires_at
) VALUES ($1, $2, $3, $4, $5,
          $6, NOW() + INTERVAL '10 minutes')
`

type InsertDeviceCodeParams struct {
	DeviceCodeHash  string
	UserCode        string
	ClientID        string
	TenantID        uuid.UUID
	Scopes          []string
	IntervalSeconds int32
}

// ==========================================================================
// Device Authorization (RFC 8628)
// ==========================================================================
func (q *Queries) InsertDeviceCode(ctx context.Context, arg InsertDeviceCodeParams) error {
	_, err := q.db.Exec(ctx, insertDeviceCode,
		arg.DeviceCodeHash,
		arg.UserCode,
		arg.ClientID,
		arg.TenantID,
		arg.Scopes,
		arg.IntervalSeconds,
	)
	return err
}

const insertOIDCClient = `-- name: InsertOIDCClient :one


INSERT INTO auth.oidc_clients (
    tenant_id, client_id, client_secret_hash, type, name,
    redirect_uris, post_logout_uris, grant_types, scopes
) VALUES ($1, $2, $3, $4, $5,
          $6, $7, $8, $9)
RETURNING id, tenant_id, client_id, type, name, redirect_uris,
          post_logout_uris, grant_types, scopes, created_at
`

type InsertOIDCClientParams struct {
	TenantID         uuid.UUID
	ClientID         string
	ClientSecretHash *string
	Type             string
	Name             string
	RedirectUris     []string
	PostLogoutUris   []string
	GrantTypes       []string
	Scopes           []string
}

type InsertOIDCClientRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ClientID       string
	Type           string
	Name           string
	RedirectUris   []string
	PostLogoutUris []string
	GrantTypes     []string
	Scopes         []string
	CreatedAt      time.Time
}

// Queries for the OIDC domain.
// All queries are STATIC. Dynamic patterns (buildUpdate etc.) do not exist here.
// ==========================================================================
// OIDC clients
// ==========================================================================
func (q *Queries) InsertOIDCClient(ctx context.Context, arg InsertOIDCClientParams) (InsertOIDCClientRow, error) {
	row := q.db.QueryRow(ctx, insertOIDCClient,
		arg.TenantID,
		arg.ClientID,
		arg.ClientSecretHash,
		arg.Type,
		arg.Name,
		arg.RedirectUris,
		arg.PostLogoutUris,
		arg.GrantTypes,
		arg.Scopes,
	)
	var i InsertOIDCClientRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Type,
		&i.Name,
		&i.RedirectUris,
		&i.PostLogoutUris,
		&i.GrantTypes,
		&i.Scopes,
		&i.CreatedAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec

INSERT INTO auth.oidc_refresh_tokens
    (token_hash, client_id, user_id, tenant_id, scopes, expires_at, resource)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertRefreshTokenParams struct {
	TokenHash string
	ClientID  string
	UserID    uuid.UUID
	TenantID  uuid.UUID
	Scopes    []string
	ExpiresAt time.Time
	Resource  *string
}

// ==========================================================================
// Refresh tokens
// ==========================================================================
func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.TokenHash,
		arg.ClientID,
		arg.UserID,
		arg.TenantID,
		arg.Scopes,
		arg.ExpiresAt,
		arg.Resource,
	)
	return err
}

const insertRotatedRefreshToken = `-- name: InsertRotatedRefreshToken :one
INSERT INTO auth.oidc_refresh_tokens
    (token_hash, client_id, user_id, tenant_id, scopes, expires_at, resource)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertRotatedRefreshTokenParams struct {
	TokenHash string
	ClientID  string
	UserID    uuid.UUID
	TenantID  uuid.UUID
	Scopes    []string
	ExpiresAt time.Time
	Resource  *string
}

func (q *Queries) InsertRotatedRefreshToken(ctx context.Context, arg InsertRotatedRefreshTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertRotatedRefreshToken,
		arg.TokenHash,
		arg.ClientID,
		arg.UserID,
		arg.TenantID,
		arg.Scopes,
		arg.ExpiresAt,
		arg.Resource,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listDevices = `-- name: ListDevices :many
SELECT d.id, d.client_id, d.user_code, d.status, d.user_id,
       COALESCE(u.email, '') AS user_email, d.scopes,
       d.created_at, d.expires_at, d.last_polled_at
FROM auth.oidc_device_codes d
LEFT JOIN "user".users u ON u.id = d.user_id
WHERE d.tenant_id = $1
ORDER BY d.created_at DESC
`

type ListDevicesRow struct {
	ID           uuid.UUID
	ClientID     string
	UserCode     string
	Status       string
	UserID       pgtype.UUID
	UserEmail    string
	Scopes       []string
	CreatedAt    time.Time
	ExpiresAt    time.Time
	LastPolledAt pgtype.Timestamptz
}

func (q *Queries) ListDevices(ctx context.Context, tenantID uuid.UUID) ([]ListDevicesRow, error) {
	rows, err := q.db.Query(ctx, listDevices, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDevicesRow{}
	for rows.Next() {
		var i ListDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.UserCode,
			&i.Status,
			&i.UserID,
			&i.UserEmail,
			&i.Scopes,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastPolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrants = `-- name: ListGrants :many
SELECT t.id, t.client_id, t.user_id, COALESCE(u.email, '') AS user_email,
       t.scopes, t.issued_at, t.expires_at
FROM auth.oidc_refresh_tokens t
LEFT JOIN "user".users u ON u.id = t.user_id
WHERE t.tenant_id = $1
  AND t.revoked_at IS NULL AND t.replaced_by IS NULL AND t.expires_at > NOW()
ORDER BY t.issued_at DESC
`

type ListGrantsRow struct {
	ID        uuid.UUID
	ClientID  string
	UserID    uuid.UUID
	UserEmail string
	Scopes    []string
	IssuedAt  time.Time
	ExpiresAt time.Time
}

func (q *Queries) ListGrants(ctx context.Context, tenantID uuid.UUID) ([]ListGrantsRow, error) {
	rows, err := q.db.Query(ctx, listGrants, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGrantsRow{}
	for rows.Next() {
		var i ListGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.UserID,
			&i.UserEmail,
			&i.Scopes,
			&i.IssuedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCClients = `-- name: ListOIDCClients :many
SELECT id, tenant_id, client_id, type, name, redirect_uris,
       post_logout_uris, grant_types, scopes, created_at
FROM auth.oidc_clients WHERE tenant_id = $1 ORDER BY created_at DESC
`

type ListOIDCClientsRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ClientID       string
	Type           string
	Name           string
	RedirectUris   []string
	PostLogoutUris []string
	GrantTypes     []string
	Scopes         []string
	CreatedAt      time.Time
}

func (q *Queries) ListOIDCClients(ctx context.Context, tenantID uuid.UUID) ([]ListOIDCClientsRow, error) {
	rows, err := q.db.Query(ctx, listOIDCClients, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOIDCClientsRow{}
	for rows.Next() {
		var i ListOIDCClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ClientID,
			&i.Type,
			&i.Name,
			&i.RedirectUris,
			&i.PostLogoutUris,
			&i.GrantTypes,
			&i.Scopes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingCIBA = `-- name: ListPendingCIBA :many
SELECT id, client_id, scopes, binding_message, created_at, expires_at
FROM auth.oidc_ciba_requests
WHERE user_id = $1 AND status = 'pending' AND expires_at > NOW()
ORDER BY created_at DESC
`

type ListPendingCIBARow struct {
	ID             uuid.UUID
	ClientID       string
	Scopes         []string
	BindingMessage *string
	CreatedAt      time.Time
	ExpiresAt      time.Time
}

func (q *Queries) ListPendingCIBA(ctx context.Context, userID uuid.UUID) ([]ListPendingCIBARow, error) {
	rows, err := q.db.Query(ctx, listPendingCIBA, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingCIBARow{}
	for rows.Next() {
		var i ListPendingCIBARow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Scopes,
			&i.BindingMessage,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShadowAICandidates = `-- name: ListShadowAICandidates :many
SELECT c.id, c.client_id, c.name, c.grant_types, c.created_at,
       COALESCE(g.live, 0)::bigint AS live_grants
FROM auth.oidc_clients c
LEFT JOIN (
    SELECT client_id, COUNT(*) AS live
    FROM auth.oidc_refresh_tokens
    WHERE revoked_at IS NULL AND expires_at > NOW()
    GROUP BY client_id
) g ON g.client_id = c.client_id
WHERE c.tenant_id = $1
  AND c.reviewed_at IS NULL
  AND c.grant_types && $2::text[]
ORDER BY live_grants DESC, c.created_at DESC
`

type ListShadowAICandidatesParams struct {
	TenantID          uuid.UUID
	MachineGrantTypes []string
}

type ListShadowAICandidatesRow struct {
	ID         uuid.UUID
	ClientID   string
	Name       string
	GrantTypes []string
	CreatedAt  time.Time
	LiveGrants int64
}

func (q *Queries) ListShadowAICandidates(ctx context.Context, arg ListShadowAICandidatesParams) ([]ListShadowAICandidatesRow, error) {
	rows, err := q.db.Query(ctx, listShadowAICandidates, arg.TenantID, arg.MachineGrantTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShadowAICandidatesRow{}
	for rows.Next() {
		var i ListShadowAICandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.GrantTypes,
			&i.CreatedAt,
			&i.LiveGrants,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCIBARequest = `-- name: LockCIBARequest :one
SELECT user_id, status, expires_at
FROM auth.oidc_ciba_requests WHERE id = $1 FOR UPDATE
`

type LockCIBARequestRow struct {
	UserID    uuid.UUID
	Status    string
	ExpiresAt time.Time
}

func (q *Queries) LockCIBARequest(ctx context.Context, id uuid.UUID) (LockCIBARequestRow, error) {
	row := q.db.QueryRow(ctx, lockCIBARequest, id)
	var i LockCIBARequestRow
	err := row.Scan(&i.UserID, &i.Status, &i.ExpiresAt)
	return i, err
}

const lockCIBARequestByHash = `-- name: LockCIBARequestByHash :one
SELECT id, client_id, tenant_id, user_id, scopes, status,
       interval_seconds, last_polled_at, expires_at, consumed_at
FROM auth.oidc_ciba_requests WHERE auth_req_id_hash = $1 FOR UPDATE
`

type LockCIBARequestByHashRow struct {
	ID              uuid.UUID
	ClientID        string
	TenantID        uuid.UUID
	UserID          uuid.UUID
	Scopes          []string
	Status          string
	IntervalSeconds int32
	LastPolledAt    pgtype.Timestamptz
	ExpiresAt       time.Time
	ConsumedAt      pgtype.Timestamptz
}

func (q *Queries) LockCIBARequestByHash(ctx context.Context, authReqIDHash string) (LockCIBARequestByHashRow, error) {
	row := q.db.QueryRow(ctx, lockCIBARequestByHash, authReqIDHash)
	var i LockCIBARequestByHashRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TenantID,
		&i.UserID,
		&i.Scopes,
		&i.Status,
		&i.IntervalSeconds,
		&i.LastPolledAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const lockDeviceByCode = `-- name: LockDeviceByCode :one
SELECT id, client_id, tenant_id, user_id, scopes, status,
       interval_seconds, last_polled_at, expires_at, consumed_at
FROM auth.oidc_device_codes WHERE device_code_hash = $1 FOR UPDATE
`

type LockDeviceByCodeRow struct {
	ID              uuid.UUID
	ClientID        string
	TenantID        uuid.UUID
	UserID          pgtype.UUID
	Scopes          []string
	Status          string
	IntervalSeconds int32
	LastPolledAt    pgtype.Timestamptz
	ExpiresAt       time.Time
	ConsumedAt      pgtype.Timestamptz
}

func (q *Queries) LockDeviceByCode(ctx context.Context, deviceCodeHash string) (LockDeviceByCodeRow, error) {
	row := q.db.QueryRow(ctx, lockDeviceByCode, deviceCodeHash)
	var i LockDeviceByCodeRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TenantID,
		&i.UserID,
		&i.Scopes,
		&i.Status,
		&i.IntervalSeconds,
		&i.LastPolledAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const lockDeviceByUserCode = `-- name: LockDeviceByUserCode :one
SELECT id, client_id, tenant_id, scopes, status, expires_at
FROM auth.oidc_device_codes WHERE user_code = $1 FOR UPDATE
`

type LockDeviceByUserCodeRow struct {
	ID        uuid.UUID
	ClientID  string
	TenantID  uuid.UUID
	Scopes    []string
	Status    string
	ExpiresAt time.Time
}

func (q *Queries) LockDeviceByUserCode(ctx context.Context, userCode string) (LockDeviceByUserCodeRow, error) {
	row := q.db.QueryRow(ctx, lockDeviceByUserCode, userCode)
	var i LockDeviceByUserCodeRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TenantID,
		&i.Scopes,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const lockOIDCClientForUpdate = `-- name: LockOIDCClientForUpdate :one
SELECT id, tenant_id, client_id, type, name, redirect_uris,
       post_logout_uris, grant_types, scopes, created_at
FROM auth.oidc_clients WHERE id = $1 AND tenant_id = $2 FOR UPDATE
`

type LockOIDCClientForUpdateParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type LockOIDCClientForUpdateRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ClientID       string
	Type           string
	Name           string
	RedirectUris   []string
	PostLogoutUris []string
	GrantTypes     []string
	Scopes         []string
	CreatedAt      time.Time
}

func (q *Queries) LockOIDCClientForUpdate(ctx context.Context, arg LockOIDCClientForUpdateParams) (LockOIDCClientForUpdateRow, error) {
	row := q.db.QueryRow(ctx, lockOIDCClientForUpdate, arg.ID, arg.TenantID)
	var i LockOIDCClientForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Type,
		&i.Name,
		&i.RedirectUris,
		&i.PostLogoutUris,
		&i.GrantTypes,
		&i.Scopes,
		&i.CreatedAt,
	)
	return i, err
}

const lockRefreshToken = `-- name: LockRefreshToken :one
SELECT id, client_id, user_id, tenant_id, scopes, expires_at,
       used_at, revoked_at, resource
FROM auth.oidc_refresh_tokens WHERE token_hash = $1 FOR UPDATE
`

type LockRefreshTokenRow struct {
	ID        uuid.UUID
	ClientID  string
	UserID    uuid.UUID
	TenantID  uuid.UUID
	Scopes    []string
	ExpiresAt time.Time
	UsedAt    pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	Resource  *string
}

func (q *Queries) LockRefreshToken(ctx context.Context, tokenHash string) (LockRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, lockRefreshToken, tokenHash)
	var i LockRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.UserID,
		&i.TenantID,
		&i.Scopes,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.Resource,
	)
	return i, err
}

const markAuthorizationCodeUsed = `-- name: MarkAuthorizationCodeUsed :exec
UPDATE auth.oidc_authorization_codes SET used_at = NOW() WHERE code_hash = $1
`

func (q *Queries) MarkAuthorizationCodeUsed(ctx context.Context, codeHash string) error {
	_, err := q.db.Exec(ctx, markAuthorizationCodeUsed, codeHash)
	return err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :exec
UPDATE auth.oidc_refresh_tokens SET used_at = NOW(), replaced_by = $1 WHERE id = $2
`

type MarkRefreshTokenUsedParams struct {
	NewID pgtype.UUID
	ID    uuid.UUID
}

func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markRefreshTokenUsed, arg.NewID, arg.ID)
	return err
}

const reviewOIDCClient = `-- name: ReviewOIDCClient :execrows
UPDATE auth.oidc_clients SET reviewed_at = NOW(), reviewed_by = $1
WHERE id = $2 AND tenant_id = $3
`

type ReviewOIDCClientParams struct {
	ReviewedBy pgtype.UUID
	ID         uuid.UUID
	TenantID   uuid.UUID
}

func (q *Queries) ReviewOIDCClient(ctx context.Context, arg ReviewOIDCClientParams) (int64, error) {
	result, err := q.db.Exec(ctx, reviewOIDCClient, arg.ReviewedBy, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeDevice = `-- name: RevokeDevice :one
UPDATE auth.oidc_device_codes SET status = 'denied'
WHERE id = $1 AND tenant_id = $2
RETURNING client_id, user_code
`

type RevokeDeviceParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type RevokeDeviceRow struct {
	ClientID string
	UserCode string
}

func (q *Queries) RevokeDevice(ctx context.Context, arg RevokeDeviceParams) (RevokeDeviceRow, error) {
	row := q.db.QueryRow(ctx, revokeDevice, arg.ID, arg.TenantID)
	var i RevokeDeviceRow
	err := row.Scan(&i.ClientID, &i.UserCode)
	return i, err
}

const revokeGrantChain = `-- name: RevokeGrantChain :exec
UPDATE auth.oidc_refresh_tokens SET revoked_at = NOW()
WHERE client_id = $1 AND user_id = $2 AND tenant_id = $3
  AND revoked_at IS NULL
`

type RevokeGrantChainParams struct {
	ClientID string
	UserID   uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) RevokeGrantChain(ctx context.Context, arg RevokeGrantChainParams) error {
	_, err := q.db.Exec(ctx, revokeGrantChain, arg.ClientID, arg.UserID, arg.TenantID)
	return err
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :exec
UPDATE auth.oidc_refresh_tokens SET revoked_at = NOW()
WHERE token_hash = $1 AND client_id = $2 AND revoked_at IS NULL
`

type RevokeRefreshTokenByHashParams struct {
	TokenHash string
	ClientID  string
}

func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, arg RevokeRefreshTokenByHashParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenByHash, arg.TokenHash, arg.ClientID)
	return err
}

const revokeRefreshTokenChain = `-- name: RevokeRefreshTokenChain :exec
UPDATE auth.oidc_refresh_tokens SET revoked_at = NOW()
WHERE client_id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeRefreshTokenChainParams struct {
	ClientID string
	UserID   uuid.UUID
}

func (q *Queries) RevokeRefreshTokenChain(ctx context.Context, arg RevokeRefreshTokenChainParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenChain, arg.ClientID, arg.UserID)
	return err
}

const touchCIBAPollTime = `-- name: TouchCIBAPollTime :exec
UPDATE auth.oidc_ciba_requests SET last_polled_at = NOW() WHERE id = $1
`

func (q *Queries) TouchCIBAPollTime(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchCIBAPollTime, id)
	return err
}

const touchDevicePollTime = `-- name: TouchDevicePollTime :exec
UPDATE auth.oidc_device_codes SET last_polled_at = NOW() WHERE id = $1
`

func (q *Queries) TouchDevicePollTime(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchDevicePollTime, id)
	return err
}

const updateOIDCClient = `-- name: UpdateOIDCClient :one
UPDATE auth.oidc_clients SET
    name             = COALESCE($1, name),
    redirect_uris    = COALESCE($2, redirect_uris),
    post_logout_uris = COALESCE($3, post_logout_uris),
    grant_types      = COALESCE($4, grant_types),
    scopes           = COALESCE($5, scopes)
WHERE id = $6 AND tenant_id = $7
RETURNING id, tenant_id, client_id, type, name, redirect_uris,
          post_logout_uris, grant_types, scopes, created_at
`

type UpdateOIDCClientParams struct {
	Name           *string
	RedirectUris   []string
	PostLogoutUris []string
	GrantTypes     []string
	Scopes         []string
	ID             uuid.UUID
	TenantID       uuid.UUID
}

type UpdateOIDCClientRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ClientID       string
	Type           string
	Name           string
	RedirectUris   []string
	PostLogoutUris []string
	GrantTypes     []string
	Scopes         []string
	CreatedAt      time.Time
}

func (q *Queries) UpdateOIDCClient(ctx context.Context, arg UpdateOIDCClientParams) (UpdateOIDCClientRow, error) {
	row := q.db.QueryRow(ctx, updateOIDCClient,
		arg.Name,
		arg.RedirectUris,
		arg.PostLogoutUris,
		arg.GrantTypes,
		arg.Scopes,
		arg.ID,
		arg.TenantID,
	)
	var i UpdateOIDCClientRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Type,
		&i.Name,
		&i.RedirectUris,
		&i.PostLogoutUris,
		&i.GrantTypes,
		&i.Scopes,
		&i.CreatedAt,
	)
	return i, err
}

const updateOIDCClientSecret = `-- name: UpdateOIDCClientSecret :exec
UPDATE auth.oidc_clients SET client_secret_hash = $1
WHERE id = $2 AND tenant_id = $3
`

type UpdateOIDCClientSecretParams struct {
	ClientSecretHash *string
	ID               uuid.UUID
	TenantID         uuid.UUID
}

func (q *Queries) UpdateOIDCClientSecret(ctx context.Context, arg UpdateOIDCClientSecretParams) error {
	_, err := q.db.Exec(ctx, updateOIDCClientSecret, arg.ClientSecretHash, arg.ID, arg.TenantID)
	return err
}

const upsertConsent = `-- name: UpsertConsent :exec
INSERT INTO auth.oidc_consents (user_id, client_id, scopes, granted_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (user_id, client_id) DO UPDATE SET scopes = EXCLUDED.scopes, granted_at = NOW()
`

type UpsertConsentParams struct {
	UserID   uuid.UUID
	ClientID string
	Scopes   []string
}

func (q *Queries) UpsertConsent(ctx context.Context, arg UpsertConsentParams) error {
	_, err := q.db.Exec(ctx, upsertConsent, arg.UserID, arg.ClientID, arg.Scopes)
	return err
}
