// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAuditChainTip = `-- name: GetAuditChainTip :one

SELECT row_hash FROM audit.events
WHERE tenant_id IS NOT DISTINCT FROM $1
  AND row_hash IS NOT NULL
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// Queries for the audit domain.
//
// The hash-chained append-only audit log.  Static queries are here; dynamic
// ones stay hand-written in the respective .go files:
//   - Reader.List (http.go): dynamic WHERE clause with optional action, resource
//     type, actor, free-text search, and cursor filters.
//   - Record advisory-lock call (audit.go): pg_advisory_xact_lock is a
//     void-returning side-effect function; it stays as a raw tx.Exec call.
//
// Fetch the most recent row_hash for a tenant's (or the platform) chain.
// Called by Record() inside the caller's transaction to chain the next row.
// tenant_id = NULL means the platform chain (NULL IS NOT DISTINCT FROM NULL).
func (q *Queries) GetAuditChainTip(ctx context.Context, tenantID pgtype.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getAuditChainTip, tenantID)
	var row_hash *string
	err := row.Scan(&row_hash)
	return row_hash, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit.events (
    id, tenant_id, actor_user_id, actor_type, action,
    resource_type, resource_id, ip, user_agent, request_id,
    metadata, created_at, prev_hash, row_hash
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, NULLIF($8, '')::inet, $9, $10,
    $11, $12, $13, $14
)
`

type InsertAuditEventParams struct {
	ID           uuid.UUID
	TenantID     pgtype.UUID
	ActorUserID  pgtype.UUID
	ActorType    string
	Action       string
	ResourceType string
	ResourceID   pgtype.UUID
	Ip           interface{}
	UserAgent    *string
	RequestID    *string
	Metadata     []byte
	CreatedAt    time.Time
	PrevHash     *string
	RowHash      *string
}

// Append one row to the hash-chained audit log.  Column order matches the
// canonicalRow struct in audit.go — never reorder.  ip is stored as inet;
// NULLIF converts an empty string to NULL before the cast so empty IPs are
// stored cleanly rather than causing a parse error.
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ID,
		arg.TenantID,
		arg.ActorUserID,
		arg.ActorType,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Ip,
		arg.UserAgent,
		arg.RequestID,
		arg.Metadata,
		arg.CreatedAt,
		arg.PrevHash,
		arg.RowHash,
	)
	return err
}

const listAuditEventsForVerify = `-- name: ListAuditEventsForVerify :many
SELECT id, tenant_id, actor_user_id, actor_type, action,
       resource_type, resource_id,
       COALESCE(host(ip), '') AS ip,
       COALESCE(user_agent, '') AS user_agent,
       COALESCE(request_id, '') AS request_id,
       metadata,
       created_at,
       prev_hash, row_hash
FROM audit.events
WHERE tenant_id IS NOT DISTINCT FROM $1
  AND row_hash IS NOT NULL
ORDER BY created_at ASC, id ASC
`

type ListAuditEventsForVerifyRow struct {
	ID           uuid.UUID
	TenantID     pgtype.UUID
	ActorUserID  pgtype.UUID
	ActorType    string
	Action       string
	ResourceType string
	ResourceID   pgtype.UUID
	Ip           interface{}
	UserAgent    string
	RequestID    string
	Metadata     []byte
	CreatedAt    time.Time
	PrevHash     *string
	RowHash      *string
}

// Walk the chain in chronological insert order for hash-chain verification.
// Only rows with non-NULL hashes (post-hash-chain migration) are returned.
// COALESCE on optional fields ensures the canonical bytes match what Record
// wrote at insert time regardless of how Postgres stored the values.
func (q *Queries) ListAuditEventsForVerify(ctx context.Context, tenantID pgtype.UUID) ([]ListAuditEventsForVerifyRow, error) {
	rows, err := q.db.Query(ctx, listAuditEventsForVerify, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditEventsForVerifyRow{}
	for rows.Next() {
		var i ListAuditEventsForVerifyRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorUserID,
			&i.ActorType,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Ip,
			&i.UserAgent,
			&i.RequestID,
			&i.Metadata,
			&i.CreatedAt,
			&i.PrevHash,
			&i.RowHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
