// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deviceSeenBefore = `-- name: DeviceSeenBefore :one
SELECT EXISTS(
    SELECT 1 FROM auth.login_context_history
    WHERE tenant_id = $1 AND user_id = $2 AND device_key = $3
) AS exists
`

type DeviceSeenBeforeParams struct {
	TenantID  uuid.UUID
	UserID    uuid.UUID
	DeviceKey string
}

func (q *Queries) DeviceSeenBefore(ctx context.Context, arg DeviceSeenBeforeParams) (bool, error) {
	row := q.db.QueryRow(ctx, deviceSeenBefore, arg.TenantID, arg.UserID, arg.DeviceKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getLastCountry = `-- name: GetLastCountry :one
SELECT country, seen_at FROM auth.login_context_history
WHERE tenant_id = $1 AND user_id = $2 AND country IS NOT NULL AND country <> ''
ORDER BY seen_at DESC LIMIT 1
`

type GetLastCountryParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

type GetLastCountryRow struct {
	Country *string
	SeenAt  time.Time
}

func (q *Queries) GetLastCountry(ctx context.Context, arg GetLastCountryParams) (GetLastCountryRow, error) {
	row := q.db.QueryRow(ctx, getLastCountry, arg.TenantID, arg.UserID)
	var i GetLastCountryRow
	err := row.Scan(&i.Country, &i.SeenAt)
	return i, err
}

const getRiskSettings = `-- name: GetRiskSettings :one

SELECT medium_threshold, high_threshold, force_mfa_at_level,
       impossible_travel_enabled, min_travel_hours, device_reputation_enabled
FROM auth.risk_settings WHERE tenant_id = $1
`

type GetRiskSettingsRow struct {
	MediumThreshold         float64
	HighThreshold           float64
	ForceMfaAtLevel         string
	ImpossibleTravelEnabled bool
	MinTravelHours          float64
	DeviceReputationEnabled bool
}

// Queries for the threat-detection/risk domain.
// All queries are static and compiled by sqlc into ./dbgen.
func (q *Queries) GetRiskSettings(ctx context.Context, tenantID uuid.UUID) (GetRiskSettingsRow, error) {
	row := q.db.QueryRow(ctx, getRiskSettings, tenantID)
	var i GetRiskSettingsRow
	err := row.Scan(
		&i.MediumThreshold,
		&i.HighThreshold,
		&i.ForceMfaAtLevel,
		&i.ImpossibleTravelEnabled,
		&i.MinTravelHours,
		&i.DeviceReputationEnabled,
	)
	return i, err
}

const insertLoginContext = `-- name: InsertLoginContext :exec
INSERT INTO auth.login_context_history (tenant_id, user_id, device_key, country)
VALUES ($1, $2, $3, $4)
`

type InsertLoginContextParams struct {
	TenantID  uuid.UUID
	UserID    uuid.UUID
	DeviceKey string
	Country   *string
}

func (q *Queries) InsertLoginContext(ctx context.Context, arg InsertLoginContextParams) error {
	_, err := q.db.Exec(ctx, insertLoginContext,
		arg.TenantID,
		arg.UserID,
		arg.DeviceKey,
		arg.Country,
	)
	return err
}

const upsertRiskSettings = `-- name: UpsertRiskSettings :exec
INSERT INTO auth.risk_settings (
    tenant_id, medium_threshold, high_threshold, force_mfa_at_level,
    impossible_travel_enabled, min_travel_hours, device_reputation_enabled, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
ON CONFLICT (tenant_id) DO UPDATE SET
    medium_threshold           = EXCLUDED.medium_threshold,
    high_threshold             = EXCLUDED.high_threshold,
    force_mfa_at_level         = EXCLUDED.force_mfa_at_level,
    impossible_travel_enabled  = EXCLUDED.impossible_travel_enabled,
    min_travel_hours           = EXCLUDED.min_travel_hours,
    device_reputation_enabled  = EXCLUDED.device_reputation_enabled,
    updated_at                 = NOW()
`

type UpsertRiskSettingsParams struct {
	TenantID                uuid.UUID
	MediumThreshold         float64
	HighThreshold           float64
	ForceMfaAtLevel         string
	ImpossibleTravelEnabled bool
	MinTravelHours          float64
	DeviceReputationEnabled bool
}

func (q *Queries) UpsertRiskSettings(ctx context.Context, arg UpsertRiskSettingsParams) error {
	_, err := q.db.Exec(ctx, upsertRiskSettings,
		arg.TenantID,
		arg.MediumThreshold,
		arg.HighThreshold,
		arg.ForceMfaAtLevel,
		arg.ImpossibleTravelEnabled,
		arg.MinTravelHours,
		arg.DeviceReputationEnabled,
	)
	return err
}
