// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthMfaOtpFactor struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Channel     string
	Destination string
	VerifiedAt  pgtype.Timestamptz
	CreatedAt   time.Time
}
