// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmMFATOTP = `-- name: ConfirmMFATOTP :exec
UPDATE auth.mfa_totp SET confirmed_at = NOW() WHERE user_id = $1
`

func (q *Queries) ConfirmMFATOTP(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, confirmMFATOTP, userID)
	return err
}

const deleteMFAOTPFactors = `-- name: DeleteMFAOTPFactors :exec
DELETE FROM auth.mfa_otp_factors WHERE user_id = $1
`

func (q *Queries) DeleteMFAOTPFactors(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMFAOTPFactors, userID)
	return err
}

const deleteMFARecoveryCodes = `-- name: DeleteMFARecoveryCodes :exec
DELETE FROM auth.mfa_recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteMFARecoveryCodes(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMFARecoveryCodes, userID)
	return err
}

const deleteMFATOTP = `-- name: DeleteMFATOTP :exec
DELETE FROM auth.mfa_totp WHERE user_id = $1
`

func (q *Queries) DeleteMFATOTP(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMFATOTP, userID)
	return err
}

const deleteOTPFactor = `-- name: DeleteOTPFactor :execrows
DELETE FROM auth.mfa_otp_factors WHERE id = $1 AND user_id = $2
`

type DeleteOTPFactorParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteOTPFactor(ctx context.Context, arg DeleteOTPFactorParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOTPFactor, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMFARecoveryCodeStats = `-- name: GetMFARecoveryCodeStats :one
SELECT
    count(*)                             AS total,
    count(*) FILTER (WHERE used_at IS NULL) AS remaining
FROM auth.mfa_recovery_codes WHERE user_id = $1
`

type GetMFARecoveryCodeStatsRow struct {
	Total     int64
	Remaining int64
}

func (q *Queries) GetMFARecoveryCodeStats(ctx context.Context, userID uuid.UUID) (GetMFARecoveryCodeStatsRow, error) {
	row := q.db.QueryRow(ctx, getMFARecoveryCodeStats, userID)
	var i GetMFARecoveryCodeStatsRow
	err := row.Scan(&i.Total, &i.Remaining)
	return i, err
}

const getMFATOTPConfirmed = `-- name: GetMFATOTPConfirmed :one

SELECT confirmed_at FROM auth.mfa_totp WHERE user_id = $1
`

// GetMFATOTPConfirmed returns confirmed_at (nullable). Callers check .Valid to test
// enrollment. Returning the full timestamp avoids sqlc's interface{} inference for
// IS NOT NULL expressions.
func (q *Queries) GetMFATOTPConfirmed(ctx context.Context, userID uuid.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getMFATOTPConfirmed, userID)
	var confirmed_at pgtype.Timestamptz
	err := row.Scan(&confirmed_at)
	return confirmed_at, err
}

const getMFATOTPFull = `-- name: GetMFATOTPFull :one

SELECT secret, confirmed_at FROM auth.mfa_totp WHERE user_id = $1
`

type GetMFATOTPFullRow struct {
	Secret      string
	ConfirmedAt pgtype.Timestamptz
}

// GetMFATOTPFull returns the secret and confirmed_at for the Verify path.
func (q *Queries) GetMFATOTPFull(ctx context.Context, userID uuid.UUID) (GetMFATOTPFullRow, error) {
	row := q.db.QueryRow(ctx, getMFATOTPFull, userID)
	var i GetMFATOTPFullRow
	err := row.Scan(&i.Secret, &i.ConfirmedAt)
	return i, err
}

const getMFATOTPSecret = `-- name: GetMFATOTPSecret :one
SELECT secret FROM auth.mfa_totp WHERE user_id = $1
`

func (q *Queries) GetMFATOTPSecret(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getMFATOTPSecret, userID)
	var secret string
	err := row.Scan(&secret)
	return secret, err
}

const getMFAVerification = `-- name: GetMFAVerification :one
SELECT verified_at FROM auth.mfa_verifications WHERE user_id = $1
`

func (q *Queries) GetMFAVerification(ctx context.Context, userID uuid.UUID) (time.Time, error) {
	row := q.db.QueryRow(ctx, getMFAVerification, userID)
	var verified_at time.Time
	err := row.Scan(&verified_at)
	return verified_at, err
}

const getOTPCodeForConfirm = `-- name: GetOTPCodeForConfirm :one

SELECT c.id
FROM auth.mfa_otp_codes c
JOIN auth.mfa_otp_factors f ON f.id = c.factor_id
WHERE f.id = $1 AND f.user_id = $2 AND c.code_hash = $3
  AND c.used_at IS NULL AND c.expires_at > NOW()
ORDER BY c.created_at DESC LIMIT 1
FOR UPDATE
`

type GetOTPCodeForConfirmParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	CodeHash string
}

// GetOTPCodeForConfirm fetches a single pending OTP code for the EnrollOTPConfirm path.
func (q *Queries) GetOTPCodeForConfirm(ctx context.Context, arg GetOTPCodeForConfirmParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getOTPCodeForConfirm, arg.ID, arg.UserID, arg.CodeHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getOTPCodeForVerify = `-- name: GetOTPCodeForVerify :one

SELECT c.id
FROM auth.mfa_otp_codes c
JOIN auth.mfa_otp_factors f ON f.id = c.factor_id
WHERE f.user_id = $1 AND f.verified_at IS NOT NULL AND c.code_hash = $2
  AND c.used_at IS NULL AND c.expires_at > NOW()
ORDER BY c.created_at DESC LIMIT 1
FOR UPDATE
`

type GetOTPCodeForVerifyParams struct {
	UserID   uuid.UUID
	CodeHash string
}

// GetOTPCodeForVerify finds a pending OTP code for any verified factor of the user.
func (q *Queries) GetOTPCodeForVerify(ctx context.Context, arg GetOTPCodeForVerifyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getOTPCodeForVerify, arg.UserID, arg.CodeHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getOTPFactorForChallenge = `-- name: GetOTPFactorForChallenge :one
SELECT channel, destination, verified_at
FROM auth.mfa_otp_factors WHERE id = $1 AND user_id = $2
`

type GetOTPFactorForChallengeParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetOTPFactorForChallengeRow struct {
	Channel     string
	Destination string
	VerifiedAt  pgtype.Timestamptz
}

func (q *Queries) GetOTPFactorForChallenge(ctx context.Context, arg GetOTPFactorForChallengeParams) (GetOTPFactorForChallengeRow, error) {
	row := q.db.QueryRow(ctx, getOTPFactorForChallenge, arg.ID, arg.UserID)
	var i GetOTPFactorForChallengeRow
	err := row.Scan(&i.Channel, &i.Destination, &i.VerifiedAt)
	return i, err
}

const insertMFAOTPCode = `-- name: InsertMFAOTPCode :exec
INSERT INTO auth.mfa_otp_codes (factor_id, code_hash, expires_at)
VALUES ($1, $2, $3)
`

type InsertMFAOTPCodeParams struct {
	FactorID  uuid.UUID
	CodeHash  string
	ExpiresAt time.Time
}

func (q *Queries) InsertMFAOTPCode(ctx context.Context, arg InsertMFAOTPCodeParams) error {
	_, err := q.db.Exec(ctx, insertMFAOTPCode, arg.FactorID, arg.CodeHash, arg.ExpiresAt)
	return err
}

const insertMFARecoveryCode = `-- name: InsertMFARecoveryCode :exec
INSERT INTO auth.mfa_recovery_codes (user_id, code_hash) VALUES ($1, $2)
`

type InsertMFARecoveryCodeParams struct {
	UserID   uuid.UUID
	CodeHash string
}

func (q *Queries) InsertMFARecoveryCode(ctx context.Context, arg InsertMFARecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, insertMFARecoveryCode, arg.UserID, arg.CodeHash)
	return err
}

const listOTPFactors = `-- name: ListOTPFactors :many
SELECT id, user_id, channel, destination, verified_at, created_at
FROM auth.mfa_otp_factors WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListOTPFactors(ctx context.Context, userID uuid.UUID) ([]AuthMfaOtpFactor, error) {
	rows, err := q.db.Query(ctx, listOTPFactors, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthMfaOtpFactor{}
	for rows.Next() {
		var i AuthMfaOtpFactor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Channel,
			&i.Destination,
			&i.VerifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnusedRecoveryCodes = `-- name: ListUnusedRecoveryCodes :many
SELECT id, code_hash FROM auth.mfa_recovery_codes
WHERE user_id = $1 AND used_at IS NULL
`

type ListUnusedRecoveryCodesRow struct {
	ID       uuid.UUID
	CodeHash string
}

func (q *Queries) ListUnusedRecoveryCodes(ctx context.Context, userID uuid.UUID) ([]ListUnusedRecoveryCodesRow, error) {
	rows, err := q.db.Query(ctx, listUnusedRecoveryCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnusedRecoveryCodesRow{}
	for rows.Next() {
		var i ListUnusedRecoveryCodesRow
		if err := rows.Scan(&i.ID, &i.CodeHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOTPCodeUsed = `-- name: MarkOTPCodeUsed :exec
UPDATE auth.mfa_otp_codes SET used_at = NOW() WHERE id = $1
`

func (q *Queries) MarkOTPCodeUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOTPCodeUsed, id)
	return err
}

const markOTPFactorVerified = `-- name: MarkOTPFactorVerified :exec
UPDATE auth.mfa_otp_factors SET verified_at = NOW() WHERE id = $1
`

func (q *Queries) MarkOTPFactorVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOTPFactorVerified, id)
	return err
}

const markRecoveryCodeUsed = `-- name: MarkRecoveryCodeUsed :exec
UPDATE auth.mfa_recovery_codes SET used_at = NOW() WHERE id = $1
`

func (q *Queries) MarkRecoveryCodeUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markRecoveryCodeUsed, id)
	return err
}

const upsertMFAOTPFactor = `-- name: UpsertMFAOTPFactor :one
INSERT INTO auth.mfa_otp_factors (user_id, channel, destination)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, channel, destination) DO UPDATE SET verified_at = NULL
RETURNING id
`

type UpsertMFAOTPFactorParams struct {
	UserID      uuid.UUID
	Channel     string
	Destination string
}

func (q *Queries) UpsertMFAOTPFactor(ctx context.Context, arg UpsertMFAOTPFactorParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertMFAOTPFactor, arg.UserID, arg.Channel, arg.Destination)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertMFATOTP = `-- name: UpsertMFATOTP :exec

INSERT INTO auth.mfa_totp (user_id, secret) VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET secret = EXCLUDED.secret, confirmed_at = NULL
`

type UpsertMFATOTPParams struct {
	UserID uuid.UUID
	Secret string
}

// Queries for the access/mfa domain.
// All static queries are compiled by sqlc into ./dbgen.
func (q *Queries) UpsertMFATOTP(ctx context.Context, arg UpsertMFATOTPParams) error {
	_, err := q.db.Exec(ctx, upsertMFATOTP, arg.UserID, arg.Secret)
	return err
}

const upsertMFAVerification = `-- name: UpsertMFAVerification :exec
INSERT INTO auth.mfa_verifications (user_id, method, verified_at)
VALUES ($1, $2, NOW())
ON CONFLICT (user_id) DO UPDATE SET method = EXCLUDED.method, verified_at = NOW()
`

type UpsertMFAVerificationParams struct {
	UserID uuid.UUID
	Method string
}

func (q *Queries) UpsertMFAVerification(ctx context.Context, arg UpsertMFAVerificationParams) error {
	_, err := q.db.Exec(ctx, upsertMFAVerification, arg.UserID, arg.Method)
	return err
}
