// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteConnectState = `-- name: DeleteConnectState :one
DELETE FROM tenant.token_vault_connect_states WHERE state = $1
RETURNING tenant_id, user_id, provider, expires_at
`

type DeleteConnectStateRow struct {
	TenantID  uuid.UUID
	UserID    uuid.UUID
	Provider  string
	ExpiresAt time.Time
}

// DeleteConnectState atomically consumes the single-use state for the
// FinishConnect ceremony (DELETE … RETURNING validates and consumes in one shot).
func (q *Queries) DeleteConnectState(ctx context.Context, state string) (DeleteConnectStateRow, error) {
	row := q.db.QueryRow(ctx, deleteConnectState, state)
	var i DeleteConnectStateRow
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Provider,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteGrant = `-- name: DeleteGrant :execrows
DELETE FROM tenant.token_vault_grants
WHERE tenant_id = $1 AND user_id = $2 AND provider = $3
`

type DeleteGrantParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
	Provider string
}

func (q *Queries) DeleteGrant(ctx context.Context, arg DeleteGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGrant, arg.TenantID, arg.UserID, arg.Provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProvider = `-- name: DeleteProvider :execrows
DELETE FROM tenant.token_vault_providers WHERE tenant_id = $1 AND provider = $2
`

type DeleteProviderParams struct {
	TenantID uuid.UUID
	Provider string
}

func (q *Queries) DeleteProvider(ctx context.Context, arg DeleteProviderParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProvider, arg.TenantID, arg.Provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProviderConfig = `-- name: GetProviderConfig :one
SELECT client_id, client_secret, authorize_url, token_url, scopes
FROM tenant.token_vault_providers WHERE tenant_id = $1 AND provider = $2
`

type GetProviderConfigParams struct {
	TenantID uuid.UUID
	Provider string
}

type GetProviderConfigRow struct {
	ClientID     string
	ClientSecret string
	AuthorizeUrl string
	TokenUrl     string
	Scopes       string
}

// GetProviderConfig fetches full config including client_secret for the
// token-exchange; client_secret is never surfaced to end users.
func (q *Queries) GetProviderConfig(ctx context.Context, arg GetProviderConfigParams) (GetProviderConfigRow, error) {
	row := q.db.QueryRow(ctx, getProviderConfig, arg.TenantID, arg.Provider)
	var i GetProviderConfigRow
	err := row.Scan(
		&i.ClientID,
		&i.ClientSecret,
		&i.AuthorizeUrl,
		&i.TokenUrl,
		&i.Scopes,
	)
	return i, err
}

const getTokenGrant = `-- name: GetTokenGrant :one
SELECT access_token_ct, access_token_nonce, refresh_token_ct, refresh_token_nonce, expires_at
FROM tenant.token_vault_grants
WHERE tenant_id = $1 AND user_id = $2 AND provider = $3
`

type GetTokenGrantParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
	Provider string
}

type GetTokenGrantRow struct {
	AccessTokenCt     []byte
	AccessTokenNonce  []byte
	RefreshTokenCt    []byte
	RefreshTokenNonce []byte
	ExpiresAt         pgtype.Timestamptz
}

func (q *Queries) GetTokenGrant(ctx context.Context, arg GetTokenGrantParams) (GetTokenGrantRow, error) {
	row := q.db.QueryRow(ctx, getTokenGrant, arg.TenantID, arg.UserID, arg.Provider)
	var i GetTokenGrantRow
	err := row.Scan(
		&i.AccessTokenCt,
		&i.AccessTokenNonce,
		&i.RefreshTokenCt,
		&i.RefreshTokenNonce,
		&i.ExpiresAt,
	)
	return i, err
}

const insertConnectState = `-- name: InsertConnectState :exec
INSERT INTO tenant.token_vault_connect_states (state, tenant_id, user_id, provider, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertConnectStateParams struct {
	State     string
	TenantID  uuid.UUID
	UserID    uuid.UUID
	Provider  string
	ExpiresAt time.Time
}

func (q *Queries) InsertConnectState(ctx context.Context, arg InsertConnectStateParams) error {
	_, err := q.db.Exec(ctx, insertConnectState,
		arg.State,
		arg.TenantID,
		arg.UserID,
		arg.Provider,
		arg.ExpiresAt,
	)
	return err
}

const listGrants = `-- name: ListGrants :many
SELECT provider, external_account_id, scope, expires_at, created_at, updated_at
FROM tenant.token_vault_grants
WHERE tenant_id = $1 AND user_id = $2 ORDER BY provider
`

type ListGrantsParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

type ListGrantsRow struct {
	Provider          string
	ExternalAccountID *string
	Scope             *string
	ExpiresAt         pgtype.Timestamptz
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) ListGrants(ctx context.Context, arg ListGrantsParams) ([]ListGrantsRow, error) {
	rows, err := q.db.Query(ctx, listGrants, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGrantsRow{}
	for rows.Next() {
		var i ListGrantsRow
		if err := rows.Scan(
			&i.Provider,
			&i.ExternalAccountID,
			&i.Scope,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviders = `-- name: ListProviders :many
SELECT id, provider, client_id, authorize_url, token_url, scopes, created_at, updated_at
FROM tenant.token_vault_providers WHERE tenant_id = $1 ORDER BY provider
`

type ListProvidersRow struct {
	ID           uuid.UUID
	Provider     string
	ClientID     string
	AuthorizeUrl string
	TokenUrl     string
	Scopes       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) ListProviders(ctx context.Context, tenantID uuid.UUID) ([]ListProvidersRow, error) {
	rows, err := q.db.Query(ctx, listProviders, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProvidersRow{}
	for rows.Next() {
		var i ListProvidersRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ClientID,
			&i.AuthorizeUrl,
			&i.TokenUrl,
			&i.Scopes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerProvider = `-- name: RegisterProvider :one

INSERT INTO tenant.token_vault_providers (tenant_id, provider, client_id, client_secret, authorize_url, token_url, scopes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tenant_id, provider) DO UPDATE SET
    client_id = EXCLUDED.client_id, client_secret = EXCLUDED.client_secret,
    authorize_url = EXCLUDED.authorize_url, token_url = EXCLUDED.token_url,
    scopes = EXCLUDED.scopes, updated_at = NOW()
RETURNING id, provider, client_id, authorize_url, token_url, scopes, created_at, updated_at
`

type RegisterProviderParams struct {
	TenantID     uuid.UUID
	Provider     string
	ClientID     string
	ClientSecret string
	AuthorizeUrl string
	TokenUrl     string
	Scopes       string
}

type RegisterProviderRow struct {
	ID           uuid.UUID
	Provider     string
	ClientID     string
	AuthorizeUrl string
	TokenUrl     string
	Scopes       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// Queries for the token-vault domain.
// storeGrant (upsert with nullable []byte params) is converted below using
// pointer types; the encrypt/decrypt/HTTP-exchange logic stays in the Service.
func (q *Queries) RegisterProvider(ctx context.Context, arg RegisterProviderParams) (RegisterProviderRow, error) {
	row := q.db.QueryRow(ctx, registerProvider,
		arg.TenantID,
		arg.Provider,
		arg.ClientID,
		arg.ClientSecret,
		arg.AuthorizeUrl,
		arg.TokenUrl,
		arg.Scopes,
	)
	var i RegisterProviderRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ClientID,
		&i.AuthorizeUrl,
		&i.TokenUrl,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTokenGrant = `-- name: UpsertTokenGrant :exec
INSERT INTO tenant.token_vault_grants
    (tenant_id, user_id, provider, access_token_ct, access_token_nonce,
     refresh_token_ct, refresh_token_nonce, token_type, scope, expires_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9, $10)
ON CONFLICT (tenant_id, user_id, provider) DO UPDATE SET
    access_token_ct = EXCLUDED.access_token_ct,
    access_token_nonce = EXCLUDED.access_token_nonce,
    refresh_token_ct = COALESCE(EXCLUDED.refresh_token_ct, tenant.token_vault_grants.refresh_token_ct),
    refresh_token_nonce = COALESCE(EXCLUDED.refresh_token_nonce, tenant.token_vault_grants.refresh_token_nonce),
    token_type = EXCLUDED.token_type,
    scope = EXCLUDED.scope,
    expires_at = EXCLUDED.expires_at,
    updated_at = NOW()
`

type UpsertTokenGrantParams struct {
	TenantID          uuid.UUID
	UserID            uuid.UUID
	Provider          string
	AccessTokenCt     []byte
	AccessTokenNonce  []byte
	RefreshTokenCt    []byte
	RefreshTokenNonce []byte
	TokenType         string
	Scope             *string
	ExpiresAt         pgtype.Timestamptz
}

// UpsertTokenGrant writes (or refreshes) a connected account's token pair.
// refresh_token_ct / refresh_token_nonce are nullable: NULL means "no refresh
// token" on insert; COALESCE preserves the existing one on update when the
// provider omits it from the refresh response.
func (q *Queries) UpsertTokenGrant(ctx context.Context, arg UpsertTokenGrantParams) error {
	_, err := q.db.Exec(ctx, upsertTokenGrant,
		arg.TenantID,
		arg.UserID,
		arg.Provider,
		arg.AccessTokenCt,
		arg.AccessTokenNonce,
		arg.RefreshTokenCt,
		arg.RefreshTokenNonce,
		arg.TokenType,
		arg.Scope,
		arg.ExpiresAt,
	)
	return err
}
