// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adoptHomeTenant = `-- name: AdoptHomeTenant :exec
UPDATE "user".users SET tenant_id = $1::uuid, updated_at = NOW()
WHERE id = $2 AND tenant_id IS NULL AND deleted_at IS NULL
`

type AdoptHomeTenantParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) AdoptHomeTenant(ctx context.Context, arg AdoptHomeTenantParams) error {
	_, err := q.db.Exec(ctx, adoptHomeTenant, arg.TenantID, arg.ID)
	return err
}

const getTenant = `-- name: GetTenant :one

SELECT id, slug, name, status, plan, region, metadata, created_at, updated_at, deleted_at FROM tenant.tenants
WHERE id = $1 AND deleted_at IS NULL
`

// Queries for the organizations (tenant) domain.
// Static queries against tenant.tenants live here and are compiled by sqlc into ./dbgen.
// Dynamic queries (partial UPDATE) intentionally remain hand-written in repository.go.
func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (TenantTenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i TenantTenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Plan,
		&i.Region,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, slug, name, status, plan, region, metadata, created_at, updated_at, deleted_at FROM tenant.tenants
WHERE LOWER(slug) = LOWER($1) AND deleted_at IS NULL
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (TenantTenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i TenantTenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Plan,
		&i.Region,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const grantAllPermissionsToRole = `-- name: GrantAllPermissionsToRole :exec
INSERT INTO rbac.role_permissions (role_id, permission_id)
SELECT $1, id FROM rbac.permissions
`

func (q *Queries) GrantAllPermissionsToRole(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, grantAllPermissionsToRole, roleID)
	return err
}

const grantRoleToUser = `-- name: GrantRoleToUser :exec
INSERT INTO rbac.user_roles (user_id, tenant_id, role_id, granted_by)
VALUES ($1, $2, $3, $1)
`

type GrantRoleToUserParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
	RoleID   uuid.UUID
}

func (q *Queries) GrantRoleToUser(ctx context.Context, arg GrantRoleToUserParams) error {
	_, err := q.db.Exec(ctx, grantRoleToUser, arg.UserID, arg.TenantID, arg.RoleID)
	return err
}

const insertOwnerRole = `-- name: InsertOwnerRole :one

INSERT INTO rbac.roles (tenant_id, name, description, is_system)
VALUES ($1, 'owner', 'Tenant owner — full access', TRUE)
RETURNING id
`

// The next four queries are the static, cross-context writes of CreateWithOwner.
// They target other bounded contexts (rbac.*, "user".users) but are fixed SQL with
// positional binds, so they compile under the shared migration schema and run on the
// caller's shared pgx.Tx via r.q.WithTx(tx).X(...).
func (q *Queries) InsertOwnerRole(ctx context.Context, tenantID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertOwnerRole, tenantID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertTenant = `-- name: InsertTenant :one
INSERT INTO tenant.tenants (slug, name, plan, region, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, slug, name, status, plan, region, metadata, created_at, updated_at, deleted_at
`

type InsertTenantParams struct {
	Slug     string
	Name     string
	Plan     string
	Region   string
	Metadata []byte
}

func (q *Queries) InsertTenant(ctx context.Context, arg InsertTenantParams) (TenantTenant, error) {
	row := q.db.QueryRow(ctx, insertTenant,
		arg.Slug,
		arg.Name,
		arg.Plan,
		arg.Region,
		arg.Metadata,
	)
	var i TenantTenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Plan,
		&i.Region,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTenantsForUser = `-- name: ListTenantsForUser :many

SELECT id, slug, name, status, plan, region, metadata, created_at, updated_at, deleted_at FROM tenant.tenants
WHERE deleted_at IS NULL
  AND EXISTS (
    SELECT 1 FROM rbac.user_roles ur
    WHERE ur.tenant_id = tenant.tenants.id AND ur.user_id = $1
  )
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListTenantsForUserParams struct {
	UserID uuid.UUID
	Limit  int32
}

// List the tenants a user is a member of, newest first. Cursor pagination is split
// into a first-page and after-cursor variant (the idiomatic sqlc way to do dynamic paging).
func (q *Queries) ListTenantsForUser(ctx context.Context, arg ListTenantsForUserParams) ([]TenantTenant, error) {
	rows, err := q.db.Query(ctx, listTenantsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantTenant{}
	for rows.Next() {
		var i TenantTenant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.Plan,
			&i.Region,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsForUserAfter = `-- name: ListTenantsForUserAfter :many
SELECT id, slug, name, status, plan, region, metadata, created_at, updated_at, deleted_at FROM tenant.tenants
WHERE deleted_at IS NULL
  AND EXISTS (
    SELECT 1 FROM rbac.user_roles ur
    WHERE ur.tenant_id = tenant.tenants.id AND ur.user_id = $1
  )
  AND (created_at < $2
       OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListTenantsForUserAfterParams struct {
	UserID          uuid.UUID
	BeforeCreatedAt time.Time
	BeforeID        uuid.UUID
	RowLimit        int32
}

func (q *Queries) ListTenantsForUserAfter(ctx context.Context, arg ListTenantsForUserAfterParams) ([]TenantTenant, error) {
	rows, err := q.db.Query(ctx, listTenantsForUserAfter,
		arg.UserID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantTenant{}
	for rows.Next() {
		var i TenantTenant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.Plan,
			&i.Region,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTenant = `-- name: SoftDeleteTenant :execrows
UPDATE tenant.tenants
SET deleted_at = NOW(), status = 'deleted', updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTenant(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTenant, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
