// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAdminPortalLinkByHash = `-- name: GetAdminPortalLinkByHash :one
SELECT id, tenant_id, capabilities, created_by, expires_at, revoked_at, last_used_at, created_at
FROM tenant.admin_portal_links WHERE token_hash = $1
`

type GetAdminPortalLinkByHashRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Capabilities []string
	CreatedBy    pgtype.UUID
	ExpiresAt    time.Time
	RevokedAt    pgtype.Timestamptz
	LastUsedAt   pgtype.Timestamptz
	CreatedAt    time.Time
}

func (q *Queries) GetAdminPortalLinkByHash(ctx context.Context, tokenHash string) (GetAdminPortalLinkByHashRow, error) {
	row := q.db.QueryRow(ctx, getAdminPortalLinkByHash, tokenHash)
	var i GetAdminPortalLinkByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Capabilities,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantNameByID = `-- name: GetTenantNameByID :one
SELECT name FROM tenant.tenants WHERE id = $1
`

func (q *Queries) GetTenantNameByID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTenantNameByID, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const insertAdminPortalLink = `-- name: InsertAdminPortalLink :one

INSERT INTO tenant.admin_portal_links (tenant_id, token_hash, capabilities, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, capabilities, created_by, expires_at, revoked_at, last_used_at, created_at
`

type InsertAdminPortalLinkParams struct {
	TenantID     uuid.UUID
	TokenHash    string
	Capabilities []string
	CreatedBy    pgtype.UUID
	ExpiresAt    time.Time
}

type InsertAdminPortalLinkRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Capabilities []string
	CreatedBy    pgtype.UUID
	ExpiresAt    time.Time
	RevokedAt    pgtype.Timestamptz
	LastUsedAt   pgtype.Timestamptz
	CreatedAt    time.Time
}

// Queries for the adminportal domain.
// Static queries against tenant.admin_portal_links and tenant.tenants are compiled
// by sqlc into ./dbgen. Dynamic/complex logic stays hand-written in adminportal.go.
func (q *Queries) InsertAdminPortalLink(ctx context.Context, arg InsertAdminPortalLinkParams) (InsertAdminPortalLinkRow, error) {
	row := q.db.QueryRow(ctx, insertAdminPortalLink,
		arg.TenantID,
		arg.TokenHash,
		arg.Capabilities,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i InsertAdminPortalLinkRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Capabilities,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAdminPortalLinksByTenant = `-- name: ListAdminPortalLinksByTenant :many
SELECT id, tenant_id, capabilities, created_by, expires_at, revoked_at, last_used_at, created_at
FROM tenant.admin_portal_links
WHERE tenant_id = $1 ORDER BY created_at DESC
`

type ListAdminPortalLinksByTenantRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Capabilities []string
	CreatedBy    pgtype.UUID
	ExpiresAt    time.Time
	RevokedAt    pgtype.Timestamptz
	LastUsedAt   pgtype.Timestamptz
	CreatedAt    time.Time
}

func (q *Queries) ListAdminPortalLinksByTenant(ctx context.Context, tenantID uuid.UUID) ([]ListAdminPortalLinksByTenantRow, error) {
	rows, err := q.db.Query(ctx, listAdminPortalLinksByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminPortalLinksByTenantRow{}
	for rows.Next() {
		var i ListAdminPortalLinksByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Capabilities,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAdminPortalLink = `-- name: RevokeAdminPortalLink :execrows
UPDATE tenant.admin_portal_links SET revoked_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND revoked_at IS NULL
`

type RevokeAdminPortalLinkParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) RevokeAdminPortalLink(ctx context.Context, arg RevokeAdminPortalLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAdminPortalLink, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAdminPortalLinkUsed = `-- name: TouchAdminPortalLinkUsed :exec
UPDATE tenant.admin_portal_links SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) TouchAdminPortalLinkUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAdminPortalLinkUsed, id)
	return err
}
