// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteEmailTemplate = `-- name: DeleteEmailTemplate :exec
DELETE FROM tenant.email_templates
WHERE tenant_id = $1 AND template_key = $2
`

type DeleteEmailTemplateParams struct {
	TenantID    uuid.UUID
	TemplateKey string
}

func (q *Queries) DeleteEmailTemplate(ctx context.Context, arg DeleteEmailTemplateParams) error {
	_, err := q.db.Exec(ctx, deleteEmailTemplate, arg.TenantID, arg.TemplateKey)
	return err
}

const getEmailTemplateOverride = `-- name: GetEmailTemplateOverride :one
SELECT subject, body
FROM tenant.email_templates
WHERE tenant_id = $1 AND template_key = $2
`

type GetEmailTemplateOverrideParams struct {
	TenantID    uuid.UUID
	TemplateKey string
}

type GetEmailTemplateOverrideRow struct {
	Subject string
	Body    string
}

func (q *Queries) GetEmailTemplateOverride(ctx context.Context, arg GetEmailTemplateOverrideParams) (GetEmailTemplateOverrideRow, error) {
	row := q.db.QueryRow(ctx, getEmailTemplateOverride, arg.TenantID, arg.TemplateKey)
	var i GetEmailTemplateOverrideRow
	err := row.Scan(&i.Subject, &i.Body)
	return i, err
}

const listEmailTemplateOverrides = `-- name: ListEmailTemplateOverrides :many

SELECT template_key, subject, body
FROM tenant.email_templates
WHERE tenant_id = $1
`

type ListEmailTemplateOverridesRow struct {
	TemplateKey string
	Subject     string
	Body        string
}

// Queries for the email-templates domain.
// Static queries against tenant.email_templates live here and are compiled by
// sqlc into ./dbgen. There are no dynamic queries in this domain.
func (q *Queries) ListEmailTemplateOverrides(ctx context.Context, tenantID uuid.UUID) ([]ListEmailTemplateOverridesRow, error) {
	rows, err := q.db.Query(ctx, listEmailTemplateOverrides, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmailTemplateOverridesRow{}
	for rows.Next() {
		var i ListEmailTemplateOverridesRow
		if err := rows.Scan(&i.TemplateKey, &i.Subject, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEmailTemplate = `-- name: UpsertEmailTemplate :exec
INSERT INTO tenant.email_templates (tenant_id, template_key, subject, body, updated_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (tenant_id, template_key) DO UPDATE
    SET subject    = EXCLUDED.subject,
        body       = EXCLUDED.body,
        updated_at = NOW()
`

type UpsertEmailTemplateParams struct {
	TenantID    uuid.UUID
	TemplateKey string
	Subject     string
	Body        string
}

func (q *Queries) UpsertEmailTemplate(ctx context.Context, arg UpsertEmailTemplateParams) error {
	_, err := q.db.Exec(ctx, upsertEmailTemplate,
		arg.TenantID,
		arg.TemplateKey,
		arg.Subject,
		arg.Body,
	)
	return err
}
