// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/google/uuid"
)

type PlatformBillingPlanPrice struct {
	PlanID      uuid.UUID
	Currency    string
	AmountMinor int64
}
